
Date: 08/03/83
From: Keith Petersen
To:   All
Re:   MDM712 file updates

Check your copies of the following files in MDM712.LBR.
Some may be missing or show a different CRC due to a
problem of the files being updated or added AFTER
MDM712 was initially released.  Make sure you have the
latest versions.

  MDM712.COM   CRC = 6A 64
  MDM712.UQD   CRC = C8 D0
  M712OX.AQM   CRC = C0 9E
  M712MM.AQM   CRC = A4 BC
  MDM712.IQF   CRC = C1 FC

MDM712.AQM should also be checked as it was updated
after initial release.

  MDM712.AQM   CRC = 43 81

Problems/complaints/bug reports/updates should be phoned
to Irv Hoff at (415) 948-2166 or sent via CompuServe's
CP-MIG to Irv Hoff 72365,70.

--end--
