$JOB LOAD ADVENTURE
.R LOAD
*ADVENT,LOAD.LS<ADVENT/S
*SEED,RND,SPEAK,GETWRD,USR,BITSET,DSTROY,JUGGLE,A5TOA1/O
*INITAD
*AMAIN/O
*SAVEGM
*RSTRGM
*BUG,GETIN,PCT,IO/C
*MOVE,PUT,CARRY,DROP,PSPEAK,RSPEAK,YES,VOCAB
*$
$END
