; modify for m80/l80.  Assemble 3 files, 2 relocatable
; Assumes CCPLUS and JOB/XJOB available.
slrmac ddtdisa/nr,ddtz/nr,ccinstal/n
slrnkp ddtzero/n,/v:5,/m:5,/p:0,ddtdisa,ddtz,/e
slrnkp ddtone/n,/p:100,ddtdisa,ddtz,/e
era ddtdisa.slr
era ddtz.slr
era temp.com
xjob
; CAUTION - *lines below work for DDTZ27, else delete & hand enter
;            ESPECIALLY the magic "l 18e1" command. * lines USE XJOB.
;-n ddtzero.cim  (do this when DDT is up, below)
;-l 100
;-d 203,204
;-n ddtone.com
;-l nnnn   (nn is 100h above lo byte 1st value from d above)
;-n temp.com
;-w
;-q   (or CTL-C to exit)
; WAIT FOR DDTZ to finish loading. Fasten the pieces together
ddtz ccinstal.com
*n ddtzero.cim
*l 100
*d 203,204
*n ddtone.com
*l 19e1
*n temp.com
*w
*q
era ddtzero.cim
era ddtone.com
era ccinstal.com
temp
; Now do the "SAVE nn ddtznew.com" to complete the job
™