; COLTAB.MAC  8/16 /78  DEFAULT "ALTSEQ" COLATING SEQUENCE TABLE FOR SORT MAIN
;
	ENTRY COLTAB,ENDCLT
;
	CSEG
;
; COLATING SEQUENCE TABLE.  1 BYTE FOR EACH KEY BYTE VALUE, CONTAINING
; 			    SEQUENCE POSITION FOR THAT KEY BYTE VALUE
;
;   TO CHANGE COLATING SEQUENCE, CHANGE CONTENTS OF DB (LEFT COLUMN)
;   FOR DESIRED CHARACTERS AS INDICATED BY COMMENTS (RIGHT COLUMN)
;
;	  SEQUENCE	   HEX	       ASCII	     ASCII
;	  POSITION	  VALUE	      GRAPHIC       NAME(S)
;	  --------        -----       -------   -----------------
COLTAB:	DB X'00'	;  00			NUL
	DB X'01'	;  01		^A	SOH
	DB X'02'	;  02		^B	STX
	DB X'03'	;  03		^C	ETX
	DB X'04'	;  04		^D	EOT
	DB X'05'	;  05		^E	ENQ
	DB X'06'	;  06		^F	ACK
	DB X'07'	;  07		^G	BEL
	DB X'08'	;  08		^H	BS
	DB X'09'	;  09		^I	HT
	DB X'0A'	;  0A		^J	LF
	DB X'0B'	;  0B		^K	VT
	DB X'0C'	;  0C		^L	FF
	DB X'0D'	;  0D		^M	CR
	DB X'0E'	;  0E		^N	SO
	DB X'0F'	;  0F		^O	SI
	DB X'10'	;  10		^P	DLE
	DB X'11'	;  11		^Q	DC1	X-ON
	DB X'12'	;  12		^R	DC2	TAPE
	DB X'13'	;  13		^S	DC3	X-OFF
	DB X'14'	;  14		^T	DC4	/TAPE
	DB X'15'	;  15		^U	NAK
	DB X'16'	;  16		^V	SYN
	DB X'17'	;  17		^W	ETB
	DB X'18'	;  18		^X	CAN
	DB X'19'	;  19		^Y	EM
	DB X'1A'	;  1A		^Z	SUB
	DB X'1B'	;  1B		^[	ESC
	DB X'1C'	;  1C		^\	FS
	DB X'1D'	;  1D		^]	GS
	DB X'1E'	;  1E		^^	RS
	DB X'1F'	;  1F		^_	US
	DB X'20'	;  20			SPACE
	DB X'21'	;  21		!
	DB X'22'	;  22		"
	DB X'23'	;  23		#
	DB X'24'	;  24		$
	DB X'25'	;  25		%
	DB X'26'	;  26		&
	DB X'27'	;  27		'
	DB X'28'	;  28		(
	DB X'29'	;  29		)
	DB X'2A'	;  2A		*
	DB X'2B'	;  2B		+
	DB X'2C'	;  2C		,
	DB X'2D'	;  2D		-
	DB X'2E'	;  2E		.
	DB X'2F'	;  2F		/
	DB X'30'	;  30		0
	DB X'31'	;  31		1
	DB X'32'	;  32		2
	DB X'33'	;  33		3
	DB X'34'	;  34		4
	DB X'35'	;  35		5
	DB X'36'	;  36		6
	DB X'37'	;  37		7
	DB X'38'	;  38		8
	DB X'39'	;  39		9
	DB X'3A'	;  3A		:
	DB X'3B'	;  3B		;
	DB X'3C'	;  3C		<
	DB X'3D'	;  3D		=
	DB X'3E'	;  3E		>
	DB X'3F'	;  3F		?
	DB X'40'	;  40		@
	DB X'41'	;  41		A
	DB X'42'	;  42		B
	DB X'43'	;  43		C
	DB X'44'	;  44		D
	DB X'45'	;  45		E
	DB X'46'	;  46		F
	DB X'47'	;  47		G
	DB X'48'	;  48		H
	DB X'49'	;  49		I
	DB X'4A'	;  4A		J
	DB X'4B'	;  4B		K
	DB X'4C'	;  4C		L
	DB X'4D'	;  4D		M
	DB X'4E'	;  4E		N
	DB X'4F'	;  4F		O
	DB X'50'	;  50		P
	DB X'51'	;  51		Q
	DB X'52'	;  52		R
	DB X'53'	;  53		S
	DB X'54'	;  54		T
	DB X'55'	;  55		U
	DB X'56'	;  56		V
	DB X'57'	;  57		W
	DB X'58'	;  58		X
	DB X'59'	;  59		Y
	DB X'5A'	;  5A		Z
	DB X'5B'	;  5B		[
	DB X'5C'	;  5C		\
	DB X'5D'	;  5D		]
	DB X'5E'	;  5E		^
	DB X'5F'	;  5F		_
	DB X'60'	;  60		`
	DB X'61'	;  61		LOWER CASE A
	DB X'62'	;  62		LOWER CASE B
	DB X'63'	;  63		LOWER CASE C
	DB X'64'	;  64		LOWER CASE D
	DB X'65'	;  65		LOWER CASE E
	DB X'66'	;  66		LOWER CASE F
	DB X'67'	;  67		LOWER CASE G
	DB X'68'	;  68		LOWER CASE H
	DB X'69'	;  69		LOWER CASE I
	DB X'6A'	;  6A		LOWER CASE J
	DB X'6B'	;  6B		LOWER CASE K
	DB X'6C'	;  6C		LOWER CASE L
	DB X'6D'	;  6D		LOWER CASE M
	DB X'6E'	;  6E		LOWER CASE N
	DB X'6F'	;  6F		LOWER CASE O
	DB X'70'	;  70		LOWER CASE P
	DB X'71'	;  71		LOWER CASE Q
	DB X'72'	;  72		LOWER CASE R
	DB X'73'	;  73		LOWER CASE S
	DB X'74'	;  74		LOWER CASE T
	DB X'75'	;  75		LOWER CASE U
	DB X'76'	;  76		LOWER CASE V
	DB X'77'	;  77		LOWER CASE W
	DB X'78'	;  78		LOWER CASE X
	DB X'79'	;  79		LOWER CASE Y
	DB X'7A'	;  7A		LOWER CASE Z
	DB X'7B'	;  7B		{
	DB X'7C'	;  7C		|
	DB X'7D'	;  7D		}	ALT MODE
	DB X'7E'	;  7E		~
	DB X'7F'	;  7F			DEL	RUBOUT
	DB X'80'	;  80
	DB X'81'	;  81
	DB X'82'	;  82
	DB X'83'	;  83
	DB X'84'	;  84
	DB X'85'	;  85
	DB X'86'	;  86
	DB X'87'	;  87
	DB X'88'	;  88
	DB X'89'	;  89
	DB X'8A'	;  8A
	DB X'8B'	;  8B
	DB X'8C'	;  8C
	DB X'8D'	;  8D
	DB X'8E'	;  8E
	DB X'8F'	;  8F
	DB X'90'	;  90
	DB X'91'	;  91
	DB X'92'	;  92
	DB X'93'	;  93
	DB X'94'	;  94
	DB X'95'	;  95
	DB X'96'	;  96
	DB X'97'	;  97
	DB X'98'	;  98
	DB X'99'	;  99
	DB X'9A'	;  9A
	DB X'9B'	;  9B
	DB X'9C'	;  9C
	DB X'9D'	;  9D
	DB X'9E'	;  9E
	DB X'9F'	;  9F
	DB X'A0'	;  A0
	DB X'A1'	;  A1
	DB X'A2'	;  A2
	DB X'A3'	;  A3
	DB X'A4'	;  A4
	DB X'A5'	;  A5
	DB X'A6'	;  A6
	DB X'A7'	;  A7
	DB X'A8'	;  A8
	DB X'A9'	;  A9
	DB X'AA'	;  AA
	DB X'AB'	;  AB
	DB X'AC'	;  AC
	DB X'AD'	;  AD
	DB X'AE'	;  AE
	DB X'AF'	;  AF
	DB X'B0'	;  B0
	DB X'B1'	;  B1
	DB X'B2'	;  B2
	DB X'B3'	;  B3
	DB X'B4'	;  B4
	DB X'B5'	;  B5
	DB X'B6'	;  B6
	DB X'B7'	;  B7
	DB X'B8'	;  B8
	DB X'B9'	;  B9
	DB X'BA'	;  BA
	DB X'BB'	;  BB
	DB X'BC'	;  BC
	DB X'BD'	;  BD
	DB X'BE'	;  BE
	DB X'BF'	;  BF
	DB X'C0'	;  C0
	DB X'C1'	;  C1
	DB X'C2'	;  C2
	DB X'C3'	;  C3
	DB X'C4'	;  C4
	DB X'C5'	;  C5
	DB X'C6'	;  C6
	DB X'C7'	;  C7
	DB X'C8'	;  C8
	DB X'C9'	;  C9
	DB X'CA'	;  CA
	DB X'CB'	;  CB
	DB X'CC'	;  CC
	DB X'CD'	;  CD
	DB X'CE'	;  CE
	DB X'CF'	;  CF
	DB X'D0'	;  D0
	DB X'D1'	;  D1
	DB X'D2'	;  D2
	DB X'D3'	;  D3
	DB X'D4'	;  D4
	DB X'D5'	;  D5
	DB X'D6'	;  D6
	DB X'D7'	;  D7
	DB X'D8'	;  D8
	DB X'D9'	;  D9
	DB X'DA'	;  DA
	DB X'DB'	;  DB
	DB X'DC'	;  DC
	DB X'DD'	;  DD
	DB X'DE'	;  DE
	DB X'DF'	;  DF
	DB X'E0'	;  E0
	DB X'E1'	;  E1
	DB X'E2'	;  E2
	DB X'E3'	;  E3
	DB X'E4'	;  E4
	DB X'E5'	;  E5
	DB X'E6'	;  E6
	DB X'E7'	;  E7
	DB X'E8'	;  E8
	DB X'E9'	;  E9
	DB X'EA'	;  EA
	DB X'EB'	;  EB
	DB X'EC'	;  EC
	DB X'ED'	;  ED
	DB X'EE'	;  EE
	DB X'EF'	;  EF
	DB X'F0'	;  F0
	DB X'F1'	;  F1
	DB X'F2'	;  F2
	DB X'F3'	;  F3
	DB X'F4'	;  F4
	DB X'F5'	;  F5
	DB X'F6'	;  F6
	DB X'F7'	;  F7
	DB X'F8'	;  F8
	DB X'F9'	;  F9
	DB X'FA'	;  FA
	DB X'FB'	;  FB
	DB X'FC'	;  FC
	DB X'FD'	;  FD
	DB X'FE'	;  FE
	DB X'FF'	;  FF
;
ENDCLT:	;END OF CODE TO KEEP IF COLTAB IN USE (SEE LOCWRK)
;
	END
