; EBCTAB.MAC  9/08/78   EBCDIC COLATING SEQUENCE TABLE FOR SORT MAIN
;			N.B. 128 ENTRIES ONLY, MUST BE USED IN CONJUNCTION
;			WITH "MASK-PARITY-BIT" OPTION.
;
	ENTRY EBCTAB,ENDEBC
;
	CSEG
;
; COLATING SEQUENCE TABLE.  1 BYTE FOR EACH KEY BYTE VALUE, CONTAINING
; 			    SEQUENCE POSITION FOR THAT KEY BYTE VALUE
;
;   TO CHANGE COLATING SEQUENCE, CHANGE CONTENTS OF DB (LEFT COLUMN)
;   FOR DESIRED CHARACTERS AS INDICATED BY COMMENTS (RIGHT COLUMN)
;
;	  SEQUENCE	   HEX	       ASCII	     ASCII
;	  POSITION	  VALUE	      GRAPHIC       NAME(S)
;	  --------        -----       -------   -----------------
EBCTAB:	DB X'00'	;  00			NUL
	DB X'01'	;  01		^A	SOH
	DB X'02'	;  02		^B	STX
	DB X'03'	;  03		^C	ETX
	DB X'37'	;  04		^D	EOT
	DB X'2D'	;  05		^E	ENQ
	DB X'2E'	;  06		^F	ACK
	DB X'2F'	;  07		^G	BEL
	DB X'16'	;  08		^H	BS
	DB X'05'	;  09		^I	HT
	DB X'25'	;  0A		^J	LF
	DB X'0B'	;  0B		^K	VT
	DB X'0C'	;  0C		^L	FF
	DB X'0D'	;  0D		^M	CR
	DB X'0E'	;  0E		^N	SO
	DB X'0F'	;  0F		^O	SI
	DB X'10'	;  10		^P	DLE
	DB X'11'	;  11		^Q	DC1	X-ON
	DB X'12'	;  12		^R	DC2	TAPE
	DB X'13'	;  13		^S	DC3	X-OFF  (1)
	DB X'3C'	;  14		^T	DC4	/TAPE
	DB X'3D'	;  15		^U	NAK
	DB X'32'	;  16		^V	SYN
	DB X'26'	;  17		^W	ETB
	DB X'18'	;  18		^X	CAN
	DB X'19'	;  19		^Y	EM      (1)
	DB X'3F'	;  1A		^Z	SUB
	DB X'27'	;  1B		^[	ESC
	DB X'22'	;  1C		^\	FS
	DB X'1D'	;  1D		^]	GS
	DB X'35'	;  1E		^^	RS
	DB X'1F'	;  1F		^_	US
	DB X'40'	;  20			SPACE
	DB X'5A'	;  21		!
	DB X'7F'	;  22		"
	DB X'7B'	;  23		#
	DB X'5B'	;  24		$
	DB X'6C'	;  25		%
	DB X'50'	;  26		&
	DB X'7D'	;  27		'
	DB X'4D'	;  28		(
	DB X'5D'	;  29		)
	DB X'5C'	;  2A		*
	DB X'4E'	;  2B		+
	DB X'6B'	;  2C		,
	DB X'60'	;  2D		-
	DB X'4B'	;  2E		.
	DB X'61'	;  2F		/
	DB X'F0'	;  30		0
	DB X'F1'	;  31		1
	DB X'F2'	;  32		2
	DB X'F3'	;  33		3
	DB X'F4'	;  34		4
	DB X'F5'	;  35		5
	DB X'F6'	;  36		6
	DB X'F7'	;  37		7
	DB X'F8'	;  38		8
	DB X'F9'	;  39		9
	DB X'7A'	;  3A		:
	DB X'5E'	;  3B		;
	DB X'4C'	;  3C		<
	DB X'7E'	;  3D		=
	DB X'6E'	;  3E		>
	DB X'6F'	;  3F		?
	DB X'7C'	;  40		@
	DB X'C1'	;  41		A
	DB X'C2'	;  42		B
	DB X'C3'	;  43		C
	DB X'C4'	;  44		D
	DB X'C5'	;  45		E
	DB X'C6'	;  46		F
	DB X'C7'	;  47		G
	DB X'C8'	;  48		H
	DB X'C9'	;  49		I
	DB X'D1'	;  4A		J
	DB X'D2'	;  4B		K
	DB X'D3'	;  4C		L
	DB X'D4'	;  4D		M
	DB X'D5'	;  4E		N
	DB X'D6'	;  4F		O
	DB X'D7'	;  50		P
	DB X'D8'	;  51		Q
	DB X'D9'	;  52		R
	DB X'E2'	;  53		S
	DB X'E3'	;  54		T
	DB X'E4'	;  55		U
	DB X'E5'	;  56		V
	DB X'E6'	;  57		W
	DB X'E7'	;  58		X
	DB X'E8'	;  59		Y
	DB X'E9'	;  5A		Z
	DB X'FF'	;  5B		[	NO EBCDIC EQUIVALENT, PUT LAST
	DB X'E1'	;  5C		\	(1)
	DB X'FF'	;  5D		]	NO EBCDIC EQUIVALENT, PUT LAST
	DB X'5F'	;  5E		^	(1)
	DB X'6D'	;  5F		_
	DB X'79'	;  60		`	(1)
	DB X'81'	;  61		LOWER CASE A
	DB X'82'	;  62		LOWER CASE B
	DB X'83'	;  63		LOWER CASE C
	DB X'84'	;  64		LOWER CASE D
	DB X'85'	;  65		LOWER CASE E
	DB X'86'	;  66		LOWER CASE F
	DB X'87'	;  67		LOWER CASE G
	DB X'88'	;  68		LOWER CASE H
	DB X'89'	;  69		LOWER CASE I
	DB X'91'	;  6A		LOWER CASE J
	DB X'92'	;  6B		LOWER CASE K
	DB X'93'	;  6C		LOWER CASE L
	DB X'94'	;  6D		LOWER CASE M
	DB X'95'	;  6E		LOWER CASE N
	DB X'96'	;  6F		LOWER CASE O
	DB X'97'	;  70		LOWER CASE P
	DB X'98'	;  71		LOWER CASE Q
	DB X'99'	;  72		LOWER CASE R
	DB X'A2'	;  73		LOWER CASE S
	DB X'A3'	;  74		LOWER CASE T
	DB X'A4'	;  75		LOWER CASE U
	DB X'A5'	;  76		LOWER CASE V
	DB X'A6'	;  77		LOWER CASE W
	DB X'A7'	;  78		LOWER CASE X
	DB X'A8'	;  79		LOWER CASE Y
	DB X'A9'	;  7A		LOWER CASE Z
	DB X'C0'	;  7B		{		(1)
	DB X'6A'	;  7C		|		(1)
	DB X'D0'	;  7D		}	ALT MODE   (1)
	DB X'A1'	;  7E		~		(1)
	DB X'07'	;  7F			DEL	RUBOUT
;
ENDEBC:	;END OF CODE TO NOT OVERLAY KEEP IF EBCTAB IN USE
;
; SOURCES: IBM 360 PRINCIPLES OF OPERATION, EXCEPT (1)
;	   A HEWLETT-PACKARD TABLE.
;
	END
