#!/bin/bash
srcdir=`pwd`
rm -f autosetup/*
( cd ~/src/autosetup/master && git pull > /dev/null && ./autosetup --install=$srcdir ) || exit 1
chmod -x         $(fossil changes --meta    autosetup) auto.def
fossil rm --hard $(fossil changes --missing autosetup)
fossil add autosetup/*
