#!/bin/bash
if [ $# = 2 ]
then
    cmp <(lz4 -dq "$1") <(lz4 -dq "$2")
    exit $?
else
    cat <<USAGE
usage: $0 <file1.lz> <file2.lz>

    Compares two lz4-compressed files, reporting differences in hex form.

USAGE
    exit 99
fi
