;
; SYSLIB Module Name:  SBDOS
; Author:  Richard Conn
; SYSLIB Version Number:  2.0
; Module Version Number:  1.0
; Module Entry Points:
;	BDOS
; Module External References:
;	None
;

;
;  BDOS -- STANDARD ROUTINE FOR CALLING THE CP/M BDOS
;	DO NOT AFFECT REGISTERS BC OR DE
;
BDOSE	EQU	5	; ENTRY POINT FOR BDOS

BDOS::
	PUSH	B	; SAVE BC
	PUSH	D	; SAVE DE
	CALL	BDOSE	; MAKE CALL
	POP	D	; GET DE
	POP	B	; GET BC
	RET

	END
