;
; SYSLIB Module Name:  SFDEL
; Author:  Richard Conn
; SYSLIB Version Number:  2.0
; Module Version Number:  1.0
; Module Entry Points:
;	F$DELETE
; Module External References:
;	BDOS
;

;
;  F$DELETE -- DELETE FILE WHOSE FCB IS PTED TO BY DE
;
	EXT	BDOS

F$DELETE::
	PUSH	H	; SAVE HL
	PUSH	B	; SAVE BC
	MVI	C,B$DEL
	CALL	BDOS
	POP	B	; RESTORE BC
	POP	H	; RESTORE HL
	RET

B$DEL	EQU	19	; DELETE FILE

	END
