;
; SYSLIB Module Name:  SFWRIT
; Author:  Richard Conn
; SYSLIB Version Number:  2.0
; Module Version Number:  1.0
; Module Entry Points:
;	F$WRITE
; Module External References:
;	BDOS
;

;
;  F$WRITE -- WRITE BLOCK TO FILE WHOSE FCB IS PTED TO BY DE
;	RET W/A=0 IF OK
;
	EXT	BDOS

F$WRITE::
	PUSH	H	; SAVE HL
	PUSH	B	; SAVE BC
	MVI	C,B$RECW
	CALL	BDOS
	POP	B	; RESTORE BC
	POP	H	; RESTORE HL
	RET

B$RECW	EQU	21	; WRITE RECORD

	END
