;
; SYSLIB Module Name:  SLCRLF
; Author:  Richard Conn
; SYSLIB Version Number:  2.0
; Module Version Number:  1.0
; Module Entry Points:
;	LCRLF
; Module External References:
;	LOUT
;

;
;  LCRLF -- 
;	PRINT <CR> AND <LF> ON LST:
;	AFFECT NO REGS
;
	EXT	LOUT

LCRLF::
	PUSH	PSW	; SAVE REG A AND FLAGS
	MVI	A,CR	; PRINT <CR>
	CALL	LOUT
	MVI	A,LF	; PRINT <LF>
	CALL	LOUT
	POP	PSW	; RESTORE REG A AND FLAGS
	RET

;
;  ASCII SPECIAL CHARACTER EQUATES
;
NULL	EQU	 0	; NULL
BEL	EQU	 7	; BELL
BS	EQU	 8	; BACKSPACE
TAB	EQU	 9	; TAB
LF	EQU	10	; LINE FEED
CR	EQU	13	; CARRIAGE RETURN
CTRLR	EQU	'R'-40H	; CTRL-R
CTRLU	EQU	'U'-40H	; CTRL-U
CTRLX	EQU	'X'-40H	; CTRL-X
DEL	EQU	7FH	; DELETE CHAR

	END
