;
; SYSLIB Module Name:  SLHL4H
; Author:  Richard Conn
; SYSLIB Version Number:  2.0
; Module Version Number:  1.0
; Module Entry Points:
;	LHL4HC
; Module External References:
;	LA2HC
;

;
;  LHL4HC -- Print HL as 4 Hex Characters
;	No Registers are to be affected.
;

	EXT	LA2HC	; PRINT A AS 2 HEX CHARACTERS

LHL4HC::
	PUSH	PSW	; SAVE A
	MOV	A,H	; PRINT H
	CALL	LA2HC
	MOV	A,L	; PRINT L
	CALL	LA2HC
	POP	PSW	; RESTORE A
	RET

	END
