;
;  SYSLIB Module Name:  SVERSI
;  Author:  Richard Conn
;  SYSLIB Version Number:  2.7
;  Module Version Number:  1.0
;  Module Entry Points:
;	VERSION
;  Module External References:
;	None
;

;
;	VERSION -- Return the SYSLIB Version Number in HL; H=Major Version,
; L=Minor Version
;
VERS	equ	27	; Version Number

VERSION::
	MVI	H,VERS/10	; GET MAJOR PART
	MVI	L,(VERS MOD 10)	; GET MINOR PART
	RET

;
;  Identifying Text
;
	DB	'SYSLIB Version '
	DB	(VERS/10)+'0','.',(VERS MOD 10)+'0'
	DB	' by Richard Conn'

	END
