
     ADDHD     43   |    ANDHD     46

     BBLINE    29   |    BIOS      65
     BDOS      65   |    BLINE     29


     CAPS      66   |    COMPB     38   |    CRC1K     49
     CAPSTR    66   |    COMPBC    38   |    CRC1UPD   48
     CATH      67   |    COMPHD    38   |    CRCCLR    48
     CCOUT     42   |    CONDIN    40   |    CRCDONE   48
     CIN       41   |    COUT      41   |    CRCK      49
     CLOUT     42   |    CPOUT     42   |    CRCUPD    48
     CMPH      44   |    CRC1CLR   48   |    CRLF      40
     CODEND    67   |    CRC1DONE  48   |    CST       41

     DBUFFER    6   |    DIRFS      5   |    DIRSEL    10
     DFREE      7   |    DIRLOAD    9   |    DIRSLOAD   9
     DIRALPHA  10   |    DIRNPACK  12   |    DIVHD     44
     DIRF       5   |    DIRPACK   11   |    DPARAMS    7

     EN        67   |    EVAL16    14
     EVAL      13   |    EVAL2     15
     EVAL10    14   |    EVAL8     15

     F$CLOSE   22   |    F$OPEN    21
     F$DELETE  23   |    F$READ    25
     F$EXIST   24   |    F$RENAME  24
     F$MAKE    23   |    F$WRITE   25
     F$MOPEN   22

     Fn$GET    19   |    FILLBC    68
     Fn$PUT    19   |    FNAME     26
     FIn$CLOSE 18   |    FOn$CLOSE 18
     FIn$OPEN  17   |    FOn$OPEN  18
     FILLB     68   |    FSIZE      8

     GETUD     53

     HFILB     68   |    HMOVB     69
     HFILBC    68   |    HMOVBC    69

     INITFCB   27   |    INSTR     39
     INLINE    30

     LA2HC     35   |    LHLDC     34
     LA3DC     36   |    LOGUD     53
     LADC      36   |    LOUT      41
     LCRLF     40   |    LPRINT    32
     LHL4HC    33   |    LPSTR     32
     LHL5DC    34



Š
     MA2HC     35   |    MHLDC     35
     MA3DC     36   |    MOVEB     69
     MADC      37   |    MOVEBC    69
     MHL4HC    33   |    MULHD     44
     MHL5DC    34

     NEGH      44

     ORHD      46

     PA2HC     35   |    PHLDC     34
     PA3DC     36   |    POUT      41
     PADC      36   |    PRINT     32
     PAUSE     69   |    PSTR      32
     PHL4HC    33   |    PUTUD     52
     PHL5DC    34

     RETUD     53   |    RND       51
     RIN       41   |    RNDINIT   50
     ROTLH     45   |    RNDSEED   50
     ROTRH     45

     SCANNER   38   |    SORT      55
     SHFTLH    45   |    SSBINIT   55
     SHFTRH    46   |    SUBHD     43

     XORHD     46

     ZCPRQ     58   |    ZFSTAT    60
     ZCPRSET   57   |    ZINIEXT   57
     ZDNFIND   62   |    ZINIMC    56
     ZFNAME    63   |    ZMCPTR    59
     ZFNINIT   62   |    ZPFIND    59





