/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "Clock_1.h"
#include "CPU_A6_aliases.h"
#include "CPU_A6.h"
#include "CPU_A5_aliases.h"
#include "CPU_A5.h"
#include "CPU_A4_aliases.h"
#include "CPU_A4.h"
#include "CPU_A3_aliases.h"
#include "CPU_A3.h"
#include "CLK_5_aliases.h"
#include "CLK_5.h"
#include "MAIN_CLK.h"
#include "CPU_CLK_aliases.h"
#include "CPU_CLK.h"
#include "RESET_CTRL_REG.h"
#include "CRESET_n_aliases.h"
#include "CRESET_n.h"
#include "WRESET_n_aliases.h"
#include "WRESET_n.h"
#include "CPU_A7_aliases.h"
#include "CPU_A7.h"
#include "IORQ_n_aliases.h"
#include "IORQ_n.h"
#include "SIOCS_n_aliases.h"
#include "SIOCS_n.h"
#include "IOCS_n_aliases.h"
#include "IOCS_n.h"
#include "CPU_A15_aliases.h"
#include "CPU_A15.h"
#include "CPU_A14_aliases.h"
#include "CPU_A14.h"
#include "MREQ_n_aliases.h"
#include "MREQ_n.h"
#include "IOWR_n_aliases.h"
#include "IOWR_n.h"
#include "EEPCS_n_aliases.h"
#include "EEPCS_n.h"
#include "SRAMCS2_n_aliases.h"
#include "SRAMCS2_n.h"
#include "SRAMCS1_n_aliases.h"
#include "SRAMCS1_n.h"
#include "cy_em_eeprom.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"

/*[]*/

