#
# CP/M Callback Filesystem
#

# Package

package:
		zip -q -r cpmcbfs.zip *
		zip -q -d cpmcbfs.zip *.bak */*.bak *.o

# Website

website:	package
		cp doc/* cpmcbfs.zip /pub/cpmcbfs
		-rm /pub/cpmcbfs/*.bak
		zip -q -d /pub/cpmcbfs/cpmcbfs.zip regkey.h
