#
#	Build 1802 version of the tools
#
all: as1802 ld1802 nm1802 osize1802 dumprelocs1802

HDR = as.h ld.h obj.h

AOBJ = as0.o as1-1802.o as2.o as3.o as4.o as6-1802.o

CFLAGS = -DTARGET_1802 -Wall -pedantic

as1802: $(HDR) $(AOBJ)
	cc -o as1802 $(AOBJ)

ld1802: $(HDR) ld.o
	cc -o ld1802 ld.o

nm1802: $(HDR) nm.o
	cc -o nm1802 nm.o

osize1802: $(HDR) osize.o
	cc -o osize1802 osize.o

dumprelocs1802: $(HDR) dumprelocs.o
	cc -o dumprelocs1802 dumprelocs.o

clean:
	rm -f *.o *~
	rm -f nm1802 ld1802 as1802 osize1802 dumprelocs1802

install:
	cp nm1802 ld1802 as1802 osize1802 dumprelocs1802 /opt/as1802/bin/
