         .title test33
         jmp st
;         .word 0   ;                    0
;         .word 0   ;                    2
         .word 0   ;                    4
         .word 0   ;                    6
         .word 0   ;                   10
         .word 0   ;                   12
         .word 0   ;                   14
         .word 0   ;                   16
         .word 0   ;                   20
         .word 0   ;                   22
         .word 0   ;                   24
         .word 0   ;                   26
         .word 0   ;                   30
         .word 0   ;                   32
         .word 0   ;                   34
         .word 0   ;                   36
         .word 0   ;                   40
         .word 0   ;                   42
         .word 0   ;                   44
         .word 0   ;                   46
         .word 0   ;                   50
         .word 0   ;                   52
         .word 0   ;                   54
         .word 0   ;                   56
         .word 0   ;                   60
         .word 0   ;                   62
         .word 0   ;                   64
         .word 0   ;                   66
         .word 0   ;                   70
         .word 0   ;                   72
         .word 0   ;                   74
         .word 0   ;                   76
         .word 0   ;                  100
         .word 0   ;                  102
         .word 0   ;                  104
         .word 0   ;                  106
         .word 0   ;                  110
         .word 0   ;                  112
         .word 0   ;                  114
         .word 0   ;                  116
         .word 0   ;                  120
         .word 0   ;                  122
         .word 0   ;                  124
         .word 0   ;                  126
         .word 0   ;                  130
         .word 0   ;                  132
         .word 0   ;                  134
         .word 0   ;                  136
         .word 0   ;                  140
         .word 0   ;                  142
         .word 0   ;                  144
         .word 0   ;                  146
         .word 0   ;                  150
         .word 0   ;                  152
         .word 0   ;                  154
         .word 0   ;                  156
         .word 0   ;                  160
         .word 0   ;                  162
         .word 0   ;                  164
         .word 0   ;                  166
         .word 0   ;                  170
         .word 0   ;                  172
         .word 0   ;                  174
         .word 0   ;                  176
         .word 0   ;                  200
         .word 0   ;                  202
         .word 0   ;                  204
         .word 0   ;                  206
         .word 0   ;                  210
         .word 0   ;                  212
         .word 0   ;                  214
         .word 0   ;                  216
         .word 0   ;                  220
         .word 0   ;                  222
         .word 0   ;                  224
         .word 0   ;                  226
         .word 0   ;                  230
         .word 0   ;                  232
         .word 0   ;                  234
         .word 0   ;                  236
         .word 0   ;                  240
         .word 0   ;                  242
         .word 0   ;                  244
         .word 0   ;                  246
         .word 0   ;                  250
         .word 0   ;                  252
         .word 0   ;                  254
         .word 0   ;                  256
         .word 0   ;                  260
         .word 0   ;                  262
         .word 0   ;                  264
         .word 0   ;                  266
         .word 0   ;                  270
         .word 0   ;                  272
         .word 0   ;                  274
         .word 0   ;                  276
         .word 0   ;                  300
         .word 0   ;                  302
         .word 0   ;                  304
         .word 0   ;                  306
         .word 0   ;                  310
         .word 0   ;                  312
         .word 0   ;                  314
         .word 0   ;                  316
         .word 0   ;                  320
         .word 0   ;                  322
         .word 0   ;                  324
         .word 0   ;                  326
         .word 0   ;                  330
         .word 0   ;                  332
         .word 0   ;                  334
         .word 0   ;                  336
         .word 0   ;                  340
         .word 0   ;                  342
         .word 0   ;                  344
         .word 0   ;                  346
         .word 0   ;                  350
         .word 0   ;                  352
         .word 0   ;                  354
         .word 0   ;                  356
         .word 0   ;                  360
         .word 0   ;                  362
         .word 0   ;                  364
         .word 0   ;                  366
         .word 0   ;                  370
         .word 0   ;                  372
         .word 0   ;                  374
         .word 0   ;                  376
         .word 0   ;                  400
         .word 0   ;                  402
         .word 0   ;                  404
         .word 0   ;                  406
         .word 0   ;                  410
         .word 0   ;                  412
         .word 0   ;                  414
         .word 0   ;                  416
         .word 0   ;                  420
         .word 0   ;                  422
         .word 0   ;                  424
         .word 0   ;                  426
         .word 0   ;                  430
         .word 0   ;                  432
         .word 0   ;                  434
         .word 0   ;                  436
         .word 0   ;                  440
         .word 0   ;                  442
         .word 0   ;                  444
         .word 0   ;                  446
         .word 0   ;                  450
         .word 0   ;                  452
         .word 0   ;                  454
         .word 0   ;                  456
         .word 0   ;                  460
         .word 0   ;                  462
         .word 0   ;                  464
         .word 0   ;                  466
         .word 0   ;                  470
         .word 0   ;                  472
         .word 0   ;                  474
         .word 0   ;                  476
stbot:
stk:
         .word 0   ;                  500
         .word 0   ;                  502
         .word 0   ;                  504
         .word 0   ;                  506
         .word 0   ;                  510
         .word 0   ;                  512
         .word 0   ;                  514
         .word 0   ;                  516
         .word 0   ;                  520
         .word 0   ;                  522
         .word 0   ;                  524
         .word 0   ;                  526
         .word 0   ;                  530
         .word 0   ;                  532
         .word 0   ;                  534
         .word 0   ;                  536
         .word 0   ;                  540
         .word 0   ;                  542
         .word 0   ;                  544
         .word 0   ;                  546
         .word 0   ;                  550
         .word 0   ;                  552
         .word 0   ;                  554
         .word 0   ;                  556
         .word 0   ;                  560
         .word 0   ;                  562
         .word 0   ;                  564
         .word 0   ;                  566
         .word 0   ;                  570
         .word 0   ;                  572
         .word 0   ;                  574
         .word 0   ;                  576
         .word 0   ;                  600
         .word 0   ;                  602
         .word 0   ;                  604
         .word 0   ;                  606
         .word 0   ;                  610
         .word 0   ;                  612
         .word 0   ;                  614
         .word 0   ;                  616
         .word 0   ;                  620
         .word 0   ;                  622
         .word 0   ;                  624
         .word 0   ;                  626
         .word 0   ;                  630
         .word 0   ;                  632
         .word 0   ;                  634
         .word 0   ;                  636
         .word 0   ;                  640
         .word 0   ;                  642
         .word 0   ;                  644
         .word 0   ;                  646
         .word 0   ;                  650
         .word 0   ;                  652
         .word 0   ;                  654
         .word 0   ;                  656
         .word 0   ;                  660
         .word 0   ;                  662
         .word 0   ;                  664
         .word 0   ;                  666
         .word 0   ;                  670
         .word 0   ;                  672
         .word 0   ;                  674
         .word 0   ;                  676
         .word 0   ;                  700
         .word 0   ;                  702
         .word 0   ;                  704
         .word 0   ;                  706
         .word 0   ;                  710
         .word 0   ;                  712
         .word 0   ;                  714
         .word 0   ;                  716
         .word 0   ;                  720
         .word 0   ;                  722
         .word 0   ;                  724
         .word 0   ;                  726
         .word 0   ;                  730
         .word 0   ;                  732
         .word 0   ;                  734
         .word 0   ;                  736
         .word 0   ;                  740
         .word 0   ;                  742
         .word 0   ;                  744
         .word 0   ;                  746
         .word 0   ;                  750
         .word 0   ;                  752
         .word 0   ;                  754
         .word 0   ;                  756
         .word 0   ;                  760
         .word 0   ;                  762
         .word 0   ;                  764
         .word 0   ;                  766
         .word 0   ;                  770
         .word 0   ;                  772
         .word 0   ;                  774
         .word 0   ;                  776
;
; general purpose register definitions
;
r0       = %0
r1       = %1
r2       = %2
r3       = %3
r4       = %4
r5       = %5
r6       = %6
r7       = %7
sp       = %6
pc       = %7
ac0      = %0
ac1      = %1
ac2      = %2
ac3      = %3
ac4      = %4
ac5      = %5
;
; error macro - provide unique error number
;
..n      = 0
         .macro error
..n      = ..n + 1
         mov #..n,@#ddisp
         halt
         .endm error
;
; start of test
;
st:
tst26x:
         mov #1000,r6
         mov #mmutrp,@#250
         clr @#177572
         jsr pc,mmu
         mov #77400,@#172200
         mov #37,@#172516
         mov #0,@#177776
         mov r6,r1
         mov #140000,@#177776
         mov r1,r6
         mov #1,@#177572
         .word 7014
         halt

tstm16:
         mov #1000,r6
         mov #mmutrp,@#250
         clr @#177572
         clr flag
         clr savmr0
         clr savmr1
         clr savmr2
         jsr pc,mmu
         clr @#177776
         mov #20200,r2
         mov #77400,@#172302
         mov #1,flag
         mov #1,@#177572
         mov r7,r1
         mfpi (r2)+
         mov #100003,r4
         jsr pc,ts10

         mov #30000,@#177776
         jsr pc,mmu
         mov #77400,@#177636
         mov #1600,@#177676
         mov #160000,r2
         mov #1,flag
         mov #1,@#177572
         mov r7,r1
         mfpd (r2)+
         mov #100177,r4
         jsr pc,ts10

         mov #10000,@#177776
         jsr pc,mmu
         mov #77400,@#172212
         mov #120000,r2
         mov #1,flag
         mov #1,@#177572
         mov r7,r1
         mfpi (r2)+
         mov #100053,r4
         jsr pc,ts10
         mov #20000,@#177776
         jsr pc,mmu
         mov #40000,r2
         mov #1,flag
         mov #1,@#177572
         mov r7,r1
         mfpd (r2)+
         mov #100105,r4
         jsr pc,ts10
         jmp t10fin
;
ts10:
         cmp #0,flag
         beq 1$
         error
1$:
         cmp r4,savmr0
         beq 2$
         error
2$:
         cmp #22,savmr1
         beq 3$
         error
3$:
         cmp r1,savmr2
         beq 4$
         error
4$:
         clr savmr0
         clr savmr1
         clr savmr2
         rts pc
;
t10fin:

t33:
         mov #177600,@#172356
         mov #77406,@#172316
         mov #177600,@#177656
         mov #77406,@#177616
         mov #77406,@#172300
         mov #77406,@#177600
         mov #77406,@#172310
         mov #125252,r2
         mov #117776,r5
;
         mov #170000,@#172350
         mov #20,@#172516        ; 22

         mov @#t44,@#250
         mov #140000,r6
         mov #1,@#177572
         mov #20000,@#177776
         mfpd (r2)+
         mov r2,-(r6)
t44:     mov @#177572,r0
         mov @#177574,r1

         mov #1,@#177572         ; mmu on
         halt
;
;
;
mmu:
         mov r0,-(sp)
         mov r1,-(sp)
         mov r2,-(sp)
         mov #177600,r0
         jsr pc,pdr
         jsr pc,par
         jsr pc,par
         mov #172200,r0
         jsr pc,pdr
         jsr pc,par
         jsr pc,par
         jsr pc,pdr
         jsr pc,par
         jsr pc,par
         mov #27,@#172516
         mov (sp)+,r2
         mov (sp)+,r1
         mov (sp)+,r0
         rts pc
;
;
;
pdr:
         clr r2
pdr1:
         mov #77406,(r0)+
         add #1,r2
         cmp #16.,r2
         bne pdr1
         rts pc
;
;
;
par:
         clr r1
par1:
         mov r1,(r0)+
         add #200,r1
         cmp #1600,r1
         bne par1
         mov #177600,(r0)+
         rts pc
;
;
;
mmutrp:
         cmp flag,#1
         beq 1$
         error
1$:
         mov r0,-(sp)
         mov @#177776,r0
         ash #-14,r0
         cmp r0,#2
         bne ok
         br notok
ok:
         mov @#177776,r0
         ash #2,r0
         ash #-14,r0
         cmp r0,#2
         bne ok1
notok:
         clr 4(sp)
ok1:
         mov @#177572,savmr0
         mov @#177574,savmr1
         mov @#177576,savmr2
         clr @#177572
         clr flag
         mov (sp)+,r0
         rti
;
; czkdkb0 data
;
savmr0:  .word 0
savmr1:  .word 0
savmr2:  .word 0
savuse:  .word 0
savsup:  .word 0
flag:    .word 0
ddisp:   .word 0
         .even

         .word 0,0,0,0,0,0,0,0,0
tothier: .ascii /ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ/
