.\" $Id
.\" cmoc - A C-like cross-compiler
.\" Copyright (C) 2003-2016 Pierre Sarrazin <http://sarrazip.com/>
.\"
.\" This program is free software: you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation, either version 3 of the License, or
.\" (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program.  If not, see <http://www.gnu.org/licenses/>.
.\"
.TH cmoc "1" "April 24th, 2020" "" ""
.SH NAME
cmoc - A C-like cross-compiler
.SH SYNOPSIS
.B cmoc [options] program.c
.SH DESCRIPTION
\fBcmoc\fR
is a Unix-based program that compiles a C-like language,
generates 6809 assembly language programs and assembles them
into executables for the Tandy Color Computer's Disk Basic environment
and for the Vectrex video game console.
.TP
See the official web site at http://sarrazip.com/dev/cmoc.html
.TP
See the manual at http://sarrazip.com/dev/cmoc-manual.html
.SH OPTIONS
.TP
\fB\-\-help\fR
display a help page (which lists several other options) and exit
.TP
\fB\-\-version\fR
display version information and exit
.SH LICENSE
This program is free software; you may redistribute it under the terms of
the GNU General Public License, version 3 or later.
This program has absolutely no warranty.
.SH AUTHOR
Pierre Sarrazin <http://sarrazip.com/>
.SH BUGS
Possibly. Please report them.
