
all:
	make -C Dhrystone
	make -C HelloWorld
	make -C Rectangles
	make -C Demo
	make -C Screenmodes
	make -C JPEG
	make -C Modplayer

clean:
	make -C Dhrystone clean
	make -C HelloWorld clean
	make -C Rectangles clean
	make -C Demo clean
	make -C Screenmodes clean
	make -C Modplayer clean


