vil.h::&.c; touch &.c
vil-main
vil-basic
vil-exp
%
il.h::&.c; touch &.c
vil-main
vil-basic
vil-exp
%
&.c::&.r; cc &.c +r
vil-main
vil-basic
vil-exp
%
&.r::vil; cc *.r +o=vil
vil-main
vil-basic
vil-exp
