asm68 -lQSx crt105.s -o ..\crt105
asm68 -lQSx crt133.s -o ..\crt133
asm68 -lQSx crt147.s -o ..\crt147
asm68 -lQSx crt167.s -o ..\crt167
asm68 -lQSx crt306.s -o ..\crt306
asm68 -lQSx crt332.s -o ..\crt332
asm68 -lQSx crt68k.s -o ..\crt68k
asm68 -lQSx -dQUICKFIX crt105.s -o ..\qcrt105
asm68 -lQSx -dQUICKFIX crt133.s -o ..\qcrt133
asm68 -lQSx -dQUICKFIX crt147.s -o ..\qcrt147
asm68 -lQSx -dQUICKFIX crt167.s -o ..\qcrt167
asm68 -lQSx -dQUICKFIX crt306.s -o ..\qcrt306
asm68 -lQSx -dQUICKFIX crt332.s -o ..\qcrt332
asm68 -lQSx -dQUICKFIX crt68k.s -o ..\qcrt68k

