         .title test27 - scoped div test
         jmp st
;         .word 0   ;                    0
;         .word 0   ;                    2
         .word 0   ;                    4
         .word 0   ;                    6
         .word 0   ;                   10
         .word 0   ;                   12
         .word 0   ;                   14
         .word 0   ;                   16
         .word 0   ;                   20
         .word 0   ;                   22
         .word 0   ;                   24
         .word 0   ;                   26
         .word 0   ;                   30
         .word 0   ;                   32
         .word 0   ;                   34
         .word 0   ;                   36
         .word 0   ;                   40
         .word 0   ;                   42
         .word 0   ;                   44
         .word 0   ;                   46
         .word 0   ;                   50
         .word 0   ;                   52
         .word 0   ;                   54
         .word 0   ;                   56
         .word 0   ;                   60
         .word 0   ;                   62
         .word 0   ;                   64
         .word 0   ;                   66
         .word 0   ;                   70
         .word 0   ;                   72
         .word 0   ;                   74
         .word 0   ;                   76
         .word 0   ;                  100
         .word 0   ;                  102
         .word 0   ;                  104
         .word 0   ;                  106
         .word 0   ;                  110
         .word 0   ;                  112
         .word 0   ;                  114
         .word 0   ;                  116
         .word 0   ;                  120
         .word 0   ;                  122
         .word 0   ;                  124
         .word 0   ;                  126
         .word 0   ;                  130
         .word 0   ;                  132
         .word 0   ;                  134
         .word 0   ;                  136
         .word 0   ;                  140
         .word 0   ;                  142
         .word 0   ;                  144
         .word 0   ;                  146
         .word 0   ;                  150
         .word 0   ;                  152
         .word 0   ;                  154
         .word 0   ;                  156
         .word 0   ;                  160
         .word 0   ;                  162
         .word 0   ;                  164
         .word 0   ;                  166
         .word 0   ;                  170
         .word 0   ;                  172
         .word 0   ;                  174
         .word 0   ;                  176
         .word 0   ;                  200
         .word 0   ;                  202
         .word 0   ;                  204
         .word 0   ;                  206
         .word 0   ;                  210
         .word 0   ;                  212
         .word 0   ;                  214
         .word 0   ;                  216
         .word 0   ;                  220
         .word 0   ;                  222
         .word 0   ;                  224
         .word 0   ;                  226
         .word 0   ;                  230
         .word 0   ;                  232
         .word 0   ;                  234
         .word 0   ;                  236
         .word 0   ;                  240
         .word 0   ;                  242
         .word 0   ;                  244
         .word 0   ;                  246
         .word 0   ;                  250
         .word 0   ;                  252
         .word 0   ;                  254
         .word 0   ;                  256
         .word 0   ;                  260
         .word 0   ;                  262
         .word 0   ;                  264
         .word 0   ;                  266
         .word 0   ;                  270
         .word 0   ;                  272
         .word 0   ;                  274
         .word 0   ;                  276
         .word 0   ;                  300
         .word 0   ;                  302
         .word 0   ;                  304
         .word 0   ;                  306
         .word 0   ;                  310
         .word 0   ;                  312
         .word 0   ;                  314
         .word 0   ;                  316
         .word 0   ;                  320
         .word 0   ;                  322
         .word 0   ;                  324
         .word 0   ;                  326
         .word 0   ;                  330
         .word 0   ;                  332
         .word 0   ;                  334
         .word 0   ;                  336
         .word 0   ;                  340
         .word 0   ;                  342
         .word 0   ;                  344
         .word 0   ;                  346
         .word 0   ;                  350
         .word 0   ;                  352
         .word 0   ;                  354
         .word 0   ;                  356
         .word 0   ;                  360
         .word 0   ;                  362
         .word 0   ;                  364
         .word 0   ;                  366
         .word 0   ;                  370
         .word 0   ;                  372
         .word 0   ;                  374
         .word 0   ;                  376
         .word 0   ;                  400
         .word 0   ;                  402
         .word 0   ;                  404
         .word 0   ;                  406
         .word 0   ;                  410
         .word 0   ;                  412
         .word 0   ;                  414
         .word 0   ;                  416
         .word 0   ;                  420
         .word 0   ;                  422
         .word 0   ;                  424
         .word 0   ;                  426
         .word 0   ;                  430
         .word 0   ;                  432
         .word 0   ;                  434
         .word 0   ;                  436
         .word 0   ;                  440
         .word 0   ;                  442
         .word 0   ;                  444
         .word 0   ;                  446
         .word 0   ;                  450
         .word 0   ;                  452
         .word 0   ;                  454
         .word 0   ;                  456
         .word 0   ;                  460
         .word 0   ;                  462
         .word 0   ;                  464
         .word 0   ;                  466
         .word 0   ;                  470
         .word 0   ;                  472
         .word 0   ;                  474
         .word 0   ;                  476
stbot:
stk:
         .word 0   ;                  500
         .word 0   ;                  502
         .word 0   ;                  504
         .word 0   ;                  506
         .word 0   ;                  510
         .word 0   ;                  512
         .word 0   ;                  514
         .word 0   ;                  516
         .word 0   ;                  520
         .word 0   ;                  522
         .word 0   ;                  524
         .word 0   ;                  526
         .word 0   ;                  530
         .word 0   ;                  532
         .word 0   ;                  534
         .word 0   ;                  536
         .word 0   ;                  540
         .word 0   ;                  542
         .word 0   ;                  544
         .word 0   ;                  546
         .word 0   ;                  550
         .word 0   ;                  552
         .word 0   ;                  554
         .word 0   ;                  556
         .word 0   ;                  560
         .word 0   ;                  562
         .word 0   ;                  564
         .word 0   ;                  566
         .word 0   ;                  570
         .word 0   ;                  572
         .word 0   ;                  574
         .word 0   ;                  576
         .word 0   ;                  600
         .word 0   ;                  602
         .word 0   ;                  604
         .word 0   ;                  606
         .word 0   ;                  610
         .word 0   ;                  612
         .word 0   ;                  614
         .word 0   ;                  616
         .word 0   ;                  620
         .word 0   ;                  622
         .word 0   ;                  624
         .word 0   ;                  626
         .word 0   ;                  630
         .word 0   ;                  632
         .word 0   ;                  634
         .word 0   ;                  636
         .word 0   ;                  640
         .word 0   ;                  642
         .word 0   ;                  644
         .word 0   ;                  646
         .word 0   ;                  650
         .word 0   ;                  652
         .word 0   ;                  654
         .word 0   ;                  656
         .word 0   ;                  660
         .word 0   ;                  662
         .word 0   ;                  664
         .word 0   ;                  666
         .word 0   ;                  670
         .word 0   ;                  672
         .word 0   ;                  674
         .word 0   ;                  676
         .word 0   ;                  700
         .word 0   ;                  702
         .word 0   ;                  704
         .word 0   ;                  706
         .word 0   ;                  710
         .word 0   ;                  712
         .word 0   ;                  714
         .word 0   ;                  716
         .word 0   ;                  720
         .word 0   ;                  722
         .word 0   ;                  724
         .word 0   ;                  726
         .word 0   ;                  730
         .word 0   ;                  732
         .word 0   ;                  734
         .word 0   ;                  736
         .word 0   ;                  740
         .word 0   ;                  742
         .word 0   ;                  744
         .word 0   ;                  746
         .word 0   ;                  750
         .word 0   ;                  752
         .word 0   ;                  754
         .word 0   ;                  756
         .word 0   ;                  760
         .word 0   ;                  762
         .word 0   ;                  764
         .word 0   ;                  766
         .word 0   ;                  770
         .word 0   ;                  772
         .word 0   ;                  774
         .word 0   ;                  776
;
; misc definitions
;
ht       = 11
lf       = 12
cr       = 15
crlf     = 200
ps       = 177776
stklmt   = 177774
pirq     = 177772
dswr     = 177570
ddisp    = 177570

;
; general purpose register definitions
;
r0       = %0
r1       = %1
r2       = %2
r3       = %3
r4       = %4
r5       = %5
r6       = %6
r7       = %7
sp       = %6
pc       = %7


..n      = 0
         .macro error
..n      = ..n + 1
         mov #..n,@#ddisp
         halt
         .endm error
;
;
;

;         .=1000
st:
         mov #2$,@#4
         mov #340,@#6
         clr r1
10$:
         mov #777,r6
         clr @#177766
         clr @#177776
         tst @#177700
1$:
         error
2$:
         cmp #0,sp
         beq 3$
         error
3$:
         cmp #1$,(sp)+
         beq 4$
         error
4$:
         cmp #0,(sp)
         beq 5$
         error
5$:
         cmp #124,@#177766
         beq 6$
         error
6$:
         halt
;
;
;

;         mov #0, @#0             ; erase the jump at loc 0, so we know if we ended there
;         inc @#count
;         mov @#count,@#177570    ; keep count of how many loops we've done, and copy this into the display register
;         mov #stk, sp
;
; tst1
;
tst1:
         clr r0
         mov #20001,r1
         div #2,r0
         cmp r0,#10000
         beq 1$
         error
1$:
         cmp r1,#1
         beq 2$
         error
2$:
;
;
;
tst213:
         clr @#177776
         clr r6
         mov @#0,r5
         mov @#2,r1
         mov #137,@#0
         mov #te126a,@#2
         scc
         div #2,r6
a126$:
         mov #stbot,r6
         error
te126a:
         cmp #0,@#177776
         beq 1$
         mov #stbot,r6
         error
1$:
         mov #a126$,r4
         asr r4
         cmp r4,r6
         beq 2$
         mov #stbot,r6
         error
2$:
         mov r5,@#0
         mov r1,@#2
         mov #stbot,r6
         mov #6,r2
         mov #47,r3
         scc
         div r2,r3
         cmp #2,@#177776
         beq 3$
         error
3$:
         cmp #6,r2
         beq 4$
         error
4$:
         cmp #47,r3
         beq 5$
         error
5$:
         clr r4
         mov #4,r5
         scc
         div #0,r4
         cmp #7,@#177776
         beq 6$
         error
6$:
         cmp #0,r4
         beq 7$
         error
7$:
         cmp #4,r5
         beq 8$
         error
8$:
         mov #4,r0
         mov #10,r5
         clr r4
         scc
         div r0,r4
         cmp #0,@#177776
         beq 9$
;         mov r0,400     ??
         error
;         mov 400,r0     ??
9$:
         cmp #4,r0
         beq 10$
         error
10$:
         cmp #2,r4
         beq 11$
         error
11$:
         cmp #0,r5
         beq 12$
         error
12$:
         mov #10,r5
         clr r4
         scc
         div #3,r4
         cmp #0,@#177776
         beq 13$
         error
13$:
         cmp #2,r4
         beq 14$
         error
14$:
         cmp #2,r5
         beq 15$
         error
15$:
         mov #te126b,r1
16$:
         mov r1,@#expdat
         mov (r1),r4
         mov 4(r1),r3
         mov 2(r1),r5
         scc
         div 4(r1),r4
         cmp 6(r1),@#177776
         beq 17$
         error
17$:
         cmp 10(r1),r5
         beq 18$
         error
18$:
         cmp 12(r1),r4
         beq 19$
         error
19$:
         cmp @#expdat,r1
         beq 20$
         error
         mov @#expdat,r1         ; ??
20$:
         cmp 4(r1),r3
         beq 21$
         error
         mov r3,4(r1)            ; ??
21$:
         add #14,r1
         cmp (r1),#333
         bne 16$
         jmp fin126
te126b:
         .word 177777            ; 1
         .word 177777
         .word 177777
         .word 0
         .word 0
         .word 1

         .word 0                 ; 2
         .word 177777
         .word 177777
         .word 12
         .word 177777
         .word 0

         .word 177777            ; 3
         .word 0
         .word 177777
         .word 2
         .word 0
         .word 177777

         .word 0                 ; 4
         .word 7642
         .word 7643
         .word 4
         .word 7642
         .word 0

         .word 0                 ; 5
         .word 137
         .word 177543
         .word 4
         .word 137
         .word 0

         .word 0                 ; 6
         .word 7643
         .word 7643
         .word 0
         .word 0
         .word 1

         .word 100000            ; 7
         .word 4376
         .word 10021
         .word 12
         .word 4376
         .word 100000

         .word 177700            ; 8
         .word 170033
         .word 10021
         .word 10
         .word 171307
         .word 176024

         .word 177700            ; 9
         .word 170033
         .word 167757
         .word 0
         .word 171307
         .word 1754

         .word 0                 ; 10
         .word 177777
         .word 1
         .word 2
         .word 177777
         .word 0

         .word 177777            ; 11
         .word 45716
         .word 1
         .word 12
         .word 45716
         .word 177777

         .word 0                 ; 12
         .word 2
         .word 177770
         .word 4
         .word 2
         .word 0

         .word 177777            ; 13
         .word 177776
         .word 10
         .word 4
         .word 177776
         .word 0

         .word 1                 ; 14
         .word 177777
         .word 1
         .word 2
         .word 177777
         .word 1

         .word 1                 ; 15
         .word 0
         .word 2
         .word 2
         .word 0
         .word 1

         .word 1                 ; 16
         .word 0
         .word 3
         .word 0
         .word 1
         .word 52525

         .word 23                ; 17
         .word 16054
         .word 16537
         .word 0
         .word 10222
         .word 246

         .word 333
fin126:
;
; end of tests
;
;
; tests from fkac - translated
;
tst254:
         mov #0,r0
         mov #4,r1
         div #2,r0
         mfps r2
         cmpb #0,r2
         beq 1$
         error
1$:
         cmp #2,r0
         beq 2$
         error
2$:
         cmp #0,r1
         beq 3$
         error
3$:
;
tst255:
         mov #-1,r0
         mov #-9.,r1
         div #3,r0
         mfps r2
         cmpb #10,r2
         beq 1$
         error
1$:
         cmp #-3,r0
         beq 2$
         error
2$:
         cmp #0,r1
         beq 3$
         error
3$:
;
tst256:
         mov #0,r0
         mov #9.,r1
         div #2,r0
         mfps r2
         cmpb #0,r2
         beq 1$
         error
1$:
         cmp #4,r0
         beq 2$
         error
2$:
         cmp #1,r1
         beq 3$
         error
3$:
;
tst257:
         mov #-1,r0
         mov #-9.,r1
         div #2,r0
         mfps r2
         cmpb #10,r2
         beq 1$
         error
1$:
         cmp #-4,r0
         beq 2$
         error
2$:
         cmp #-1,r1
         beq 3$
         error
3$:
;
tst260:
         mov #0,r0
         mov #2,r1
         div #-3,r0
         mfps r2
         cmpb #4,r2
         beq 1$
         error
1$:
         cmp #0,r0
         beq 2$
         error
2$:
         cmp #2,r1
         beq 3$
         error
3$:
;
tst261:
         mov #-1,r0
         mov #-2,r1
         div #3,r0
         mfps r2
         cmpb #4,r2
         beq 1$
         error
1$:
         cmp #0,r0
         beq 2$
         error
2$:
         cmp #-2,r1
         beq 3$
         error
3$:
;
tst262:
         mov #-1,r0
         mov #-1,r1
         div #1,r0
         mfps r2
         cmpb #10,r2
         beq 1$
         error
1$:
         cmp #-1,r0
         beq 2$
         error
2$:
         cmp #0,r1
         beq 3$
         error
3$:
;
tst263:
         mov #0,r0
         mov #0,r1
         div #1,r0
         mfps r2
         cmpb #4,r2
         beq 1$
         error
1$:
         cmp #0,r0
         beq 2$
         error
2$:
         cmp #0,r1
         beq 3$
         error
3$:
;
tst264:
         mov #-1,r0
         mov #125252,r1
         div #2,r0
         mfps r2
         cmpb #10,r2
         beq 1$
         error
1$:
         cmp #152525,r0
         beq 2$
         error
2$:
         cmp #0,r1
         beq 3$
         error
3$:
;
tst265:
         mov #-1,r0
         mov #-1,r1
         div #-1,r0
         mfps r2
         cmpb #0,r2
         beq 1$
         error
1$:
         cmp #1,r0
         beq 2$
         error
2$:
         cmp #0,r1
         beq 3$
         error
3$:
;
tst266:
         mov #25253,r0
         mov #1,r1
         div #125252,r0
         mfps r2
         cmpb #10,r2
         beq 1$
         error
1$:
         cmp #100000,r0
         beq 2$
         error
2$:
         cmp #1,r1
         beq 3$
         error
3$:
;
tst267:
         mov #37777,r0
         mov #77777,r1
         div #77777,r0
         mfps r2
         cmpb #0,r2
         beq 1$
         error
1$:
         cmp #77777,r0
         beq 2$
         error
2$:
         cmp #77776,r1
         beq 3$
         error
3$:
;
tst270:
         mov #0,r0
         mov #100000,r1
         div #2,r0
         mfps r2
         cmpb #0,r2
         beq 1$
         error
1$:
         cmp #40000,r0
         beq 2$
         error
2$:
         cmp #0,r1
         beq 3$
         error
3$:
;
tst271:
         mov #177777,r0
         mov #77777,r1
         div #177776,r0
         mfps r2
         cmpb #0,r2
         beq 1$
         error
1$:
         cmp #40000,r0
         beq 2$
         error
2$:
         cmp #177777,r1
         beq 3$
         error
3$:
;
tst:
         mov #0,r0
         mov #52525,r1
         div #52525,r0
         mfps r2
         cmpb #0,r2
         beq 1$
         error
1$:
         cmp #1,r0
         beq 2$
         error
2$:
         cmp #0,r1
         beq 3$
         error
3$:
;
tst273:
         mov #0,r0
         mov #77777,r1
         div #0,r0
         mfps r2
         cmpb #3,r2
         beq 1$
         error
1$:
;
tst274:
         mov #77777,r0
         mov #177777,r1
         div #2,r0
         mfps r2
         cmpb #2,r2
         beq 1$
         error
1$:
         mov #11111,r1
         mov #22222,r2
         mov #33333,r3
         mov #44444,r4
         halt
;
; data for czkdjb0
;
sloc00:  .word 0
sloc01:  .word 0

expdat:  .word 0

seq:     .word 0
sps:     .word 0
spsj:    .word 0

count:   .word 0


