

	declare 
		memptr entry returns (pointer),
		memsiz entry returns (fixed(15)),
		memwds entry returns (fixed(15)),
		dfcb0  entry returns (pointer),
		dfcb1  entry returns (pointer),
		dbuff  entry returns (pointer),
		reboot entry,
		rdcon  entry returns (character(1)),
		wrcon  entry (character(1)),
		rdrdr  entry returns (character(1)),
		wrpun  entry (character(1)),
		wrlst  entry (character(1)),
		coninp entry returns (character(1)),
		conout entry (character(1)),
		rdstat entry returns (bit(1)),
		getio  entry returns (bit(8)),
		setio  entry (bit(8)),
		wrstr  entry (pointer),
		rdbuf  entry (pointer),
		break  entry returns (bit(1)),
		vers   entry returns (bit(16)),
		reset  entry,
		select entry (fixed(7)),
		open   entry (pointer) returns (fixed(7)),
		close  entry (pointer) returns (fixed(7)),
		sear   entry (pointer) returns (fixed(7)),
		searn  entry returns (fixed(7)),
		delete entry (pointer),
		rdseq  entry (pointer) returns (fixed(7)),
		wrseq  entry (pointer) returns (fixed(7)),
		make   entry (pointer) returns (fixed(7)),
		rename entry (pointer),
		logvec entry returns (bit(16)),
		curdsk entry returns (fixed(7)),
		setdma entry (pointer),
		wpdisk entry,
		rovec  entry returns (bit(16)),
		filatt entry (pointer),
		getusr entry returns (fixed(7)),
		setusr entry (fixed(7)),
		rdran  entry (pointer) returns (fixed(7)),
		wrran  entry (pointer) returns (fixed(7)),
		filsiz entry (pointer),
		setrec entry (pointer),
		resdrv entry (bit(16)),
		wrranz entry (pointer) returns (fixed(7));
