// Copyright (C) 1991-2011 Altera Corporation
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, Altera MegaCore Function License 
// Agreement, or other applicable license agreement, including, 
// without limitation, that your use is for the sole purpose of 
// programming logic devices manufactured by Altera and sold by 
// Altera or its authorized distributors.  Please refer to the 
// applicable agreement for further details.


// Generated by Quartus II 32-bit Version 11.1 (Build Build 216 11/23/2011)
// Created on Mon Apr 09 09:30:28 2012

TG68Test TG68Test_inst
(
	.clk(clk_sig) ,	// input  clk_sig
	.counter(counter_sig) ,	// output [15:0] counter_sig
	.reset(reset_sig) 	// input  reset_sig
);

