# shuffleBits - Convert PDP-8 binary file to MIF file
#	Read in the binary file creates by macro8x assembler
#	Write out the Altera formatted Memory Initialization (.MIF) file to the command prompt window

import sys

print('argv',sys.argv)
print('count',len(sys.argv))
inFileName = sys.argv[1]

binList = []
with open(inFileName, "rb") as f:
	binList = f.read()
# print(binList)
pairOffset = 0
theList = []
while pairOffset < len(binList)-1:
	val1 = int(binList[pairOffset]) & 0x3f;
	val2 = int(binList[pairOffset+1]) & 0x3f;
	val = (val1 << 6) | val2;
	txt = '{0:o}'
	theList.append(txt.format(val))
	pairOffset += 2

print('-- Generated by shuffleBits.py')
print('-- ')
print('DEPTH = '+ str(len(theList))  +';')
print('WIDTH = 12;')
print('ADDRESS_RADIX = DECIMAL;')
print('DATA_RADIX = OCTAL;')
print('CONTENT BEGIN')
lineCount = 0
addrCount = 0
for cell in theList:
	if lineCount == 0:
		if len(str(addrCount)) == 4:
			outVal = str(addrCount) + ':'
		elif len(str(addrCount)) == 3:
			outVal = '0' + str(addrCount) + ':'
		elif len(str(addrCount)) == 2:
			outVal = '00' + str(addrCount) + ':'
		elif len(str(addrCount)) == 1:
			outVal = '000' + str(addrCount) + ':'
		print(outVal,end='')
	lineCount += 1
	addrCount += 1	
	newCell	= ''
	if len(cell) == 4:
		newCell = cell
	elif len(cell) == 3:
		newCell = '0' + cell
	elif len(cell) == 2:
		newCell = '00' + cell
	elif len(cell) == 1:
		newCell = '000' + cell
	print(' ' + newCell,end='')
	if lineCount == 8:
		lineCount = 0
		print(';')
print(';\nEND;')


