REM CHEMIST....... (one of the original programs).....

 10 PRINT"THE FICTICIOUS CHEMICAL KYPTOCYANIC CAN ONLY BE"
 20 PRINT "DILUTED BY THE RATIO OF 7 PARTS WATER TO 3 PARTS ACID."
 30 PRINT "IF ANY OTHER RATIO IS ATTEMPTED , THE ACID BECOMES UNSTABLE"
 40 PRINT "AND SOON EXPLODES.  GIVEN THE AMOUNT OF ACID, YOU MUST"
 50 PRINT "DECIDE HOW MUCH WATER TO ADD FOR DILUTION.  IF YOU MISS"
 60 PRINT "YOU FACE THE CONSEQUENCES."
 70 A=INT(RND(1)*50)
 80 W=7*A/3
 90 PRINT A"LITERS OF KRYPTOCYANIC ACID.  HOW MUCH WATER";
 100 INPUT R
 110 LET D=ABS(W-R)
 120 IF D>W/20 THEN 180
 130 PRINT "GOOD JOB! YOU MAY BREATHE NOW, BUT DON'T INHALE THE FUMES!"
 140 PRINT
 150 IF G=10 THEN 260
 160 G=G+1
 170 GOTO 70
 180 PRINT "SIZZLE! YOU HAVE JUST BEEN DESALINATED INTO A BLOB"
 190 PRINT"OF QUIVERING PROTOPLASM!"
 200 T=T+1
 210 G=0
 220 IF T=9 THEN 300
 230 PRINT"HOWEVER,YOU MAY TRY AGAIN WITH ANOTHER LIFE."
 240 PRINT
 250 GOTO 70
 260 PRINT"YOUR A FANTASTIC CHEMIST!! (OR A FLOP WITH A CALCULATOR)
 270 PRINT"WOULD YOU CHANCE TO TRY AGAIN?(Y/N)";
 280 INPUT G$:IF G$="Y" THEN GOTO 70 :G=0
 290 END
 300 PRINT"YOUR NINE LIVES ARE USED UP,BUT YOU WILL BE LONG REMEMBERED"
 310 PRINT"FOR YOUR CONTRIBUTION TO COMIC BOOK CHEMISTRY"
 320 END


