;
; SYSLIB Module Name:  SCAPS
; Author:  Richard Conn
; SYSLIB Version Number:  2.0
; Module Version Number:  1.0
; Module Entry Points:
;	CAPS
; Module External References:
;	None
;

;
;  CAPS -- Capitalize ASCII Character in A
;
CAPS::
	ANI	7FH	; MASK OUT MSB
	CPI	61H	; LESS THAN SMALL LETTER A?
	RC
	CPI	7AH+1	; BETWEEN SMALL A AND SMALL Z?
	RNC
	ANI	5FH	; REMOVE BIT 5 TO CAPITALIZE (0X0X XXXX)
	RET

	END
