;
; SYSLIB Module Name:  SCAPST
; Author:  Richard Conn
; SYSLIB Version Number:  2.0
; Module Version Number:  1.0
; Module Entry Points:
;	CAPSTR
; Module External References:
;	CAPS
;

;
;  CAPSTR -- Capitalize String Pted to by HL
;	This routine simply capitalizes the <NULL>-terminated string
; pointed to by HL.  No Registers are affected.
;
	EXT	CAPS

CAPSTR::
	PUSH	PSW	; SAVE REGS
	PUSH	H
CAPSLP:
	MOV	A,M	; GET CHAR
	ORA	A	; DONE?
	JZ	CAPSDN
	CALL	CAPS	; CAPITALIZE IT
	INX	H	; PT TO NEXT
	JMP	CAPSLP
CAPSDN:
	POP	H	; GET REGS
	POP	PSW
	RET

	END
