;
; SYSLIB Module Name:  SCODEN
; Author:  Richard Conn
; SYSLIB Version Number:  2.0
; Module Version Number:  1.0
; Module Entry Points:
;	CODEND
; Module External References:
;	None
;

;
;  This module returns the address of the last element of code in
;  in the user's object program.  This address should correspond to
;  the first available block for scratch buffer area.
;
;  Input Parameters:  None
;  Output Parameters:  HL = Address of next page
;

CODEND::
	LXI	H,ENDALL	; RETURN NEXT PAGE
	INR	H
	MVI	L,0
	RET
ENDALL:
	DB	0

	END
