;
; SYSLIB Module Name:  SCOMPH
; Author:  Richard Conn
; SYSLIB Version Number:  2.0
; Module Version Number:  1.0
; Module Entry Points:
;	COMPHD
; Module External References:
;	None
;

;
;  SCOMPHD --
;	Compare HL with DE.  On return, Zero means HL=DE; Carry means
; HL<DE.
;	PSW is affected.  HL and DE are not.
;

COMPHD::
	MOV	A,H	; COMPARE HIGH
	CMP	D
	RNZ		; IF NOT ZERO, FLAGS ARE SET
	MOV	A,L	; COMPARE LOW
	CMP	E
	RET

	END
