;
; SYSLIB Module Name:  SEPRINT
; Author:  Richard Conn
; SYSLIB Version Number:  2.0
; Module Version Number:  1.0
; Module Entry Points:
;	EPRINT
; Module External References:
;	EPSTR
;

;
;  EPRINT -- 
;	PRINT STRING PTED TO BY RET ADR UNTIL BINARY 0 ENCOUNTERED
;	AFFECT NO REGISTERS OR FLAGS; UNLIKE PRINT, EPRINT DOES NOT
;	PERFORM CONTROL CHARACTER INTERPRETATION
;
	EXT	EPSTR

EPRINT::
	XTHL		; HL=ADR, OLD HL ON STACK
	CALL	EPSTR	; PRINT STRING PTED TO BY HL
	XTHL		; RESTORE HL AND NEW RET ADR
	RET

	END
