;
; SYSLIB Module Name:  SFEXIS
; Author:  Richard Conn
; SYSLIB Version Number:  2.0
; Module Version Number:  1.0
; Module Entry Points:
;	F$EXIST
; Module External References:
;	BDOS
;

;
;  EXTERNALS
;
	EXT	BDOS

;
;  F$EXIST -- Search current disk and user for file whose FCB is pted
;	to by DE; return Zero Flag Set (Z) if not found, NZ if found
;
F$EXIST::
	PUSH	H	; SAVE REGS
	PUSH	B
	MVI	C,17	; SEARCH FOR FIRST
	CALL	BDOS
	POP	B	; RESTORE REGS
	POP	H
	INR	A	; 0 IF NOT FOUND
	RET

	END
