;
; SYSLIB Module Name:  SFMAKE
; Author:  Richard Conn
; SYSLIB Version Number:  2.0
; Module Version Number:  1.0
; Module Entry Points:
;	F$MAKE
; Module External References:
;	BDOS		F$DELETE
;

;
;  F$MAKE -- MAKE FILE WHOSE FCB IS PTED TO BY DE
;
	EXT	BDOS
	EXT	F$DELETE

F$MAKE::
	CALL	F$DELETE	; DELETE FILE
	PUSH	H		; SAVE HL
	PUSH	B		; SAVE BC
	MVI	C,B$MAKE
	CALL	BDOS
	POP	B		; RESTORE BC
	POP	H		; RESTORE HL
	RET

B$MAKE	EQU	22	; MAKE FILE

	END
