;
; SYSLIB Module Name:  SFREAD
; Author:  Richard Conn
; SYSLIB Version Number:  2.0
; Module Version Number:  1.0
; Module Entry Points:
;	F$READ
; Module External References:
;	BDOS
;

;
;  F$READ -- READ BLOCK FROM FILE WHOSE FCB IS PTED TO BY DE
;	RET W/A=0 IF OK
;
	EXT	BDOS

F$READ::
	PUSH	H	; SAVE HL
	PUSH	B	; SAVE BC
	MVI	C,B$RECR
	CALL	BDOS
	POP	B	; RESTORE BC
	POP	H	; RESTORE HL
	RET

B$RECR	EQU	20	; READ RECORD

	END
