;
; SYSLIB Module Name:  SLPRIN
; Author:  Richard Conn
; SYSLIB Version Number:  2.0
; Module Version Number:  1.0
; Module Entry Points:
;	LPRINT
; Module External References:
;	LPSTR
;

;
;  LPRINT -- 
;	PRINT STRING PTED TO BY RET ADR UNTIL BINARY 0 ENCOUNTERED ON LST:
;	AFFECT NO REGISTERS OR FLAGS
;
	EXT	LPSTR

LPRINT::
	XTHL		; HL=ADR, OLD HL ON STACK
	CALL	LPSTR	; PRINT STRING PTED TO BY HL
	XTHL		; RESTORE HL AND NEW RET ADR
	RET

	END
