;
; SYSLIB Module Name:  SMHL4H
; Author:  Richard Conn
; SYSLIB Version Number:  2.3
; Module Version Number:  1.0
; Module Entry Points:
;	MHL4HC
; Module External References:
;	MA2HC
;
;
;	MHL4HC -- Store HL as 4 Hex Characters in memory; on input, DE pts
; to 4-byte buffer and HL=value; on return, DE pts to byte after buffer
;	No Registers are to be affected.
;

	EXT	MA2HC	; STORE A AS 2 HEX CHARACTERS

MHL4HC::
	PUSH	PSW	; SAVE A
	MOV	A,H	; PRINT H
	CALL	MA2HC
	MOV	A,L	; PRINT L
	CALL	MA2HC
	POP	PSW	; RESTORE A
	RET

	END
