;
; SYSLIB Module Name:  SPHL4C
; Author:  Richard Conn
; SYSLIB Version Number:  2.0
; Module Version Number:  1.0
; Module Entry Points:
;	PHL4HC
; Module External References:
;	PA2HC
;

;
;  PHL4HC -- Print HL as 4 Hex Characters
;	No Registers are to be affected.
;

	EXT	PA2HC	; PRINT A AS 2 HEX CHARACTERS

PHL4HC::
	PUSH	PSW	; SAVE A
	MOV	A,H	; PRINT H
	CALL	PA2HC
	MOV	A,L	; PRINT L
	CALL	PA2HC
	POP	PSW	; RESTORE A
	RET

	END
