;
; SYSLIB Module Name:  SPRINT
; Author:  Richard Conn
; SYSLIB Version Number:  2.0
; Module Version Number:  1.0
; Module Entry Points:
;	PRINT
; Module External References:
;	PSTR
;

;
;  PRINT -- 
;	PRINT STRING PTED TO BY RET ADR UNTIL BINARY 0 ENCOUNTERED
;	AFFECT NO REGISTERS OR FLAGS
;
	EXT	PSTR

PRINT::
	XTHL		; HL=ADR, OLD HL ON STACK
	CALL	PSTR	; PRINT STRING PTED TO BY HL
	XTHL		; RESTORE HL AND NEW RET ADR
	RET

	END
