C=120
V=2
#=F,C

Y
C A,Q D--
Q D-
Q D--,S G+
S F+
Q D-,S E+
S D+

Y
C A,Q D--
Q D-
Q D--,S G+
S F+
Q D-,S E+
S D+

Y
S (F-,F)
S (G-,G)
Q (A,A+)
Q (G-,G)
Q (F-,F)

Y
Q (E-,E)
Q (A,A+)
Q (F-,F)
Q (D-,D)

Y
C A,Q D--
Q D-
Q D--,S G+
S F+
Q D-,S E+
S D+

Y
C A,Q D--
Q D-
Q D--,S G+
S F+
Q D-,S E+
S D+

Y
S (F-,F)
S (G-,G)
Q (A,A+)
Q (G-,G)
Q (F-,F)

Y
Q (E-,E)
Q (A,A+)
C (D-,D)


Y
C A,Q D--
Q D-
Q D--,S G+
S F+
Q D-,S E+
S D+

Y
C A,Q D--
Q D-
Q D--,S G+
S F+
Q D-,S E+
S D+

Y
S (F-,F)
S (G-,G)
Q (A,A+)
Q (G-,G)
Q (F-,F)

Y
Q (E-,E)
Q (A,A+)
Q (F-,F)
Q (D-,D)

Y
C A,Q D--
Q D-
Q D--,S G+
S F+
Q D-,S E+
S D+

Y
C A,Q D--
Q D-
Q D--,S G+
S F+
Q D-,S E+
S D+

Y
S (F-,F)
S (G-,G)
Q (A,A+)
Q (G-,G)
Q (F-,F)

Y
Q (E-,E)
Q (A,A+)
C (D-,D)

Y
Q A-,S C+
S D+
Q (A,E+)
Q A-,S C+
S D+
Q (A,E+)

Y
Q (A-,A++)
Q (A,E+)
C E+,Q A
Q A

Y
Q (A-,A++)
Q (A,E+)
Q (A-,A++)
Q (A,E+)

Y
Q A-,S D+
S C+
Q A,S B+
S A+
Q (E--,B+)
Q (E-,E)

Y
Q (E--,E+)
Q (D#+,E-)
Q (E--,E)
C D+,Q E-
Q E--
Q (E-,C+)
Q (E--,A++)
Q (E-,G#+)

Y
Q (E--,E+)
Q (D#+,E-)
Q (E--,E)
C D+,Q E-
Q E--
Q (E-,C+)
Q (E--,A++)
Q (E-,G#+)

Y
Q E--,S E+
S D#+
Q E-,S C+
S D+
Q E--,S E+
S D#+
Q E-,S C+
S D+

Y
Q (E--,E+)
Q (E-,G#)
Q (C-,A+)
Q (D-,D+)

Y
C E-,S C+
S D+
Q E+
Q (A-,A+)
Q (D-,D)

Y
S (C-,C)
S (D-,D)
Q (E-,E)
C (A-,A)


Y
C A,Q D--
Q D-
Q D--,S G+
S F+
Q D-,S E+
S D+

Y
C A,Q D--
Q D-
Q D--,S G+
S F+
Q D-,S E+
S D+

Y
S (F-,F)
S (G-,G)
Q (A,A+)
Q (G-,G)
Q (F-,F)

Y
Q (E-,E)
Q (A,A+)
Q (F-,F)
Q (D-,D)

Y
C A,Q D--
Q D-
Q D--,S G+
S F+
Q D-,S E+
S D+

Y
C A,Q D--
Q D-
Q D--,S G+
S F+
Q D-,S E+
S D+

Y
S (F-,F)
S (G-,G)
Q (A,A+)
Q (G-,G)
Q (F-,F)

Y
Q (E-,E)
Q (A,A+)
C (D-,D)

Y
Q A-,S C+
S D+
Q (A,E+)
Q A-,S C+
S D+
Q (A,E+)

Y
Q (A-,A++)
Q (A,E+)
C E+,Q A
Q A

Y
Q (A-,A++)
Q (A,E+)
Q (A-,A++)
Q (A,E+)

Y
Q A-,S D+
S C+
Q A,S B+
S A+
Q (E--,B+)
Q (E-,E)

Y
Q (E--,E+)
Q (D#+,E-)
Q (E--,E)
C D+,Q E-
Q E--
Q (E-,C+)
Q (E--,A++)
Q (E-,G#+)

Y
Q (E--,E+)
Q (D#+,E-)
Q (E--,E)
C D+,Q E-
Q E--
Q (E-,C+)
Q (E--,A++)
Q (E-,G#+)

Y
Q E--,S E+
S D#+
Q E-,S C+
S D+
Q E--,S E+
S D#+
Q E-,S C+
S D+

Y
Q (E--,E+)
Q (E-,G#)
Q (C-,A+)
Q (D-,D+)

Y
C E-,S C+
S D+
Q E+
Q (A-,A+)
Q (D-,D)

Y
S (C-,C)
S (D-,D)
Q (E-,E)
C (A-,A)

Y
C A,Q D--
Q D-
Q D--,S G+
S F+
Q D-,S E+
S D+

Y
C A,Q D--
Q D-
Q D--,S G+
S F+
Q D-,S E+
S D+

Y
S (F-,F)
S (G-,G)
Q (A,A+)
Q (G-,G)
Q (F-,F)

Y
Q (E-,E)
Q (A,A+)
Q (F-,F)
Q (D-,D)

Y
C A,Q D--
Q D-
Q D--,S G+
S F+
Q D-,S E+
S D+

Y
C A,Q D--
Q D-
Q D--,S G+
S F+
Q D-,S E+
S D+

Y
S (F-,F)
S (G-,G)
Q (A,A+)
Q (G-,G)
Q (F-,F)

Y
Q (E-,E)
Q (A,A+)
M (F,D+)

$
