.Dd March 5, 2015
.Dt srec2bin 1
.Os kk_srec
.Sh NAME
.Nm srec2bin
.Nd Convert Motorola SREC encoded data to binary
.Sh SYNOPSIS
.Nm
.Op Fl a Ar address_offset | Fl A
.Op Fl i Ar input_file.srec
.Op Fl o Ar output_file.bin
.Op Fl v
.Sh DESCRIPTION
.Nm
reads Motorola SREC encoded data from standard input and writes the
decoded binary data to standard output.
.Sh OPTIONS
.Bl -tag -width -indent
.It Fl a Ar address_offset
Set the address of the first byte output to
.Ar address_offset
- by default the output respects the addres read from the input, but
with many SREC files produced by compilers the data have an offset
(possibly mega- or gigabytes), which may cause the output file to be
unnecessarily large. The offset specified by this parameter is
subtracted from all addresses read from the file.
.It Fl A
Autodetect the address offset (see
.Ar -a
above), i.e., the first output byte written will have the address of the
first byte of input - this option should almost always be used!
.It Fl i Ar file
Read the Motorola SREC input from
.Ar file
instead of standard input
.It Fl o Ar file
Write the binary output to
.Ar file
instead of standard output
.It Fl v
Print extra status messages to standard error
.El
.Sh EXAMPLES
Read Motorola SREC from
.Ar input.srec
and write the binary output to 
.Ar output.bin
such that the first byte of input is written as the first byte
of output (even if the input specifies an address offset):
.Pp
.Bd -ragged -offset indent
.Nm
.Fl A
.Fl i
.Ar input.srec
.Fl o
.Ar output.bin
.Ed
.Pp
Read Motorola SREC from
.Ar input.srec
and write the binary output to
.Ar output.bin
such that the offset
.Ar 0x8000000
is subtracted from input addresses:
.Bd -ragged -offset indent
.Nm
.Fl a
.Ar 0x8000000
.Fl i
.Ar input.srec
.Fl o
.Ar output.bin
.Ed
.Sh AUTHOR
.An "Kimmo Kulovesi" Aq http://arkku.com
