         .title test25
         jmp st
;         .word 0   ;                    0
;         .word 0   ;                    2
         .word 0   ;                    4
         .word 0   ;                    6
         .word 0   ;                   10
         .word 0   ;                   12
         .word 0   ;                   14
         .word 0   ;                   16
         .word 0   ;                   20
         .word 0   ;                   22
         .word 0   ;                   24
         .word 0   ;                   26
         .word 0   ;                   30
         .word 0   ;                   32
         .word 0   ;                   34
         .word 0   ;                   36
         .word 0   ;                   40
         .word 0   ;                   42
         .word 0   ;                   44
         .word 0   ;                   46
         .word 0   ;                   50
         .word 0   ;                   52
         .word 0   ;                   54
         .word 0   ;                   56
         .word 0   ;                   60
         .word 0   ;                   62
         .word 0   ;                   64
         .word 0   ;                   66
         .word 0   ;                   70
         .word 0   ;                   72
         .word 0   ;                   74
         .word 0   ;                   76
         .word 0   ;                  100
         .word 0   ;                  102
         .word 0   ;                  104
         .word 0   ;                  106
         .word 0   ;                  110
         .word 0   ;                  112
         .word 0   ;                  114
         .word 0   ;                  116
         .word 0   ;                  120
         .word 0   ;                  122
         .word 0   ;                  124
         .word 0   ;                  126
         .word 0   ;                  130
         .word 0   ;                  132
         .word 0   ;                  134
         .word 0   ;                  136
         .word 0   ;                  140
         .word 0   ;                  142
         .word 0   ;                  144
         .word 0   ;                  146
         .word 0   ;                  150
         .word 0   ;                  152
         .word 0   ;                  154
         .word 0   ;                  156
         .word 0   ;                  160
         .word 0   ;                  162
         .word 0   ;                  164
         .word 0   ;                  166
         .word 0   ;                  170
         .word 0   ;                  172
         .word 0   ;                  174
         .word 0   ;                  176
         .word 0   ;                  200
         .word 0   ;                  202
         .word 0   ;                  204
         .word 0   ;                  206
         .word 0   ;                  210
         .word 0   ;                  212
         .word 0   ;                  214
         .word 0   ;                  216
         .word 0   ;                  220
         .word 0   ;                  222
         .word 0   ;                  224
         .word 0   ;                  226
         .word 0   ;                  230
         .word 0   ;                  232
         .word 0   ;                  234
         .word 0   ;                  236
         .word 0   ;                  240
         .word 0   ;                  242
         .word 0   ;                  244
         .word 0   ;                  246
         .word 0   ;                  250
         .word 0   ;                  252
         .word 0   ;                  254
         .word 0   ;                  256
         .word 0   ;                  260
         .word 0   ;                  262
         .word 0   ;                  264
         .word 0   ;                  266
         .word 0   ;                  270
         .word 0   ;                  272
         .word 0   ;                  274
         .word 0   ;                  276
         .word 0   ;                  300
         .word 0   ;                  302
         .word 0   ;                  304
         .word 0   ;                  306
         .word 0   ;                  310
         .word 0   ;                  312
         .word 0   ;                  314
         .word 0   ;                  316
         .word 0   ;                  320
         .word 0   ;                  322
         .word 0   ;                  324
         .word 0   ;                  326
         .word 0   ;                  330
         .word 0   ;                  332
         .word 0   ;                  334
         .word 0   ;                  336
         .word 0   ;                  340
         .word 0   ;                  342
         .word 0   ;                  344
         .word 0   ;                  346
         .word 0   ;                  350
         .word 0   ;                  352
         .word 0   ;                  354
         .word 0   ;                  356
         .word 0   ;                  360
         .word 0   ;                  362
         .word 0   ;                  364
         .word 0   ;                  366
         .word 0   ;                  370
         .word 0   ;                  372
         .word 0   ;                  374
         .word 0   ;                  376
         .word 0   ;                  400
         .word 0   ;                  402
         .word 0   ;                  404
         .word 0   ;                  406
         .word 0   ;                  410
         .word 0   ;                  412
         .word 0   ;                  414
         .word 0   ;                  416
         .word 0   ;                  420
         .word 0   ;                  422
         .word 0   ;                  424
         .word 0   ;                  426
         .word 0   ;                  430
         .word 0   ;                  432
         .word 0   ;                  434
         .word 0   ;                  436
         .word 0   ;                  440
         .word 0   ;                  442
         .word 0   ;                  444
         .word 0   ;                  446
         .word 0   ;                  450
         .word 0   ;                  452
         .word 0   ;                  454
         .word 0   ;                  456
         .word 0   ;                  460
         .word 0   ;                  462
         .word 0   ;                  464
         .word 0   ;                  466
         .word 0   ;                  470
         .word 0   ;                  472
         .word 0   ;                  474
         .word 0   ;                  476
         .word 0   ;                  500
         .word 0   ;                  502
         .word 0   ;                  504
         .word 0   ;                  506
         .word 0   ;                  510
         .word 0   ;                  512
         .word 0   ;                  514
         .word 0   ;                  516
         .word 0   ;                  520
         .word 0   ;                  522
         .word 0   ;                  524
         .word 0   ;                  526
         .word 0   ;                  530
         .word 0   ;                  532
         .word 0   ;                  534
         .word 0   ;                  536
         .word 0   ;                  540
         .word 0   ;                  542
         .word 0   ;                  544
         .word 0   ;                  546
         .word 0   ;                  550
         .word 0   ;                  552
         .word 0   ;                  554
         .word 0   ;                  556
         .word 0   ;                  560
         .word 0   ;                  562
         .word 0   ;                  564
         .word 0   ;                  566
         .word 0   ;                  570
         .word 0   ;                  572
         .word 0   ;                  574
         .word 0   ;                  576
         .word 0   ;                  600
         .word 0   ;                  602
         .word 0   ;                  604
         .word 0   ;                  606
         .word 0   ;                  610
         .word 0   ;                  612
         .word 0   ;                  614
         .word 0   ;                  616
         .word 0   ;                  620
         .word 0   ;                  622
         .word 0   ;                  624
         .word 0   ;                  626
         .word 0   ;                  630
         .word 0   ;                  632
         .word 0   ;                  634
         .word 0   ;                  636
         .word 0   ;                  640
         .word 0   ;                  642
         .word 0   ;                  644
         .word 0   ;                  646
         .word 0   ;                  650
         .word 0   ;                  652
         .word 0   ;                  654
         .word 0   ;                  656
         .word 0   ;                  660
         .word 0   ;                  662
         .word 0   ;                  664
         .word 0   ;                  666
         .word 0   ;                  670
         .word 0   ;                  672
         .word 0   ;                  674
         .word 0   ;                  676
         .word 0   ;                  700
         .word 0   ;                  702
         .word 0   ;                  704
         .word 0   ;                  706
         .word 0   ;                  710
         .word 0   ;                  712
         .word 0   ;                  714
         .word 0   ;                  716
         .word 0   ;                  720
         .word 0   ;                  722
         .word 0   ;                  724
         .word 0   ;                  726
         .word 0   ;                  730
         .word 0   ;                  732
         .word 0   ;                  734
         .word 0   ;                  736
         .word 0   ;                  740
         .word 0   ;                  742
         .word 0   ;                  744
         .word 0   ;                  746
         .word 0   ;                  750
         .word 0   ;                  752
         .word 0   ;                  754
         .word 0   ;                  756
         .word 0   ;                  760
         .word 0   ;                  762
         .word 0   ;                  764
         .word 0   ;                  766
         .word 0   ;                  770
         .word 0   ;                  772
         .word 0   ;                  774
stbot:
stk:
         .word 0   ;                  776
;
; misc definitions
;
ht       = 11
lf       = 12
cr       = 15
crlf     = 200
ps       = 177776
stklmt   = 177774
pirq     = 177772
dswr     = 177570
ddisp    = 177570
cpereg   = 177766
;
; general purpose register definitions
;
r0       = %0
r1       = %1
r2       = %2
r3       = %3
r4       = %4
r5       = %5
r6       = %6
r7       = %7
sp       = %6
pc       = %7
;
; priority level definitions
;
pr0      = 0
pr1      = 40
pr2      = 100
pr3      = 140
pr4      = 200
pr5      = 240
pr6      = 300
pr7      = 340
;
; kt11 register addresses
;
sr0      = 177572
sr1      = 177574
sr2      = 177576
sr3      = 172516
;
uipdr0   = 177600
uipdr1   = 177602
uipdr2   = 177604
uipdr3   = 177606
uipdr4   = 177610
uipdr5   = 177612
uipdr6   = 177614
uipdr7   = 177616
;
udpdr0   = 177620
udpdr1   = 177622
udpdr2   = 177624
udpdr3   = 177626
udpdr4   = 177630
udpdr5   = 177632
udpdr6   = 177634
udpdr7   = 177636
;
uipar0   = 177640
uipar1   = 177642
uipar2   = 177644
uipar3   = 177646
uipar4   = 177650
uipar5   = 177652
uipar6   = 177654
uipar7   = 177656
;
udpar0   = 177660
udpar1   = 177662
udpar2   = 177664
udpar3   = 177666
udpar4   = 177670
udpar5   = 177672
udpar6   = 177674
udpar7   = 177676
;
kipdr0   = 172300
kipdr1   = 172302
kipdr2   = 172304
kipdr3   = 172306
kipdr4   = 172310
kipdr5   = 172312
kipdr6   = 172314
kipdr7   = 172316
;
kipar0   = 172340
kipar1   = 172342
kipar2   = 172344
kipar3   = 172346
kipar4   = 172350
kipar5   = 172352
kipar6   = 172354
kipar7   = 172356
;
sipdr0   = 172200
sipdr1   = 172202
sipdr2   = 172204
sipdr3   = 172206
sipdr4   = 172210
sipdr5   = 172212
sipdr6   = 172214
sipdr7   = 172216
;
sipar0   = 172240
sipar1   = 172242
sipar2   = 172244
sipar3   = 172246
sipar4   = 172250
sipar5   = 172252
sipar6   = 172254
sipar7   = 172256
;
; error macro - provide unique error number
;
..n      = 0
         .macro error
..n      = ..n + 1
         mov #..n,@#ddisp
         halt
         .endm error
;
;
;

;         .=1000
st:
         mov #stk, sp
         jmp tst213
;         mov #0, @#0             ; erase the jump at loc 0, so we know if we ended there
         inc @#count
         mov @#count,@#177570    ; keep count of how many loops we've done, and copy this into the display register

;
; tst1
;
tst1:
         scc
         clz
         beq 1$
         bne 2$

1$:
         error
2$:      ccc
         sez
         bne 3$
         beq 4$
3$:
         error
4$:
;
; tst2
;
tst2:
         ccc
         bcc 2$
1$:
         error
2$:      sec
         bcs 4$
3$:
         error
4$:
;
; tst3
;
tst3:
         clr r0
         bne 1$
         clr (r0)
         bne 1$
         tst @#0
         beq 2$
1$:
         error
2$:
;
; tst4
;
tst4:
         mov #125252,@#0
         cmp #125252,@#0
         beq 2$
1$:
         error
2$:
;
; tst5
;
tst5:
         mov #052525,@#0
         cmp @#0,#052525
         beq 2$
1$:
         error
2$:
;
; tst6
;
tst6:
         clr @#0
         com @#0
         cmp @#0,#177777
         beq 2$
1$:
         error
2$:
;
; tst7
;
tst7:
         mov #177777,r0
         cmp r0,#177777
         beq 1$
         error
1$:
         clr r0
         cmp r0,#0
         beq 2$
         error
2$:
         mov #125252,r0
         cmp r0,#125252
         beq 3$
         error
3$:
         mov #52525,r0
         cmp r0,#52525
         beq 4$
         error
4$:
;
; tst10
;
tst10:
         mov #177777,r1
         cmp r1,#177777
         beq 1$
         error
1$:
         clr r1
         cmp r1,#0
         beq 2$
         error
2$:
         mov #125252,r1
         cmp r1,#125252
         beq 3$
         error
3$:
         mov #52525,r1
         cmp r1,#52525
         beq 4$
         error
4$:
;
; tst11
;
tst11:
         mov #177777,r2
         cmp r2,#177777
         beq 1$
         error
1$:
         clr r2
         cmp r2,#0
         beq 2$
         error
2$:
         mov #125252,r2
         cmp r2,#125252
         beq 3$
         error
3$:
         mov #52525,r2
         cmp r2,#52525
         beq 4$
         error
4$:
;
; tst12
;
tst12:
         mov #177777,r3
         cmp r3,#177777
         beq 1$
         error
1$:
         clr r3
         cmp r3,#0
         beq 2$
         error
2$:
         mov #125252,r3
         cmp r3,#125252
         beq 3$
         error
3$:
         mov #52525,r3
         cmp r3,#52525
         beq 4$
         error
4$:
;
; tst13
;
tst13:
         mov #177777,r4
         cmp r4,#177777
         beq 1$
         error
1$:
         clr r4
         cmp r4,#0
         beq 2$
         error
2$:
         mov #125252,r4
         cmp r4,#125252
         beq 3$
         error
3$:
         mov #52525,r4
         cmp r4,#52525
         beq 4$
         error
4$:
;
; tst14
;
tst14:
         mov #177777,r5
         cmp r5,#177777
         beq 1$
         error
1$:
         clr r5
         cmp r5,#0
         beq 2$
         error
2$:
         mov #125252,r5
         cmp r5,#125252
         beq 3$
         error
3$:
         mov #52525,r5
         cmp r5,#52525
         beq 4$
         error
4$:
;
; tst15
;
tst15:
         mov #177777,r6
         cmp r6,#177777
         beq 1$
         error
1$:
         clr r6
         cmp r6,#0
         beq 2$
         error
2$:
         mov #125252,r6
         cmp r6,#125252
         beq 3$
         error
3$:
         mov #52525,r6
         cmp r6,#52525
         beq 4$
         error
4$:
;
; tst16
;
tst16:
         mov #377,@#177776
         cmp #357,@#177776
         beq 1$
         error
1$:
         clr @#177776
         cmp #0,@#177776
         beq 2$
         error
2$:
         mov #105,@#177776
         cmp #105,@#177776
         beq 3$
         error
3$:
         mov #252,@#177776
         cmp #252,@#177776
         beq 4$
         error
4$:
;
; tst17
;
tst17:
         clr r4
         com r4
         clr r4
         beq 2$
1$:
         error
2$:
         com r4
         inc r4
         beq 4$
3$:
         error
4$:
;
;
;
tst20:
         clr r4
         com r4
         clrb r4
         beq 2$
1$:
         error
2$:
         decb r4
         bpl 3$
         comb r4
         beq 4$
3$:
         error
4$:
;
;
;
tst21:
         clr r4
         clr (r4)
         com (r4)
         clr (r4)
         beq 2$
1$:
         error
2$:
         com (r4)
         beq 3$
         bpl 3$
         inc (r4)
         beq 4$
3$:
         error
4$:
;
;
;
tst22:
         clr r4
         clr (r4)
         com (r4)
         clrb (r4)
         clrb (r4)
         beq 2$
1$:
         error
2$:
         incb (r4)
         bmi 3$
         beq 3$
         comb (r4)
         incb (r4)
         incb (r4)
         beq 4$
3$:
         error
4$:
;
;
;
tst23:
         clr r4
         clr (r4)
         com (r4)
         inc r4
         clrb (r4)
         beq 1$
         error
1$:
         dec r4
         inc (r4)
         inc r4
         comb (r4)
         incb (r4)
         bpl 2$
         beq 2$
         incb (r4)
         beq 3$
2$:
         error
3$:
;
;
;
tst24:
         clr r4
         comb r4
         inc r4
         clr (r4)
         com (r4)
         clr (r4)+
         beq 1$
         error
1$:
         dec r4
         dec r4
         com (r4)+
         bpl 2$
         dec r4
         dec r4
         inc (r4)+
         beq 3$
2$:
         error
3$:
;
;
;
tst25:
         clr r4
         comb r4
         inc r4
         clr (r4)
         com (r4)
         clrb (r4)+
         beq 1$
         error
1$:
         dec r4
         decb (r4)+
         bpl 2$
         dec r4
         comb (r4)+
         beq 3$
2$:
         error
3$:
;
;
;
tst26:
         clr r4
         comb r4
         inc r4
         clr (r4)
         com (r4)
         inc (r4)
         clrb (r4)+
         beq 1$
         error
1$:
         dec r4
         dec r4
         incb (r4)+
         comb (r4)+
         bpl 2$
         dec r4
         incb (r4)+
         beq 3$
2$:
         error
3$:
;
;
;
tst27:
         clr r4
         clr (r4)
         comb (r4)
         inc (r4)
         clr @(r4)+
         beq 1$
         error
1$:
         dec r4
         dec r4
         com @(r4)+
         bpl 2$
         dec r4
         dec r4
         inc @(r4)+
         beq 3$
2$:
         error
3$:
;
;
;
tst30:
         clr r4
         clr r1
         comb r1
         inc r1
         clr (r1)
         com (r1)+
         clr (r1)
         comb (r1)
         clr (r4)
         comb (r4)
         inc (r4)
         clrb @(r4)+
         beq 1$
         error
1$:
         dec r4
         dec r4
         comb @(r4)+
         dec r4
         dec r4
         incb @(r4)+
         beq 3$
2$:
         error
3$:
         dec r4
         dec r4
         inc (r4)
         incb @(r4)+
         bne 4$
         dec r4
         dec r4
         clrb @(r4)+
         beq 5$
4$:
         error
5$:
         dec r4
         dec r4
         comb @(r4)+
         dec r4
         dec r4
         incb @(r4)+
         beq 7$
6$:
         error
7$:
;
;
;
tst31:
         clr r4
         comb r4
         inc r4
         clr (r4)
         com (r4)+
         clr (r4)
         inc (r4)+
         clr -(r4)
         beq 1$
         error
1$:
         dec -(r4)
         com (r4)
         beq 2$
         bmi 2$
         inc r4
         inc r4
         dec -(r4)
         beq 3$
2$:
         error
3$:
;
;
;
tst32:
         clr r4
         comb r4
         inc r4
         clr -(r4)
         comb (r4)
         inc (r4)+
         clr (r4)
         com (r4)+
         inc r4
         clrb -(r4)
         beq 2$
1$:
         error
2$:
         inc r4
         inc r4
         comb -(r4)
         dec r4
         dec r4
         incb -(r4)
         beq 4$
3$:
         error
4$:
         decb -(r4)
         beq 6$
5$:
         error
6$:
;
;
;
tst33:
         clr r4
         clr (r4)
         comb (r4)
         inc (r4)+
         clr @-(r4)
         beq 1$
         error
1$:
         inc r4
         inc r4
         com @-(r4)
         beq 2$
         inc r4
         inc r4
         dec @-(r4)
         beq 2$
         inc (r4)+
         incb @-(r4)
         beq 3$
2$:
         error
3$:
;
;
;
tst34:
         clr r4
         comb r4
         inc r4
         clr r1
         comb r1
         dec r1
         clr r2
         clr (r2)
         clr (r4)
         com (r4)
         clr (r1)
         neg @-(r4)
         beq 2$
1$:
         error
2$:
         dec @(r4)+
         neg @-(r4)
         beq 3$
         bvs 3$
         bmi 3$
         bcs 4$
3$:
         error
4$:
         dec @(r4)+
         beq 6$:
5$:
         error
6$:
         incb (r2)
         neg @-(r4)
         beq 7$
         bvs 7$
         bcc 7$
         bmi 8$
7$:
         error
8$:
         incb (r2)
         beq 10$
9$:
         error
10$:
;
;
;
tst35:
         clr r4
         inc r4
         inc r4
         clr r1
         comb r1
         inc r1
         clr (r1)
         com (r1)+
         clr (r1)
         inc (r1)
         clr r2
         clr (r2)
         clr 376(r4)
         beq 2$
1$:
         error
2$:
         dec 376(r4)
         com 400(r4)
         beq 3$
         inc 400(r4)
         inc 400(r4)
         beq 4$
3$:
         error
4$:
         inc -2(r1)
         beq 6$
5$:
         error
6$:
;
;
;
tst36:
         clr r1
         clr r4
         comb r4
         inc r4
         clr (r4)
         com (r4)
         clr -(r4)
         clr -(r4)
         inc (r4)+
         neg 2(r4)
         beq 1$
         bvs 1$
         bmi 1$
         bcs 2$
1$:
         error
2$:
         dec 2(r4)
         beq 4$
3$:
         error
4$:
         neg 0(r4)
         beq 5$
         error
5$:
         negb 374(r1)
         bvs 6$
         beq 6$
         bpl 6$
         bcs 7$
6$:
         error
7$:
         incb 374(r1)
         beq 9$
8$:
         error
9$:
;
;
;
tst37:
         clr r1
         clr r4
         comb r4
         inc r4
         clr (r1)
         comb (r1)
         inc (r1)
         inc (r1)
         inc (r1)
         clr (r4)
         clr 2(r4)
         com 2(r4)
         clr @-400(r4)
         beq 2$
1$:
         error
2$:
         com @0(r1)
         bmi 4$
3$:
         error
4$:
         com r4
         inc @401(r4)
         beq 6$
5$:
         error
6$:
;
;
;
tst40:
         clr r4
         clr (r4)
         clr r2
         comb r2
         inc r2
         clr (r2)
         neg @-400(r2)
         bcs 1$
         beq 2$
1$:
         error
2$:
         dec (r4)
         neg @+400(r4)
         beq 3$
         bvs 3$
         bmi 3$
         bcs 4$
3$:
         error
4$:
;
;
;
tst41:
         clr r4
         comb r4
         inc r4
         clr (r7)+
1$:
         .word -1
         beq 3$
2$:
         error
3$:
;
;
;
tst42:
         clr r4
         scc
         clz
         tst r4
         bcs 1$
         bvs 1$
         bmi 1$
         beq 2$
1$:
         error
2$:
         dec r4
         scc
         cln
         tst r4
         bcs 3$
         bvs 3$
         beq 3$
         bmi 4$
3$:
         error
4$:
;
;
;
tst43:
         clr r4
         comb r4
         scc
         cln
         tstb r4
         bvs 1$
         bcs 1$
         bvs 1$   ; ??
         bmi 2$
1$:
         error
2$:
         inc r4
         tstb r4
         beq 4$
3$:
         error
4$:
;
;
;
tst44:
         clr r4
         clr (r4)
         scc
         clz
         tst (r4)
         bcs 1$
         bvs 1$
         bmi 1$
         beq 2$
1$:
         error
2$:
         inc (r4)
         scc
         tst (r4)
         beq 3$
         bvs 3$
         bcs 3$
         bpl 4$
3$:
         error
4$:
;
;
;
tst45:
         clr r4
         clr (r4)
         comb (r4)
         inc (r4)
         scc
         clz
         tstb (r4)
         bcs 1$
         bvs 1$
         bmi 1$
         beq 2$
1$:
         error
2$:
         inc r4
         scc
         tstb (r4)
         beq 3$
         bmi 3$
         bvs 3$
         bcc 4$
3$:
         error
4$:
;
;
;
tst46:
         clr r4
         clr (r4)+
         clr (r4)
         com (r4)
         clr r4
         scc
         clz
         tst (r4)+
         bcs 1$
         bvs 1$
         bmi 1$
         beq 2$
1$:
         error
2$:
         tst (r4)+
         bcs 3$
         bvs 3$
         beq 3$
         bmi 4$
3$:
         error
4$:
;
;
;
tst47:
         clr r4
         clr (r4)+
         comb -(r4)
         dec r4
         scc
         clz
         tstb(r4)+
         bvs 1$
         bcs 1$
         bmi 1$
         beq 2$
1$:
         error
2$:
         scc
         cln
         tstb (r4)+
         beq 3$
         bcs 3$
         bvs 3$
         bmi 4$
3$:
         error
4$:
;
;
;
tst50:
         clr r4
         clr (r4)
         comb (r4)
         inc (r4)
         clr @(r4)+
         clr r4
         scc
         clz
         tst @(r4)+
         bcs 1$
         bvs 1$
         bmi 1$
         beq 2$
1$:
         error
2$:
         dec r4
         dec r4
         dec @(r4)+
         clr r4
         scc
         cln
         tst @(r4)+
         bcs 3$
         beq 3$
         bvs 3$
         bmi 4$
3$:
         error
4$:
;
;
;
tst51:
         clr r4
         clr (r4)
         comb (r4)
         inc (r4)
         clr r1
         comb r1
         inc r1
         clr (r1)
         scc
         tst @(r4)+
         bcs 1$
         bvs 1$
         bmi 1$
         beq 2$
1$:
         error
2$:
         dec r4
         dec r4
         tst r4
         beq 4$
3$:
         error
4$:
;
;
;
tst52:
         clr r4
         clr (r4)
         comb (r4)
         inc (r4)
         inc (r4)
         clr r1
         comb r1
         inc r1
         clr (r1)
         com (r1)
         clrb (r1)
         tstb @(r4)+
         beq 1$
         bcs 1$
         bvs 1$
         bmi 2$
1$:
         error
2$:
         dec r4
         dec r4
         beq 4$
3$:
         error
4$:
;
;
;
tst53:
         clr r4
         clr (r4)
         inc r4
         inc r4
         scc
         clz
         tst -(r4)
         bcs 1$
         bvs 1$
         bmi 1$
         beq 2$
1$:
         error
2$:
         tst r4
         beq 4$
3$:
         error
4$:
;
;
;
tst54:
         clr r4
         clr (r4)
         com (r4)
         comb (r4)
         scc
         inc r4
         inc r4
         tstb -(r4)
         beq 1$
         bcs 1$
         bvs 1$
         bmi 2$
1$:
         error
2$:
         tstb -(r4)
         beq 4$
3$:
         error
4$:
;
;
;
tst55:
         clr r4
         clr (r4)+
         scc
         clz
         tst @-(r4)
         bcs 1$
         bvs 1$
         bmi 1$
         beq 2$
1$:
         error
2$:
         tst r4
         beq 4$
3$:
         error
4$:
;
;
;
tst56:
         clr r4
         clr (r4)
         comb (r4)
         inc (r4)
         clr @(r4)+
         com @-(r4)
         comb @(r4)+
         tstb @-(r4)
         bcs 1$
         bmi 1$
         bvs 1$
         beq 2$
1$:
         error
2$:
         inc (r4)+
         tstb @-(r4)
         bmi 4$
3$:
         error
4$:
;
;
;
tst57:
         clr r4
         clr (r4)
         comb r4
         inc r4
         clr (r4)
         com (r4)
         tst -400(r4)
         bcs 1$
         bvs 1$
         bmi 1$
         beq 2$
1$:
         error
2$:
         clr r4
         tst 400(r4)
         beq 3$
         bmi 4$
3$:
         error
4$:
;
;
;
tst60:
         clr r4
         clr (r4)
         com (r4)+
         clr (r4)
         clr r2
         clr r4
         comb r4
         inc r4
         clr (r4)
         tst @-376(r4)
         bcs 1$
         bvs 1$
         beq 1$
         bmi 2$
1$:
         error
2$:
         inc (r2)+
         tst @-376(r4)
         bmi 3$
         beq 4$
3$:
         error
4$:
;
;
;
tst61:
         clr r4
         clr r1
         com r1
         mov r1,r4
         beq 1$
         bvs 1$
         bmi 2$
1$:
         error
2$:
         inc r4
         bne 1$
;
;
;
tst62:
         clr r4
         clr r1
         com r1
         add r1,r4
         beq 1$
         bcs 1$
         bvs 1$
         bmi 2$
1$:
         error
2$:
         inc r4
         beq 4$
3$:
         error
4$:
;
;
;
tst63:
         clr r4
         clr r1
         inc r1
         sub r1,r4
         bvs 1$
         bcc 1$
         beq 1$
         bmi 2$
1$:
         error
2$:
         com r1
         inc r1
         sub r1,r4
         beq 4$
3$:
         error
4$:
;
;
;
tst64:
         ccc
         mov #125252,r4
         beq 1$
         bmi 2$
1$:
         error
2$:
         mov #052525,r1
         bmi 3$
         bne 4$
3$:
         error
4$:
         add r1,r4
         bmi 6$
5$:
         error
6$:
         inc r4
         bne 5$
;
;
;
tst65:
         clr r4
         com r4
         mov #125252,r1
         mov #052525,r2
         sec
         bic r1,r4
         bcc 1$
         bvs 1$
         beq 1$
         bpl 2$
1$:
         error
2$:
         cmp r4,r2
         beq 4$
3$:
         error
4$:
         dec r1
         bis r2,r1
         bmi 6$
5$:
         error
6$:
         inc r1
         inc r1
         inc r1
         bne 5$
;
;
;
tst66:
         mov #125252,r1
         mov #100000,r4
         mov #052525,r2
         bit r4,r1
         beq 1$
         bmi 2$
1$:
         error
2$:
         cmp r4,r1
         beq 3$
         bcc 3$
         bmi 4$
3$:
         error
4$:
         cmp r1,r4
         beq 5$
         bcs 5$
         bvs 5$
         bpl 6$
5$:
         error
6$:
         clr r4
         inc r4
         scc
         bit r4,r1
         beq 8$
7$:
         error
8$:
;
;
;
tst67:
         mov #400,r4
         mov #402,r1
         clr (r4)
         com (r4)
         clr (r1)
         comb (r1)
         clr r2
         mov #405,r3
         scc
         mov (r4),(r2)
         beq 1$
         bvs 1$
         bcc 1$
         bmi 2$
1$:
         error
2$:
         inc (r2)
         bne 3$
         ccc
         movb (r1),(r3)
         beq 3$
         bmi 4$
3$:
         error
4$:
         incb (r3)
         bne 3$
         clr r2
         movb (r1),r2
         bpl 5$
         bvs 5$
         bcs 5$
         cmp #177777,r2
         beq 6$
5$:
         error
6$:
;
;
;
tst70:
         mov #400,r4
         mov #402,r1
         mov #-25,(r4)
         mov #24,(r1)
         add (r1),(r4)
         beq 1$
         bcs 1$
         bpl 1$
         inc (r4)
         beq 2$
1$:
         error
2$:
;
;
;
tst71:
         mov #400,r4
         mov #404,r1
         mov #3,(r4)
         mov #6,(r1)
         scc
         sub (r4),(r1)
         beq 1$
         bmi 1$
         bcc 2$
1$:
         error
2$:
         sub (r4),(r1)
         bne 1$
;
;
;
tst72:
         mov #400,r4
         mov #402,r1
         mov #052525,(r4)
         mov #125252,(r1)
         bis (r4),(r1)
         beq 1$
         bmi 2$
1$:
         error
2$:
         inc (r1)
         beq 4$
3$:
         error
4$:
         dec (r1)
         bic (r4),(r1)
         beq 5$
         bmi 6$
5$:
         error
6$:
         com (r1)
         bic (r1),(r4)
         beq 8$
7$:
         error
8$:
;
;
;
tst73:
         mov #400,r4
         mov #052525,(r4)
         mov #402,r1
         mov #125252,(r1)
         clc
         bit (r4),(r1)
         bcs 1$
         beq 2$
1$:
         error
2$:
         cmp (r4),(r1)
         beq 3$
         bcc 3$
         bvc 3$
         bmi 4$
3$:
         error
4$:
         clr (r4)
         inc (r4)
         bit (r1),(r4)
         beq 6$
5$:
         error
6$:
;
;
;
tst74:
         mov #400,r4
         mov #402,r1
         mov #5,(r4)
         clr (r1)+
         clr (r1)
         com (r1)
         tst -(r1)
         scc
         mov (r1)+,(r4)+
         bmi 1$
         bcc 1$
         bvs 1$
         beq 2$
1$:
         error
2$:
         inc -(r4)
         add (r4),(r1)
         beq 4$
3$:
         error
4$:
;
;
;
tst75:
         mov #400,r4
         mov #402,r1
         mov #177760,(r4)
         mov #177750,(r1)
         sub (r4)+,(r1)+
         beq 1$
         bvs 1$
         bcc 1$
         bmi 2$
1$:
         error
2$:
         inc -(r1)
         sub #177771,(r1)+
         bmi 3$
         beq 4$
3$:
         error
4$:
;
;
;
tst76:
         mov #400,r4
         mov #402,r1
         mov #404,r2
         mov #141401,(r4)
         mov #177405,(r1)
         mov #70,(r2)+
         mov #-1,(r2)+
         bic (r4)+,(r1)+
         beq 1$
         bpl 2$
1$:
         error
2$:
         bis (r4)+,(r1)+
         bicb (r4)+,(r1)+
         dec r1
         bisb (r4)+,(r1)+
         bmi 4$
3$:
         error
4$:
         inc (r4)
         beq 6$
5$:
         error
6$:
;
;
;
tst77:
         mov #400,r4
         mov #402,r1
         mov #125252,(r4)
         mov #100001,(r1)+
         mov #100002,(r1)
         tst -(r1)
         bitb (r4)+,(r1)+
         bmi 1$
         beq 2$
1$:
         error
2$:
         bitb (r1)+,(r4)+
         beq 3$
         bmi 4$
3$:
         error
4$:
         cmp (r4)+,(r1)+
         beq 5$
         bcc 5$
         bmi 6$
5$:
         error
6$:
         dec -(r1)
         tst -(r1)
         cmp (r1)+,(r4)+
         beq 8$
7$:
         error
8$:
;
;
;
tst100:
         clr r4
         mov #2,r1
         mov #400,r2
         mov #400,(r4)
         mov #402,(r1)
         mov #200,(r2)+
         mov #54320,(r2)
         sub @(r4),@(r1)+
         beq 1$
         bcs 1$
         bpl 2$
1$:
         error
2$:
         cmp #54120,(r2)
         beq 4$
3$:
         error
4$:
;         clr 0 ; ??
;         clr 2 ; ??
;
;
;
tst101:
         mov #400,r4
         mov #402,r1
         mov #125366,(r1)+
         mov #173001,(r4)+
         cmp -(r4),-(r1)
         bcs 1$
         bpl 2$
1$:
         error
2$:
         inc r4
         inc r1
         sec
         bitb -(r1),-(r4)
         bcc 3$
         beq 4$
3$:
         error
4$:
         tst (r4)+
         inc r1
         cmpb -(r4),-(r1)
         beq 6$
5$:
         error
6$:
;
;
;
tst102:
         mov #400,r4
         mov #1,(r4)+
         mov #-2,(r4)+
         mov #400,(r4)+
         mov #402,(r4)
         mov #410,r1
         add @-(r4),@-(r1)
         beq 1$
         bpl 1$
         bcc 2$
1$:
         error
2$:
         add #4,r4
         add @-(r1),@-(r4)
         beq 4$
3$:
         error
4$:
;
;
;
tst103:
         clr r4
         mov #400,r1
         mov #125252,(r1)+
         mov #1,(r1)+
         mov #100000,(r1)+
         bit 400(r4),-4(r1)
         beq 2$
1$:
         error
2$:
         bitb 405(r4),-6(r1)
         beq 3$
         bmi 4$
3$:
         error
4$:
;
;
;
tst104:
         mov #400,r4
         clr r1
         mov #-2,(r4)+
         mov #-1,(r4)+
         mov #400,(r4)+
         mov #402,(r1)
         inc r1
         sub @-406(r4),@403(r1)
         beq 1$
         bmi 2$
1$:
         error
2$:
         sub @-1(r1),@-2(r4)
         beq 4$
3$:
         error
4$:
;         clr 0 ; ??
;         clr 2 ; ??
;
;
;
tst105:
         mov #125252,r4
         scc
         rol r4
         bvc 1$
         bcc 1$
         cmp #052525,r4
         beq 2$
1$:
         error
2$:
         mov #125252,r4
         ccc
         rolb r4
         bcc 3$
         bvc 3$
         bmi 3$
         cmp #125124,r4
         beq 4$
3$:
         error
4$:
;
;
;
tst106:
         clr r4
         mov #52525,(r4)
         rol (r4)
         bpl 1$
         bvc 1$
         bcs 1$
         cmp (r4),#125252
         beq 2$
1$:
         error
2$:
         mov #125252,(r4)
         inc r4
         scc
         rolb (r4)
         bmi 3$
         bcc 3$
         bvc 3$
         dec r4
         cmp #52652,(r4)
         beq 4$
3$:
         error
4$:
;
;
;
tst107:
         clr r4
         mov #100000,(r4)
         ccc
         rol (r4)+
         bcc 1$
         bvc 1$
         beq 2$
1$:
         error
2$:
         dec r4
         dec r4
         bne 3$
         mov #4040,(r4)
         clc
         rolb (r4)+
         bcs 3$
         bvs 3$
         dec r4
         cmp #04100,(r4)
         beq 4$
3$:
         error
4$:
;
;
;
tst110:
         clr r4
         mov #052525,(r4)
         scc
         rol @#0
         bpl 1$
         bvc 1$
         bcs 1$
         cmp #125253,(r4)
         beq 2$
1$:
         error
2$:
         mov #125252,(r4)
         sec
         rolb @#0
         bmi 3$
         bcc 3$
         bvs 4$
3$:
         error
4$:
;
;
;
tst111:
         clr r1
         mov #2,r4
         mov #54321,(r1)
         scc
         rol -(r4)
         bpl 1$
         bvc 1$
         bcs 1$
         cmp #130643,(r1)
         bne 1$
         tst r4
         beq 2$
1$:
         error
2$:
;
;
;
tst112:
         clr r4
         mov #400,(r4)
         mov #123456,@(r4)+
         scc
         rol @-(r4)
         bmi 1$
         bcc 1$
         bvc 1$
         tst r4
         bne 1$
         cmp #47135,@#400
         beq 2$
1$:
         error
2$:
;
;
;
tst113:
         mov #400,r4
         clr r1
         mov #32525,(r1)
         scc
         rol -400(r4)
         bmi 1$
         bcs 1$
         bvs 1$
         cmp #65253,(r1)
         beq 2$
1$:
         error
2$:
;
;
;
tst114:
         mov #400,r4
         clr @#402
         mov #100000,@#0
         rol @2(r4)
         bmi 1$
         bne 1$
         bcc 1$
         bvc 1$
         tst @#0
         beq 2$
1$:
         error
2$:
;
;
;
tst115:
         mov #400,r4
         mov #40700,(r4)
         swab @#400
         bmi 1$
         cmp #140101,(r4)
         bne 1$
         swab @#400
         bmi 2$
1$:
         error
2$:
;
;
;
tst116:
         mov #52525,r4
         ccc
         ror r4
         bcc 1$
         cmp #25252,r4
         beq 2$
1$:
         error
2$:
;
;
;
tst117:
         clr r4
         mov #1,(r4)
         scc
         rorb (r4)
         bcc 1$
         bpl 1$
         cmp #200,(r4)
         beq 2$
1$:
         error
2$:
;
;
;
tst120:
         mov #1,@#seq
         mov #mju1,r1
         jmp (r1)
mju2:
         cmp @#seq,#2
         beq mju2a
1$:
         error
mju2a:
         cmp r1,#mju2+2
         beq mju2b
2$:
         error
mju2b:
         inc @#seq
         mov #mj2,r1
         jmp @(r1)+
mj2:
         .word mju3
mju1:
         cmp @#seq,#1
         beq mju1a
3$:
         error
mju1a:
         inc @#seq
         mov #mju2,r1
         jmp (r1)+
mju3:
         cmp @#seq,#3
         beq mju3a
4$:
         error
mju3a:
         cmp #mj2+2,r1
         beq mju3b
5$:
         error
mju3b:
         inc @#seq
         mov #mju4+2,r1
         jmp -(r1)
mju5:
         halt               ; ??
         cmp #mj5,r1
         beq mju5a
6$:
         error
mju5a:
         cmp @#seq,#5
         beq mju5b
7$:
         error
mju5b:
         inc @#seq
         mov #mju6-5,r1
         jmp +5(r1)
mju4:
         nop
         cmp #mju4,r1
         beq mju4a
8$:
         error
mju4a:
         cmp @#seq,#4
         beq mju4b
9$:
         error
mju4b:
         inc @#seq
         mov #mj5+2,r1
         jmp @-(r1)
mj5:
         .word mju5+2
mju6:
         cmp #6,@#seq
         beq mju6a
10$:
         error
mju6a:
         inc @#seq
         mov #mj7+10,r1
         jmp @-10(r1)
mj7:
         .word mju7
         halt
mju7:
         cmp #7,@#seq
         beq mju7e
11$:
         error
mju7e:
;
;
;
tst121:
         mov #128$,r1

         mov (pc)+,(pc)
         .word nop
64$:     .word 111
         mov (pc)+,(pc)
         .word nop
65$:     .word 111
         mov (pc)+,(pc)
         .word nop
66$:     .word 111
         mov (pc)+,(pc)
         .word nop
67$:     .word 111
         mov (pc)+,(pc)
         .word nop
68$:     .word 111
         mov (pc)+,(pc)
         .word nop
69$:     .word 111
         mov (pc)+,(pc)
         .word nop
70$:     .word 111
         mov (pc)+,(pc)
         .word nop
71$:     .word 111
         mov (pc)+,(pc)
         .word nop
72$:     .word 111
         mov (pc)+,(pc)
         .word nop
73$:     .word 111
         mov (pc)+,(pc)
         .word nop
74$:     .word 111
         mov (pc)+,(pc)
         .word nop
75$:     .word 111
         mov (pc)+,(pc)
         .word nop
76$:     .word 111
         mov (pc)+,(pc)
         .word nop
77$:     .word 111
         mov (pc)+,(pc)
         .word nop
78$:     .word 111
         mov (pc)+,(pc)
         .word nop
79$:     .word 111
         mov (pc)+,(pc)
         .word nop
80$:     .word 111
         mov (pc)+,(pc)
         .word nop
81$:     .word 111
         mov (pc)+,(pc)
         .word nop
82$:     .word 111
         mov (pc)+,(pc)
         .word nop
83$:     .word 111
         mov (pc)+,(pc)
         .word nop
84$:     .word 111
         mov (pc)+,(pc)
         .word nop
85$:     .word 111
         mov (pc)+,(pc)
         .word nop
86$:     .word 111
         mov (pc)+,(pc)
         .word nop
87$:     .word 111
         mov (pc)+,(pc)
         .word nop
88$:     .word 111
         mov (pc)+,(pc)
         .word nop
89$:     .word 111
         mov (pc)+,(pc)
         .word nop
90$:     .word 111
         mov (pc)+,(pc)
         .word nop
91$:     .word 111
         mov (pc)+,(pc)
         .word nop
92$:     .word 111
         mov (pc)+,(pc)
         .word nop
93$:     .word 111
         mov (pc)+,(pc)
         .word nop
94$:     .word 111
         mov (pc)+,(pc)
         .word nop
95$:     .word 111
         jmp @#129$
128$:
         error
129$:
         mov #32.,r2
         mov #64$,r3
130$:
         mov #111,(r3)
         add #6,r3
         sob r2,130$
;
;
;
tst122:
         mov #0,@#seq
         jmp (r7)
;
mjp17:
         tst @#seq
         beq 2$
1$:
         error
2$:
         inc @#seq
         jmp #401
;
         halt
;
mjp27:
         cmp @#seq,#1
         beq mjp27a
1$:
         error
mjp27a:
         inc @#seq
         jmp @#mjp37
mjp67:
         cmp @#seq,#3
         beq mjp67a
2$:
         error
mjp67a:
         inc @#seq
         ccc
         jmp @mjp67b
;
         halt
;
mjp67b:
         .word mjp77
;
mjp77:
         cmp @#seq,#4
         beq mjp77e
3$:
         error
mjp37:
         cmp @#seq,#2
         beq mjp37a
4$:
         error

mjp37a:
         inc @#seq
         jmp mjp67
;
;
mjp77e:
;
;
;
tst123:
         mov #stk, sp
         mov r6,@#sps
         mov r6,@#spsj
         sub #2,@#spsj
         mov #1,@#seq
         mov #mjsr1,r1
         clr r4
         com r4
         jsr r4,(r1)
mjsr2:
         cmp #2,@#seq
         beq mjsr2a
5$:
         error
mjsr2a:
         cmp @#spsj,r6
         bne 6$
         cmp (r6),#125252
         bne 6$
         cmp #mjsr4,r4
         beq mjsr2b
6$:
         error
mjsr2b:
         inc @#seq
         mov @#sps,r6
         mov #mjsra,r1
         clr r4
         jsr r4,@(r1)+
         halt
mjsra:
         .word mjsr3
mjsr1:
         cmp #1,@#seq
         beq mjsr1a
7$:
         error
mjsr1a:
         cmp @#spsj,r6
         bne 8$
         cmp (r6),#-1
         bne 8$
         cmp #mjsr2,r4
         beq mjsr1b
8$:
         error
mjsr1b:
         inc @#seq
         mov @#sps,r6
         mov #125252,r4
         mov #mjsr2,r1
         jsr r4,(r1)+
mjsr4:
         cmp #4,@#seq
         beq mjsr4a
9$:
         error
mjsr4a:
         cmp @#spsj,r6
         bne 10$
         cmp (r6),#052525
         bne 10$
         cmp #mjsr6,r4
         beq mjsr4b
10$:
         error
mjsr4b:
         inc @#seq
         mov @#sps,r6
         mov #377,r4
         mov #mjsrb+2,r1
         jsr r4,@-(r1)
         halt
mjsrb:
         .word mjsr5
mjsr3:
         cmp #3,@#seq
         beq mjsr3a
11$:
         error
mjsr3a:
         cmp @#spsj,r6
         bne 12$
         cmp (r6),#0
         bne 12$
         cmp #mjsra-2,r4
         beq mjsr3b
12$:
         error
mjsr3b:
         inc @#seq
         mov @#sps,r6
         mov #052525,r4
         mov #mjsr4+2,r1
         ccc
         jsr r4,-(r1)
mjsr6:
         cmp #6,@#seq
         beq mjsr6a
13$:
         error
mjsr6a:
         cmp @#spsj,r6
         bne 14$
         cmp (r6),#123456
         bne 14$
         cmp #mjsr7,r4
         beq mjsr6b
14$:
         error
mjsr6b:
         inc @#seq
         mov @#sps,r6
         mov #-5,r4
         mov #mjsrc+10,r1
         jsr r4,@-10(r1)
mjsrc:
         .word mjsr7
mjsr5:
         cmp #5,@#seq
         beq mjsr5a
15$:
         error
mjsr5a:
         cmp @#spsj,r6
         bne 16$
         cmp (r6),#377
         bne 16$
         cmp #mjsrb-2,r4
         beq mjsr5b
16$:
         error
mjsr5b:
         inc @#seq
         mov @#sps,r6
         mov #123456,r4
         mov #mjsr6+10,r1
         jsr r4,-10(r1)
mjsr7:
         cmp #7,@#seq
         beq mjsr7a
17$:
         error
mjsr7a:
         cmp @#spsj,r6
         bne 18$
         cmp (r6),#-5
         bne 18$
         cmp #mjsr5-2,r4
         beq mjsr7e
18$:
         error
mjsr7e:
         mov @#sps,r6
;
;
;
tst124:
         mov #1,@#seq
         mov r6,@#sps
         mov r6,@#spsj
         sub #2,@#spsj
         mov #-1,r4
         jsr r4,#240
mjr27:
         cmp #1,@#seq
         bne 1$
         cmp @#spsj,r6
         bne 1$
         cmp (r6),#-1
         bne 1$
         cmp r4,#mjr27
         beq mjr27a
1$:
         error
mjr27a:
         inc @#seq
         mov #152525,r4
         mov @#sps,r6
         jsr r4,@#mjr37
mjr27b:
         halt
mjr67:
         cmp @#seq,#3
         bne 2$
         cmp @#spsj,r6
         bne 2$
         cmp (r6),#125
         bne 2$
         cmp r4,#mjr77
         beq mjr67a
2$:
         error
mjr67a:
         inc @#seq
         mov @#sps,r6
         mov #1,r4
         jsr r4,@mjr6b
mjr6a:
         halt
mjr6b:
         .word mjr77
mjr37:
         cmp @#seq,#2
         bne 2$
         cmp @#spsj,r6
         bne 2$
         cmp (r6),#152525
         bne 2$
         cmp r4,#mjr27b
         beq mjr37a
2$:
         error
mjr37a:
         inc @#seq
         mov @#sps,r6
         mov #125,r4
         jsr r4,mjr67
mjr77:
         cmp @#seq,#4
         bne 2$
         cmp @#spsj,r6
         bne 2$
         cmp (r6),#1
         bne 2$
         cmp r4,#mjr6a
         beq mjr77a
2$:
         error
mjr77a:
         mov @#sps,r6
;
;
;
tst125:
         mov #stbot,r6
         mov #123456,-(r6)
         mov #rts1,r3
         rts r3
         error
rts1:
         cmp #123456,r3
         beq rts6
         error
rts6:
         mov r6,r1
         mov #1$,r5
         mov r5,r6
         rts r6
         error
1$:
         cmp (r5),r6
         beq rtse
         error
rtse:
         mov r1,r6
;
;
;
tst126:
         mov #40000,@#177776
         mov #177777,r6
         cmp #177777,r6
         beq 1$
         error
1$:
         clr r6
         cmp #0,r6
         beq 2$
         error
2$:
         mov #125252,r6
         cmp #125252,r6
         beq 3$
         error
3$:
         mov #52525,r6
         cmp #52525,r6
         beq 4$
         error
4$:
         mov #700,r6
         mov #140000,@#177776
         mov #177777,r6
         cmp #177777,r6
         beq 5$
         error
5$:
         clr r6
         cmp #0,r6
         beq 6$
         error
6$:
         mov #125252,r6
         cmp #125252,r6
         beq 7$
         error
7$:
         mov #52525,r6
         cmp #52525,r6
         beq 8$
         error
8$:
         mov #600,r6
         clr @#177776
         mov #stbot,r6
         clr @#700
         clr @#600
         clr @#stbot
         jsr pc,check
ret1:
         mov #40000,@#177776
         cmp #700,r6
         beq 1$
         error
1$:
         mov #140000,@#177776
         cmp #600,r6
         beq 2$
         error
2$:
         clr @#177776
         cmp #stbot,r6
         beq 3$
         error
3$:
         jmp mtso
check:
         mov #40000,@#177776
         jsr pc,check1
ret2:
         cmp #0,(sp)
         beq 1$
         error
1$:
         mov #140000,@#177776
         cmp #0,(sp)
         beq 2$
         error
2$:
         clr @#177776
         cmp #ret1,(sp)
         beq 3$
         error
3$:
         rts pc
check1:
         mov #140000,@#177776
         jsr pc,check2
ret3:
         cmp #0,(sp)
         beq 1$
         error
1$:
         clr @#177776
         cmp #ret1,(sp)
         beq 2$
         error
2$:
         mov #40000,@#177776
         cmp #ret2,(sp)
         beq 3$
         error
3$:
         rts pc
check2:
         cmp #ret3,(sp)
         beq 1$
         error
1$:
         mov #40000,@#177776
         cmp #ret2,(sp)
         beq 2$
         error
2$:
         clr @#177776
         cmp #ret1,(sp)
         beq 3$
         error
3$:
         mov #140000,@#177776
         rts pc
mtso:
;
;
;
tst127:
         scc
         clz
         mov #0,r4
         bmi 1$
         bvs 1$
         bcc 1$
         beq 2$
1$:
         error
2$:
         scc
         .word 251
         mov #100000,r4
         beq 3$
         bvs 3$
         bcs 3$
         bmi 4$
3$:
         error
4$:
;
;
;
tst130:
         clr r4
         com r4
         scc
         clz
         bit #0,r4
         bmi 1$
         bvs 1$
         bcc 1$
         beq 2$
1$:
         error
2$:
         scc
         .word 251
         bit #100000,r4
         beq 3$
         bvs 3$
         bcs 3$
         bmi 4$
3$:
         error
4$:
;
;
;
tst131:
         clr r4
         com r4
         scc
         clz
         bic #177777,r4
         bmi 1$
         bvs 1$
         bcc 1$
         beq 2$
1$:
         error
2$:
         com r4
         scc
         .word 251
         bic #77777,r4
         beq 3$
         bvs 3$
         bcs 3$
         bmi 4$
3$:
         error
4$:
;
;
;
tst132:
         clr r4
         scc
         .word 246
         bis #0,r4
         bmi 1$
         bvs 1$
         bcc 1$
         beq 2$
1$:
         error
2$:
         scc
         clc
         bis #100067,r4
         beq 3$
         bvs 3$
         bcs 3$
         bmi 4$
3$:
         error
4$:
;
;
;
tst133:
         mov #77777,r4
         ccc
         sec
         inc r4
         beq 1$
         bpl 1$
         bvc 1$
         bcs 2$
1$:
         error
2$:
         ccc
         inc r4
         bcs 3$
         bvs 3$
         dec r4
         bvs 3$
         bcs 3$
         scc
         .word 252
         dec r4
         beq 3$
         bvc 3$
         bcc 3$
         bpl 4$
3$:
         error
4$:
;
;
;
tst134:
         scc
         clz
         clr r4
         bmi 1$
         bvs 1$
         bcs 1$
         beq 2$
1$:
         error
2$:
         com r4
         scc
         tst r4
         beq 3$
         bvs 3$
         bcs 3$
         bmi 4$
3$:
         error
4$:
         scc
         swab r4
         bvs 5$
         bcs 5$
         bmi 6$
5$:
         error
6$:
;
;
;
tst135:
         mov #77777,r4
         mov #1,r1
         ccc
         add r4,r1
         bvc 1$
         bcs 1$
         beq 1$
         bmi 2$
1$:
         error
2$:
         inc r4
         add r4,r1
         bvc 3$
         bcc 3$
         beq 4$
3$:
         error
4$:
         add r4,r1
         bvs 5$
         bcs 5$
         bmi 6$
5$:
         error
6$:
;
;
;
tst136:
         mov #177777,r4
         scc
         adc r4
         bmi 1$
         bvs 1$
         bcc 1$
         beq 2$
1$:
         error
2$:
         mov #077777,r4
         scc
         clv
         adc r4
         bpl 3$
         bcs 3$
         beq 3$
         bvs 4$
3$:
         error
4$:
         scc
         adc r4
         bvs 5$
         bcs 5$
         bmi 6$
5$:
         error
6$:
;
;
;
tst137:
         mov #077777,r4
         ccc
         neg r4
         bvs 1$
         bcc 1$
         beq 1$
         bmi 2$
1$:
         error
2$:
         clr r4
         ccc
         neg r4
         bmi 3$
         bcs 3$
         bvs 3$
         beq 4$
3$:
         error
4$:
         mov #77777,r4
         mov #170000,r1
         ccc
         cmp r4,r1
         bvc 5$
         bcc 5$
         beq 5$
         bmi 6$
5$:
         error
6$:
         ccc
         com r1
         bmi 7$
         beq 7$
         bcc 7$
         bvc 8$
7$:
         error
8$:
         scc
         com r1
         bmi 10$
9$:
         error
10$:
;
;
;
tst140:
         mov #77775,r4
         ccc
         sub #137757,r4
         bvc 1$
         bpl 1$
         beq 1$
         bcs 2$
1$:
         error
2$:
         mov #5,r4
         ccc
         sub #12,r4
         bcc 3$
         bvs 3$
         beq 3$
         bmi 4$
3$:
         error
4$:
;
;
;
tst141:
         mov #100000,r4
         ccc
         sbc r4
         bpl 1$
         bvs 1$
         sec
         sbc r4
         bvc 1$
         bcs 1$
         bpl 2$
1$:
         error
2$:
         clr r4
         scc
         clc
         sbc r4
         bcs 3$
         bvs 3$
         bne 3$
         sec
         sbc r4
         bcc 3$
         bvs 3$
         beq 3$
         bmi 4$
3$:
         error
4$:
;
;
;
tst142:
         mov #60000,r4
         ccc
         rol r4
         bcs 1$
         bvc 1$
         bmi 2$
1$:
         error
2$:
         rol r4
         bcc 3$
         bvs 3$
         bmi 4$
3$:
         error
4$:
         rol r4
         bvc 5$
         bcc 5$
         bmi 5$
         bne 6$
5$:
         error
6$:
         rol r4
         bvs 7$
         bcs 7$
         bpl 8$
7$:
         error
8$:
;
;
;
tst143:
         mov #3,r4
         ccc
         ror r4
         bcc 1$
         bvc 1$
         bpl 2$
1$:
         error
2$:
         ror r4
         bcc 3$
         bvs 3$
         bmi 4$
3$:
         error
4$:
         ror r4
         bvc 5$
         bcs 5$
         bmi 6$
5$:
         error
6$:
         ror r4
         bvs 7$
         bcs 7$
         bpl 8$
7$:
         error
8$:
;
;
;
tst144:
         mov #52525,r1
         clc
         ror r1
         ror r1
         ror r1
         bcs 1$
         error
1$:
         cmp #45252,r1
         beq 2$
         error
2$:
         mov #125252,r1
         clc
         rol r1
         rol r1
         rol r1
         bcs 3$
         error
3$:
         cmp #052522,r1
         beq 4$
         error
4$:
;
;
;
tst145:
         mov #60000,r4
         ccc
         asl r4
         bcs 1$
         bvc 1$
         bmi 2$
1$:
         error
2$:
         asl r4
         bcc 3$
         bvs 3$
         bmi 4$
3$:
         error
4$:
         asl r4
         bvc 5$
         bcc 5$
         bmi 5$
         beq 6$
5$:
         error
6$:
         asl r4
         bvs 7$
         bcs 7$
         bpl 8$
7$:
         error
8$:
;
;
;
tst146:
         mov #341,r4
         ccc
         asr r4
         bcc 1$
         bvc 1$
         bpl 2$
1$:
         error
2$:
         bis #100001,r4
         asr r4
         bcc 3$
         bvs 3$
         bmi 4$
3$:
         error
4$:
         asr r4
         bvc 5$
         bcs 5$
         bmi 6$
5$:
         error
6$:
         asr r4
         bvc 7$
         bcs 7$
         bpl 7$
         cmp #170016,r4
         beq 8$
7$:
         error
8$:
;
;
;
tst147:
         mov #123456,r4
         mov r4,r1
         ccc
         sxt r4
         bcs 1$
         bmi 1$
         bvs 1$
         beq 2$
1$:
         error
2$:
         mov r1,r4
         scc
         sxt r4
         beq 3$
         bpl 3$
         bcc 3$
         bvs 3$
         com r4
         beq 4$
3$:
         error
4$:
;
;
;
tst150:
         mov #123456,r4
         mov #52525,r1
         ccc
         xor r1,r4
         bvs 1$
         beq 1$
         bcs 1$
         bmi 2$
1$:
         error
2$:
         mov #125252,r1
         scc
         xor r1,r4
         bmi 3$
         beq 3$
         bcc 3$
         bvc 4$
3$:
         error
4$:
         xor r4,r4
         bvs 5$
         bmi 5$
         bcc 5$
         bne 5$
         cmp #0,r4
         beq 6$
5$:
         error
6$:
;
;
;
tst151:
         clr r4
         ccc
         .word 271
         sxt r4
         bvs 1$
         bpl 1$
         beq 1$
         bcc 1$
         inc r4
         beq 2$
1$:
         error
2$:
         scc
         cln
         clr r4
         mov #55,(r4)
         sxt (r4)
         bne 3$
         bvs 3$
         bcs 3$
         bmi 3$
         tst (r4)
         beq 4$
3$:
         error
4$:
         mov #-1,r0
         clr r4
         sxt r0
         tst r0
         beq 5$
         error
5$:
         clr r0
         mov #-1,r0
         sxt r0
         cmp #-1,r0
         beq 6$
         error
6$:
;
;
;
tst152:
         mov #7643,r1
         mov #133333,r4
         scc
         xor r4,r1
         bpl 1$
         beq 1$
         bcc 1$
         bvs 1$
         cmp r1,#134570
         beq 2$
1$:
         error
2$:
         mov r1,r2
         ccc
         xor r4,r2
         bmi 3$
         bvs 3$
         bcs 3$
         cmp r2,#7643
         beq 4$
3$:
         error
4$:
;
;
;
tst153:
         mov #555,r4
         scc
1$:
         bcc 2$
         bvc 2$
         bpl 2$
         bne 2$
         sob r4,1$
         bcc 3$
         bvc 3$
         bpl 3$
         bne 3$
         jmp 4$
3$:
         error
         jmp 4$           ; ??
2$:
         error
4$:
         cmp r4,#0
         beq 5$
         error
5$:
;
;
;
tst154:
         mov #stbot-100,sp
         mov #125252,@#stbot-2
         mov #1$,r5
         mov #mark+37,-(sp)
         scc
         jmp (sp)
         error
1$:
         bhi 2$
         bpl 2$
         bvs 3$
2$:
         error
3$:
         cmp #125252,r5
         beq 4$
         error
4$:
         cmp sp,#stbot
         beq 15$
         error
15$:
         mov #52525,-(sp)
         mov #6400,-(sp)
         mov sp,r5
         jsr pc,5$
6$:
         jmp 16$
5$:
         ccc
         rts r5
         error
16$:
         blos 7$
         bmi 7$
         bvc 8$
7$:
         error
8$:
         cmp r6,#stbot
         beq 9$
         error
9$:
         cmp #52525,r5
         beq 10$
         error
10$:
;
;
;
tst155:
         mov #30017,@#177776
         ccc
         cmp #30000,@#177776
         beq 1$
         error
1$:
;
;
;
tst156:
         mov #30017,@#177776
         clc
         cmp #30016,@#177776
         beq 1$
         error
1$:
;
;
;
tst157:
         mov #30017,@#177776
         cln
         cmp #30007,@#177776
         beq 1$
         error
1$:
;
;
;
tst160:
         mov #30017,@#177776
         clv
         cmp #30015,@#177776
         beq 1$
         error
1$:
;
;
;
tst161:
         mov #30017,@#177776
         clz
         cmp #30013,@#177776
         beq 1$
         error
1$:
;
;
;
tst162:
         mov #30000,@#177776
         scc
         cmp #30017,@#177776
         beq 1$
         error
1$:
;
;
;
tst163:
         mov #30000,@#177776
         sec
         cmp #30001,@#177776
         beq 1$
         error
1$:
;
;
;
tst164:
         mov #30000,@#177776
         sen
         cmp #30010,@#177776
         beq 1$
         error
1$:
;
;
;
tst165:
         mov #30000,@#177776
         sev
         cmp #30002,@#177776
         beq 1$
         error
1$:
;
;
;
tst166:
         mov #30000,@#177776
         sez
         cmp #30004,@#177776
         beq 1$
         error
1$:
;
;
;
tst167:
         mov #30000,@#177776
         scc
         .word 243
         cmp #30014,@#177776
         beq 1$
         error
1$:
         scc
         .word 245
         cmp #30012,@#177776
         beq 2$
         error
2$:
         scc
         .word 246
         cmp #30011,@#177776
         beq 3$
         error
3$:
         scc
         .word 247
         cmp #30010,@#177776
         beq 4$
         error
4$:
         scc
         .word 251
         cmp #30006,@#177776
         beq 5$
         error
5$:
         scc
         .word 252
         cmp #30005,@#177776
         beq 6$
         error
6$:
         scc
         .word 253
         cmp #30004,@#177776
         beq 7$
         error
7$:
         scc
         .word 254
         cmp #30003,@#177776
         beq 8$
         error
8$:
         scc
         .word 255
         cmp #30002,@#177776
         beq 9$
         error
9$:
         scc
         .word 256
         cmp #30001,@#177776
         beq 10$
         error
10$:
;
;
;
tst170:
         mov #30000,@#177776
         .word 263
         cmp #30003,@#177776
         beq 1$
         error
1$:
         ccc
         .word 265
         cmp #30005,@#177776
         beq 2$
         error
2$:
         ccc
         .word 266
         cmp #30006,@#177776
         beq 3$
         error
3$:
         ccc
         .word 267
         cmp #30007,@#177776
         beq 4$
         error
4$:
         ccc
         .word 271
         cmp #30011,@#177776
         beq 5$
         error
5$:
         ccc
         .word 272
         cmp #30012,@#177776
         beq 6$
         error
6$:
         ccc
         .word 273
         cmp #30013,@#177776
         beq 7$
         error
7$:
         ccc
         .word 274
         cmp #30014,@#177776
         beq 8$
         error
8$:
         ccc
         .word 275
         cmp #30015,@#177776
         beq 9$
         error
9$:
         ccc
         .word 276
         cmp #30016,@#177776
         beq 10$
         error
10$:
;
;
;
tst171:
         ccc
         bge 1$
         error
1$:
         bgt 2$
         error
2$:
         ble 3$
         br 4$
3$:
         error
4$:
         blt 5$
         br 6$
5$:
         error
6$:
         sez
         ble 7$
         error
7$:
         bgt 8$
         br 9$
8$:
         error
9$:
         ccc
         sen
         blt 10$
         error
10$:
         ble 11$
         error
11$:
         bge 12$
         br 13$
12$:
         error
13$:
         bgt 14$
         br 15$
14$:
         error
15$:
         ccc
         sev
         ble 16$
         error
16$:
         blt 17$
         error
17$:
         bge 18$
         br 19$
18$:
         error
19$:
         bgt 20$
         br 21$
20$:
         error
21$:
         ccc
         .word 272
         bge 22$
         error
22$:
         bgt 23$
         error
23$:
         ble 24$
         br 25$
24$:
         error
25$:
         blt 26$
         br 27$
26$:
         error
27$:
;
;
;
tst172:
         mov #30000,@#177776
         mov #1,r0
         mov #2,r1
         mov #3,r2
         mov #4,r3
         mov #5,r4
         mov #6,r5
         mov r6,@#sloc00
         mov #30017,@#expdat
         scc
         nop
         nop
         nop
         jsr pc,t114
         cmp r6,@#sloc00
         beq 1$
         error
1$:
         mov #30000,@#expdat
         ccc
         .word 260
         .word 260
         .word 260
         jsr pc,t114
         cmp r6,@#sloc00
         beq 2$
         error
2$:
         jmp finnop
t114:
         cmp @#expdat,@#177776
         beq ta114
;         mov r0,400       ???????
         error
;         mov 400,r0       ???????
ta114:
         cmp #1,r0
         beq tb114
         error
tb114:
         cmp #2,r1
         beq tc114
         error
tc114:
         cmp #3,r2
         beq td114
         error
td114:
         cmp #4,r3
         beq tf114
         error
tf114:
         cmp #5,r4
         beq tg114
         error
tg114:
         cmp #6,r5
         beq th114
         error
th114:
         rts pc
finnop:
;
;
;
tst173:
         clr r0
         clr r1
         clr r2
         clr r3
         clr r4
         clr r5
         mov #4000,@#ps
         bit #4000,@#ps
         bne 1$
         error
1$:
         mov #177777,r0
         mov r0,r1
         mov r1,r2
         mov r2,r3
         mov r3,r4
         mov r4,r5
         bic #4000,@#ps
         bit #4000,@#ps
         beq 2$
         error
2$:
         tst r0
         beq 3$
         error
3$:
         tst r1
         beq 4$
         error
4$:
         tst r2
         beq 5$
         error
5$:
         tst r3
         beq 6$
         error
6$:
         tst r4
         beq 7$
         error
7$:
         tst r5
         beq 8$
         error
8$:
         mov #4000,@#ps
         clr r0
         clr r1
         clr r2
         clr r3
         clr r4
         clr r5
         bic #4000,@#ps
         mov #177777,r0
         mov r0,r1
         mov r1,r2
         mov r2,r3
         mov r3,r4
         mov r4,r5
         bis #4000,@#ps
         tst r0
         beq 9$
         error
9$:
         tst r1
         beq 10$
         error
10$:
         tst r2
         beq 11$
         error
11$:
         tst r3
         beq 12$
         error
12$:
         tst r4
         beq 13$
         error
13$:
         tst r5
         beq 14$
         error
14$:
;
;
;
tst174:
         mov #177777,r0
         cmp r0,#177777
         beq 1$
         error
1$:
         clr r0
         cmp r0,#0
         beq 2$
         error
2$:
         mov #125252,r0
         cmp r0,#125252
         beq 3$
         error
3$:
         mov #52525,r0
         cmp r0,#52525
         beq 4$
         error
4$:
;
;
;
tst175:
         mov #177777,r1
         cmp r1,#177777
         beq 1$
         error
1$:
         clr r1
         cmp r1,#0
         beq 2$
         error
2$:
         mov #125252,r1
         cmp r1,#125252
         beq 3$
         error
3$:
         mov #52525,r1
         cmp r1,#52525
         beq 4$
         error
4$:
;
;
;
tst176:
         mov #177777,r2
         cmp r2,#177777
         beq 1$
         error
1$:
         clr r2
         cmp r2,#0
         beq 2$
         error
2$:
         mov #125252,r2
         cmp r2,#125252
         beq 3$
         error
3$:
         mov #52525,r2
         cmp r2,#52525
         beq 4$
         error
4$:
;
;
;
tst177:
         mov #177777,r3
         cmp r3,#177777
         beq 1$
         error
1$:
         clr r3
         cmp r3,#0
         beq 2$
         error
2$:
         mov #125252,r3
         cmp r3,#125252
         beq 3$
         error
3$:
         mov #52525,r3
         cmp r3,#52525
         beq 4$
         error
4$:
;
;
;
tst200:
         mov #177777,r4
         cmp r4,#177777
         beq 1$
         error
1$:
         clr r4
         cmp r4,#0
         beq 2$
         error
2$:
         mov #125252,r4
         cmp r4,#125252
         beq 3$
         error
3$:
         mov #52525,r4
         cmp r4,#52525
         beq 4$
         error
4$:
;
;
;
tst201:
         mov #177777,r5
         cmp r5,#177777
         beq 1$
         error
1$:
         clr r5
         cmp r5,#0
         beq 2$
         error
2$:
         mov #125252,r5
         cmp r5,#125252
         beq 3$
         error
3$:
         mov #52525,r5
         cmp r5,#52525
         beq 4$
         error
4$:
         bic #4000,@#ps
;
;
;
tst202:
         clr r4
         mov #te115a,r1
         mov #te115b,r2
         mov #te115c,r3
1$:
         mov (r1)+,@#177776
         mfps r4
         cmp @#177776,(r2)+
         beq 2$
         error
2$:
         cmp r4,(r3)+
         beq 3$
         error
3$:
         cmp (r1),#177777
         bne 1$

         mov #te115a,r1
         mov #te115b,r2
         mov #te115c,r3
         mov r6,r5
101$:
         mov (r1),@#177776
         mfps r6
         cmp @#177776,(r2)
         beq 102$
         error
102$:
         cmp r6,(r3)
         beq 103$
         error
103$:
         mov r5,r6

         mov #te115a,r1
         mov #te115b,r2
         mov #te115d,r3
         clr @#expdat
4$:
         mov #expdat,r4
         mov (r1)+,@#177776
         mfps (r4)+
         cmp @#177776,(r2)+
         beq 5$
         error
5$:
         cmp r4,#expdat+1
         beq 6$
         error
6$:
         cmp @#expdat,(r3)+
         beq 7$
         error
7$:
         cmp (r1),#177777
         bne 4$
         jmp te115f

te115a:
         .word 30207
         .word 30000
         .word 30057
         .word 177777
te115b:
         .word 30211
         .word 30004
         .word 30041
te115c:
         .word 177607
         .word 0
         .word 57
te115d:
         .word 207
         .word 0
         .word 57
te115f:
         nop
tellf:
;
;
;
tst203:
         mov #30000,@#177776
         mov #te116d,r1
         mov #te116b,r2
         mov r1,r3
         jsr pc,t116

         mov #140000,@#177776
         mov #600,r6
         mov #te116d,r1
         mov #te116c,r2
         mov r1,r3
         jsr pc,t116

         mov #140000,@#177776
         mov #te116a,r1
         mov #te116c,r2
         mov #te116d,r3
         mov r1,r4
         jsr pc,ta116

         mov #30000,@#177776
         mov #te116a,r1
         mov #te116b,r2
         mov #te116d,r3

         clr @#177776
         mtps #177412
         cmp #12,@#177776
         beq 100$
         error
100$:
         jmp fin116

t116:
         mov (r1)+,r5
         mtps r5
         cmp @#177776,(r2)+
         beq 1$
         error
1$:
         cmp (r3)+,r5
         beq 2$
         error
2$:
         cmp (r2),#177777
         bne t116
         rts pc

ta116:
         mtps (r1)+
         cmp @#177776,(r2)+
         beq 1$
         error
1$:
         cmpb (r4)+,(r3)+
         beq 2$
         error
2$:
         cmp r1,r4
         beq 3$
         error
3$:
         inc r3
         cmp (r2),#177777
         bne ta116
         rts pc

te116a:
         .byte 377
         .byte 0
         .byte 252
         .byte 125
te116b:
         .word 30357
         .word 30000
         .word 30252
         .word 177777
te116c:
         .word 140017
         .word 140000
         .word 140012
         .word 140005
te116d:
         .word 177777
         .word 177400
         .word 177652
         .word 177525
fin116:
;
;
;
tst204:
         jmp tst205
         mov @#10,-(sp)
         mov #te117a,@#10
         mov #177777,r0
         mov #30000,@#177776
         mfpt
         cmp #30000,@#177776
         beq 1$
         error
1$:
         cmp r0,#1111                  ; FIXME maybe? 1111 is our specific cpu designation; maybe we want to simulate a well-known one?
         beq 2$
         error
2$:
         mov #177777,r0
         scc
         mfpt
         cmp #30017,@#177776
         beq 3$
         error
3$:
         cmp r0,#1111
         beq 4$
         error
4$:
         mov (sp)+,@#10
         jmp fin117
te117a:
         error
fin117:
;
;
;
tst205:
         clr @#177766
         clr @#177776
         mov @#4,-(sp)
         mov @#6,-(sp)
         mov @#10,-(sp)   ; oops, 11/45 traps to 10 on user mode halt
         mov @#12,-(sp)
         mov #te120a,@#4
         clr @#6
         mov #te120a,@#10
         clr @#12
         mov #140000,@#ps
         mov #600,r6
         halt
procnt:
         error
         jmp fin120       ; ??
te120a:
         cmp #30000,@#177776
         beq 1$
         error
1$:
         cmp #200,@#177766
         beq 2$
         br 2$
         error
2$:
         cmp (sp)+,#procnt
         beq 3$
         error
3$:
         cmp (sp)+,#140000
         beq fin120
         error
fin120:
         clr @#177766
         mov (sp)+,@#12
         mov (sp)+,@#10
         mov (sp)+,@#6
         mov (sp)+,@#4
;
;
;
tst206:
1$:
         mov #30340,@#177776
         mov #160000,@#sr0
         mov #77,@#sr3
         clr @#177772
         cmp @#177772,#0
         beq c121a
         error
c121a:
         mov #25000,@#177772
         cmp #25252,@#177772
         beq c121b
         error
c121b:
         mov #77000,@#177772
         cmp #77314,@#177772
         beq c121c
         error
c121c:
         scc
         reset
         cmp #30357,@#177776
         beq 1$
         error
1$:
         mov @#sr0,r1
         bic #176,r1
         cmp #0,r1
         beq 2$
         error
2$:
         cmp #0,@#sr3
         beq 3$
         error
3$:
         cmp #0,@#177772
         beq 4$
         error
4$:
         mov @#4,r2
         mov @#6,r3
         mov @#10,r4
         mov @#12,r5
         mov #8$,@#4
         mov #340,@#6
         mov #8$,@#10
         mov #340,@#12       ; ! user mode halt traps to 10 on 11/45

         mov #140340,@#177776
         mov #160000,@#sr0
         mov #77,@#sr3
         mov #77000,@#177772
         scc
         reset
         cmp #140357,@#177776
         beq 5$
         halt                ; ! user mode halt traps to illegal insn
         error
5$:
         mov @#sr0,r1
         bic #176,r1
         cmp #160000,r1
         beq 6$
         halt                ; ! user mode halt traps to illegal insn
         error
6$:
         cmp #17,@#sr3       ; mmu on 11/45 has 4 bits in sr3, not 6. Other 2 are enable for csm insn, and 22-bit mode enable
         beq 7$
         halt                ; ! user mode halt traps to illegal insn
         error
7$:
         cmp #77314,@#177772
         beq 9$
         error
8$:
         rti
9$:
         clr @#177772
         clr @#177776
         mov r2,@#4
         mov r3,@#6
         mov r4,@#10
         mov r5,@#12
;
;
;
tst207:
         mov #8.,r5
         mov #t122b,r1
1$:
         mov #30000,@#177776
         jsr pc,t122a
         cmp (r1)+,@#177776
         beq 2$
         error
2$:
         sob r5,1$

         mov #8.,r5
3$:
         mov #140000,@#177776
         mov #600,r6
         jsr pc,t122a
         cmp #140017,@#177776
         beq 4$
         error
4$:
         sob r5,3$
         jmp fin122

t122a:
         cmp r5,#8.
         bne 1$
         scc
         spl 0
         br 8$
1$:
         cmp r5,#7
         bne 2$
         scc
         spl 1
         br 8$
2$:
         cmp r5,#6
         bne 3$
         scc
         spl 2
         br 8$
3$:
         cmp r5,#5
         bne 4$
         scc
         spl 3
         br 8$
4$:
         cmp r5,#4
         bne 5$
         scc
         spl 4
         br 8$
5$:
         cmp r5,#3
         bne 6$
         scc
         spl 5
         br 8$
6$:
         cmp r5,#2
         bne 7$
         scc
         spl 6
         br 8$
7$:
         scc
         spl 7
8$:
         rts pc

t122b:
         .word 30017
         .word 30057
         .word 30117
         .word 30157
         .word 30217
         .word 30257
         .word 30317
         .word 30357
fin122:
;
;
;
tst210:
         clr @#177776
         mov #10.,r3
         mov #400,r1
         mov #t123a,r0
100$:
         mov (r0)+,(r1)+
         sob r3,100$
         mov @#10,-(sp)
         mov #t123d,@#10
         clr r0
         mov #400,r1
         mov #410,r2
         mov #416,r3
         mov r1,r4
1$:
         mov #30000,@#177776
         sev
         .word 7221                 ; tstset (r1)+
         cmp (r2)+,@#177776
         beq 2$
         error
2$:
         cmp r0,(r3)
         beq 3$
         error
3$:
         inc r4
         inc r4
         cmp r4,r1
         beq 4$
         error
4$:
         bis #1,(r3)
         cmp (r3)+,-(r1)
         beq 5$
         error
5$:
         inc r1
         inc r1
         cmp (r1),#177777
         bne 1$
         mov #t123e,@#10
         .word 7201                 ; tstset r1
         error
         jmp t123f
t123a:
         .word 167604
         .word 0
         .word 1
         .word 177777
t123b:
         .word 30010
         .word 30004
         .word 30001
t123c:
         .word 167604
         .word 0
         .word 1
t123d:
         error
t123e:
         tst (sp)+
         tst (sp)+
t123f:
         mov (sp)+,@#10
;
;
;
tst211:
         clr @#177776
         mov #10.,r3
         mov #400,r1
         mov #t124a,r0
100$:
         mov (r0)+,(r1)+
         sob r3,100$
         mov @#10,-(sp)
         mov #t124d,@#10
         mov #400,r1
         mov #410,r2
         mov #416,r3
         mov r2,r4
1$:
         mov #30000,@#177776
         mov (r1),r0
         cmp r3,#416
         beq 2$
         bne 3$
2$:
         sec
         br 4$
3$:
         clc
4$:
         sev
         .word 7322
         cmp (r3)+,@#177776
         beq 5$
         error
5$:
         cmp (r1),r0
         beq 6$
         error
6$:
         inc r4
         inc r4
         cmp r2,r4
         beq 7$
         error
7$:
         cmp (r1)+,-(r2)
         beq 8$
         error
8$:
         inc r2
         inc r2
         cmp (r1),#177777
         bne 1$
         mov #t124e,@#10
         .word 7302
         error
         jmp t124f
t124a:
         .word 167604
         .word 0
         .word 1
         .word 177777
t124b:
         .word 177777
         .word 177777
         .word 177777
t124c:
         .word 30011
         .word 30004
         .word 30000
t124d:
         error
t124e:
         tst (sp)+
         tst (sp)+
t124f:
         mov (sp)+,@#10
;
;
;
tst212:
         clr @#177776
         mov #te125a,r1
1$:
         mov r1,@#expdat
         add #2,@#expdat
         mov #122222,r3
         mov (r1),r2
         scc
         mul 2(r1),r2
         cmp 4(r1),@#177776
         beq 2$
         error
2$:
         cmp 6(r1),r3
         beq 3$
         error
3$:
         cmp 10(r1),r2
         beq 4$
         error
4$:
         cmp 2(r1),@expdat
         beq 5$
         error
5$:
         add #12,r1
         cmp r1,#fin125
         bne 1$
6$:
         mov #te125a,r1
7$:
         mov r1,r2
         mov #stbot,r6
         mov #4,r4
         mov (r1),r5
         scc
         mul 2(r1),r5
         cmp 4(r1),@#177776
         beq 8$
         error
8$:
         cmp 6(r1),r5
         beq 9$
         error
9$:
         cmp r6,#stbot
         beq 10$
         mov #stbot,r6
         error
10$:
         tst (r2)+
         cmp (r2),2(r1)
         beq 11$
         error
11$:
         cmp r4,#4
         beq 12$
         error
12$:
         add #12,r1
         cmp r1,#fin125
         bne 7$
         jmp fin125

te125a:
         .word 177777        ; 1
         .word 177777
         .word 0
         .word 1
         .word 0

         .word 6772          ; 2
         .word 100000
         .word 11
         .word 0
         .word 174403

         .word 177777        ; 3
         .word 77777
         .word 10
         .word 100001
         .word 177777

         .word 77777         ; 4
         .word 456
         .word 1
         .word 177322
         .word 226

         .word 173210        ; 5
         .word 0
         .word 4
         .word 0
         .word 0

         .word 0             ; 6
         .word 3251
         .word 4
         .word 0
         .word 0

         .word 0             ; 7
         .word 0
         .word 4
         .word 0
         .word 0

         .word 100000        ; 8
         .word 1
         .word 10
         .word 100000
         .word 177777

         .word 77777         ; 9
         .word 1
         .word 0
         .word 77777
         .word 0

         .word 10            ; 10
         .word 10000
         .word 1
         .word 100000
         .word 0

         .word 1452          ; 11
         .word 34527
         .word 1
         .word 66506
         .word 265

         .word 7             ; 12
         .word 400
         .word 0
         .word 3400
         .word 0

         .word 2             ; 13
         .word 100000
         .word 11
         .word 0
         .word 177777

         .word 100000        ; 14
         .word 77777
         .word 11
         .word 100000
         .word 140000

         .word 1             ; 15
         .word 177777
         .word 10
         .word 177777
         .word 177777
fin125:
;
;
;
tst213:
         clr @#177776
         clr r6
         mov @#0,r5
         mov @#2,r1
         mov #137,@#0
         mov #te126a,@#2
         scc
         div #2,r6
a126$:
         mov #stbot,r6
         error
te126a:
         cmp #0,@#177776
         beq 1$
         mov #stbot,r6
         error
1$:
         mov #a126$,r4
         asr r4
         cmp r4,r6
         beq 2$
         mov #stbot,r6
         error
2$:
         mov r5,@#0
         mov r1,@#2
         mov #stbot,r6
         mov #6,r2
         mov #47,r3
         scc
         div r2,r3
         cmp #2,@#177776
         beq 3$
         error
3$:
         cmp #6,r2
         beq 4$
         error
4$:
         cmp #47,r3
         beq 5$
         error
5$:
         clr r4
         mov #4,r5
         scc
         div #0,r4
         cmp #7,@#177776
         beq 6$
         error
6$:
         cmp #0,r4
         beq 7$
         error
7$:
         cmp #4,r5
         beq 8$
         error
8$:
         mov #4,r0
         mov #10,r5
         clr r4
         scc
         div r0,r4
         cmp #0,@#177776
         beq 9$
;         mov r0,400     ??
         error
;         mov 400,r0     ??
9$:
         cmp #4,r0
         beq 10$
         error
10$:
         cmp #2,r4
         beq 11$
         error
11$:
         cmp #0,r5
         beq 12$
         error
12$:
         mov #10,r5
         clr r4
         scc
         div #3,r4
         cmp #0,@#177776
         beq 13$
         error
13$:
         cmp #2,r4
         beq 14$
         error
14$:
         cmp #2,r5
         beq 15$
         error
15$:
         mov #te126b,r1
16$:
         mov r1,@#expdat
         mov (r1),r4
         mov 4(r1),r3
         mov 2(r1),r5
         scc
         div 4(r1),r4
         cmp 6(r1),@#177776
         beq 17$
         error
17$:
         cmp 10(r1),r5
         beq 18$
         error
18$:
         cmp 12(r1),r4
         beq 19$
         error
19$:
         cmp @#expdat,r1
         beq 20$
         error
         mov @#expdat,r1         ; ??
20$:
         cmp 4(r1),r3
         beq 21$
         error
         mov r3,4(r1)            ; ??
21$:
         add #14,r1
         cmp (r1),#333
         bne 16$
         jmp fin126
te126b:
         .word 177777            ; 1
         .word 177777
         .word 177777
         .word 0
         .word 0
         .word 1

         .word 0                 ; 2
         .word 177777
         .word 177777
         .word 12
         .word 177777
         .word 0

         .word 177777            ; 3
         .word 0
         .word 177777
         .word 2
         .word 0
         .word 177777

         .word 0                 ; 4
         .word 7642
         .word 7643
         .word 4
         .word 7642
         .word 0

         .word 0                 ; 5
         .word 137
         .word 177543
         .word 4
         .word 137
         .word 0

         .word 0                 ; 6
         .word 7643
         .word 7643
         .word 0
         .word 0
         .word 1

         .word 100000            ; 7
         .word 4376
         .word 10021
         .word 12
         .word 4376
         .word 100000

         .word 177700            ; 8
         .word 170033
         .word 10021
         .word 10
         .word 171307
         .word 176024

         .word 177700            ; 9
         .word 170033
         .word 167757
         .word 0
         .word 171307
         .word 1754

         .word 0                 ; 10
         .word 177777
         .word 1
         .word 2
         .word 177777
         .word 0

         .word 177777            ; 11
         .word 45716
         .word 1
         .word 12
         .word 45716
         .word 177777

         .word 0                 ; 12
         .word 2
         .word 177770
         .word 4
         .word 2
         .word 0

         .word 177777            ; 13
         .word 177776
         .word 10
         .word 4
         .word 177776
         .word 0

         .word 1                 ; 14
         .word 177777
         .word 1
         .word 2
         .word 177777
         .word 1

         .word 1                 ; 15
         .word 0
         .word 2
         .word 2
         .word 0
         .word 1

         .word 1                 ; 16
         .word 0
         .word 3
         .word 0
         .word 1
         .word 52525

         .word 23                ; 17
         .word 16054
         .word 16537
         .word 0
         .word 10222
         .word 246

         .word 333
fin126:
;
;
;
tst214:
         clr @#177776
         mov #1,r2
         scc
         ash r2,r2
         cmp #0,@#177776
         beq 1$
         error
1$:
         cmp r2,#2
         beq 2$
         error
2$:
         mov #100000,r2
         mov #1,r3
         ccc
         ash r3,r2
         cmp #7,@#177776
         beq 3$
         error
3$:
         cmp r3,#1
         beq 4$
         error
4$:
         cmp r2,#0
         beq 5$
         error
5$:
         mov #te127a,r1
6$:
         mov r1,r3
         mov 2(r1),r2
         scc
         ash (r1),r2
         cmp 4(r1),@#177776
         beq 7$
         error
7$:
         cmp 6(r1),r2
         beq 8$
         error
8$:
         cmp r3,r1
         beq 9$
         error
9$:
         cmp (r3),(r1)
         beq 10$
         error
10$:
         add #10,r1
         cmp r1,#fin127
         bne 6$
         jmp fin127

te127a:
         .word 177761
         .word 77777
         .word 5
         .word 0

         .word 177700
         .word 17777
         .word 0
         .word 17777

         .word 177700
         .word 100000
         .word 10
         .word 100000

         .word 177777
         .word 100000
         .word 10
         .word 140000

         .word 177737
         .word 177777
         .word 11
         .word 177777

         .word 177706
         .word 102000
         .word 7
         .word 0

         .word 177710
         .word 17777
         .word 13
         .word 177400

         .word 177713
         .word 12
         .word 0
         .word 50000

         .word 177707
         .word 170001
         .word 2
         .word 200

         .word 177717
         .word 1
         .word 12
         .word 100000

         .word 177740
         .word 17777
         .word 4
         .word 0

         .word 177771
         .word 150000
         .word 10
         .word 177640

         .word 177742
         .word 100000
         .word 11
         .word 177777

         .word 177764
         .word 100000
         .word 10
         .word 177770

         .word 177750
         .word 52525
         .word 4
         .word 0

         .word 177760
         .word 100000
         .word 11
         .word 177777

         .word 177770
         .word 100000
         .word 10
         .word 177600

         .word 177712
         .word 4367
         .word 13
         .word 156000

         .word 177764
         .word 17777
         .word 1
         .word 1

         .word 177701
         .word 110000
         .word 3
         .word 20000
fin127:
;
;
;
tst215:
         clr @#177776
         mov #23,r1
         mov #52525,r5
         clr r4
         scc
         ashc r1,r4
         cmp @#177776,#12
         beq 1$
         error
1$:
         cmp r1,#23
         beq 2$
         error
2$:
         cmp r4,#125250
         beq 3$
         error
3$:
         cmp r5,#0
         beq 4$
         error
4$:
         mov #52525,r3
         clr r2
         mov #164731,r4
         scc
         ashc #23,r3
         cmp @#177776,#12
         beq 5$
         error
5$:
         cmp r2,#0
         beq 6$
         error
6$:
         cmp r3,#0
         beq 7$
         error
7$:
         cmp r4,#164731
         beq 8$
         error
8$:
         mov #te130a,r1
9$:
         mov r1,r4
         mov 2(r1),r2
         mov 4(r1),r3
         scc
         ashc (r1),r2
         cmp @#177776,6(r1)
         beq 10$
         error
10$:
         cmp 10(r1),r2
         beq 11$
         error
11$:
         cmp 12(r1),r3
         beq 12$
         error
12$:
         cmp r4,r1
         beq 13$
         error
13$:
         cmp (r1),(r4)
         beq 14$
         error
14$:
         add #14,r1
         cmp r1,#fin130
         bne 9$
         jmp fin130

te130a:
         .word 177700
         .word 100125
         .word 177777
         .word 10
         .word 100125
         .word 177777

         .word 177777
         .word 1
         .word 0
         .word 0
         .word 0
         .word 100000

         .word 177701
         .word 47777
         .word 100000
         .word 12
         .word 117777
         .word 0

         .word 177706
         .word 4256
         .word 177700
         .word 2
         .word 25677
         .word 170000

         .word 177711
         .word 65700
         .word 12
         .word 13
         .word 100000
         .word 12000

         .word 177737
         .word 0
         .word 1
         .word 4
         .word 0
         .word 0

         .word 177736
         .word 0
         .word 1
         .word 0
         .word 40000
         .word 0

         .word 177740
         .word 100000
         .word 0
         .word 11
         .word 177777
         .word 177777

         .word 177725
         .word 177777
         .word 174000
         .word 7
         .word 0
         .word 0

         .word 177724
         .word 177777
         .word 174000
         .word 11
         .word 100000
         .word 0

         .word 177733
         .word 177777
         .word 157023
         .word 12
         .word 114000
         .word 0

         .word 177727
         .word 0
         .word 177777
         .word 13
         .word 177600
         .word 0

         .word 177717
         .word 177777
         .word 1
         .word 11
         .word 100000
         .word 100000

         .word 177741
         .word 100000
         .word 0
         .word 10
         .word 177777
         .word 177777

         .word 177742
         .word 37777
         .word 177777
         .word 5
         .word 0
         .word 0

         .word 177742
         .word 77777
         .word 177777
         .word 1
         .word 0
         .word 1

         .word 177711
         .word 65600
         .word 12
         .word 3
         .word 0
         .word 12000

         .word 177740
         .word 77777
         .word 177777
         .word 4
         .word 0
         .word 0

         .word 177737
         .word 177777
         .word 177774
         .word 11
         .word 177777
         .word 177777

         .word 177747
         .word 100000
         .word 174000
         .word 10
         .word 177777
         .word 177700

         .word 177753
         .word 6324
         .word 71002
         .word 1
         .word 0
         .word 146

         .word 177765
         .word 102351
         .word 177231
         .word 11
         .word 177760
         .word 116477
fin130:
;
;
;
tst216:
         clr r6
         movb (r6)+,expdat             ; original is count
         cmp #2,r6
         beq spau1
         error
spau1:
         clr r6
         movb (r6)+,expdat
         movb (r6)+,expdat
         cmp #4,r6
         beq spau2
         error
spau2:
         mov #stbot,r6
         movb -(r6),expdat
         cmp #stbot-2,r6
         beq spau3
         error
spau3:
         mov #stbot,r6
         movb -(r6),expdat
         movb -(r6),expdat
         cmp #stbot-4,r6
         beq spau4
         error
spau4:
         clr r6
         tstb (r6)+
         cmp r6,#2
         beq spau5
         error
spau5:
         mov #stbot,r6
         tstb -(r6)
         cmp #stbot-2,r6
         beq spau6
         error
spau6:
         mov #stbot,r6
;
;
;
tst217:
         clr @#cpereg
         mov #150,r6
         mov @#4,sloc00
         mov #mtrya,@#4
         mov @#146,r1
         mov @#144,r2
         mov @#142,r3
         clr @#146
         clr -(r6)
         mov #stbot,r6
         error
mtrya:
         cmp #10,@#cpereg
         bne 1$
         cmp r6,#142
         beq mtryb
1$:
         error
mtryb:
         clr @#cpereg
         mov sloc00,@#4
         mov r1,@#146
         mov r2,@#144
         mov r3,@#142
         mov #stbot,r6
;
;
;
tst220:
         clr @#cpereg
         mov #400,r6
         mov @#4,sloc00
         mov #tryma,@#4
         clr @#376
         clr -(r6)
         mov #stbot,r6
         error
tryma:
         clr @#cpereg
         mov #1000,r5
         mov #400,r6
         mov #trymb,@#4
         add -(r6),-(r5)
         mov #stbot,r6
         error
trymb:
         clr @#cpereg
         mov #150,r6
         mov #trymc,@#4
         bic -(r5),-(r6)
         mov #stbot,r6
         error
trymc:
         clr @#cpereg
         mov sloc00,@#4
         mov #stbot,r6
;
;
;
tst221:
         clr @#cpereg
         mov #400,r6
         mov @#10,sloc00
         mov #mill0a,@#10
         mov @#4,sloc01
         mov #mill0b,@#4
         77
         nop
mill0a:
         mov #stbot,r6
         error
mill0b:
         mov sloc01,@#4
         mov sloc00,@#10
         clr @#cpereg
         mov #stbot,r6
;
;
;
tst222:
         clr @#cpereg
         mov #400,r6
         mov @#20,sloc00
         mov #iot0a,@#20
         mov @#4,sloc01
         mov #iot0b,@#4
         iot
         nop
iot0a:
         mov #stbot,r6
         error
iot0b:
         clr @#cpereg
         mov #stbot,r6
         mov sloc01,@#4
         mov sloc00,@#20
;
;
;
tst223:
         clr @#cpereg
         mov #400,r6
         mov @#30,sloc00
         mov #memt0a,@#30
         mov @#4,sloc01
         mov #memt0b,@#4
         emt 0
         nop
memt0a:
         mov #stbot,r6
         error
memt0b:
         mov sloc00,@#30
         mov sloc01,@#4
         clr @#cpereg
         mov #stbot,r6
;
;
;
tst224:
         clr @#cpereg
         mov #400,r6
         mov @#34,sloc00
         mov #trp0a,@#34
         mov @#4,sloc01
         mov #trp0b,@#4
         trap 0
         nop
trp0a:
         mov #stbot,r6
         error
trp0b:
         mov sloc00,@#34
         mov sloc01,@#4
         clr @#cpereg
         mov #stbot,r6
;
;
;
tst225:
         clr @#cpereg
         mov #400,r6
         mov @#14,sloc00
         mov #bpt0a,@#14
         mov @#4,sloc01
         mov #bpt0b,@#4
         bpt
         nop
bpt0a:
         mov #stbot,r6
         error
bpt0b:
         clr @#cpereg
         mov sloc00,@#14
         mov sloc01,@#4
         mov #stbot,r6
;
;
;
tst226:
         clr @#cpereg
         mov #400,r6
         mov @#10,sloc00
         mov #ila0a,@#10
         mov @#4,sloc01
         mov #ilb0b,@#4

         clr r1
         jmp r1
         nop
ila0a:
         mov #stbot,r6
         error
ilb0b:
         mov sloc01,@#4
         mov sloc00,@#10
         clr @#cpereg
         mov #stbot,r6
;
;
;
tst227:
         clr @#cpereg
         mov #400,r6
         mov @#10,sloc00
         mov #illb0a,@#10
         mov #illb0b,@#4

         clr r1
         jsr r5,r1
         nop
illb0a:
         mov #stbot,r6
         error
illb0b:
         clr @#cpereg
         mov sloc00,@#10
         mov sloc01,@#4
         mov #stbot,r6
;
;
;
tst230:
         mov @#4,sloc00
         mov #mst0e,@#4
         mov #1002,r6
         tst -(r6)
         mov #2002,r6
         tst -(r6)
         mov #4002,r6
         tst -(r6)
         mov #10002,r6
         tst -(r6)
;         mov #100402,r6                        ; FIXME there is not that much core yet
;         tst -(r6)
         br mst0ee
mst0e:
         mov #stbot,r6
         error
mst0ee:
         mov sloc00,@#4
         mov #stbot,r6
;
;
;
tst231:
         mov #stbot,r6
         mov @#14,sloc00
         mov #20,-(r6)
         mov #mtta,-(r6)
         mov #mttb,@#14
         rti
         error
mtta:
         error
mttb:
         cmp #stbot-4,r6
         beq mttd
         error
mttd:
         cmp (r6),#mtta
         beq mtte
         error
mtte:
         mov sloc00,@#14
         mov #stbot,r6
;
;
;
tst232:
         mov #stbot,r6
         mov @#14,sloc00
         mov #20,-(r6)
         mov #mttsa,-(r6)
         mov #mttsb,@#14
         rtt
         error
mttsa:
         nop
mttsq:
         error
mttsb:
         cmp #stbot-4,r6
         beq mttsd
         error
mttsd:
         cmp (r6),#mttsq
         beq mttse
         error
mttse:
         mov sloc00,@#14
         mov #stbot,r6
;
;
;
tst233:
         mov #stbot,r6
         mov @#14,sloc00
         mov #20,-(r6)
         mov #mttra,-(r6)
         mov #mttrb,@#14
         mov #357,@#177776
         scc
         rti
         error
mttra:
         error
mttrb:
         cmp stbot-2,#20
         beq mttrq
         error
mttrq:
         mov #stbot,r6
         mov #377,-(r6)
         mov #mttrd,-(r6)
         mov #mttre,@#14
         mov #0,@#177776
         ccc
         rti
         error
mttrd:
         error
mttre:
         cmp stbot-2,#377
         beq mttrf
         error
mttrf:
         mov sloc00,@#14
         mov #stbot,r6
;
;
;
tst234:
         mov #stbot,r6
         mov @#10,sloc00
         mov #mrtb,@#10
         77
mrta:
         error
mrtb:
         cmp #stbot-4,r6
         beq mrte
         error
mrte:
         cmp (r6),#mrta
         beq mrtf
         error
mrtf:
         mov sloc00,@#10
         mov #stbot,r6
;
;
;
tst235:
         mov #stbot,r6
         mov @#10,sloc00
         mov #mrt0b,@#10
         clr @#177776
         ccc
         77
mrt0a:
         error
mrt0b:
         cmp stbot-2,#0
         beq mrt0c
         error
mrt0c:
         mov #stbot,r6
         mov #mrt0e,@#10
         mov #357,@#177776
         scc
         77
mrt0d:
         error
mrt0e:
         cmp stbot-2,#357
         beq mrt0f
         error
mrt0f:
         mov sloc00,@#10
         mov #stbot,r6
;
;
;
tst236:
         mov #stbot,r6
         mov @#34,sloc00
         mov #mtpb,@#34
         clr @#177776
         ccc
         trap 0
mtpr:
         error
mtpb:
         cmp #stbot-4,r6
         beq mtpq
         error
mtpq:
         cmp (r6),#mtpr
         beq mtpf
         error
mtpf:
         mov sloc00,@#34
         mov #stbot,r6
;
;
;
tst237:
         mov #stbot,r6
         mov @#34,sloc00
         mov #mtp0b,@#34
         clr @#177776
         ccc
         trap 0
mtp0a:
         error
mtp0b:
         cmp stbot-2,#0
         beq mtp0c
         error
mtp0c:
         mov #stbot,r6
         mov #mtp0e,@#34
         mov #357,@#177776
         scc
         trap 0
mtp0d:
         error
mtp0e:
         cmp stbot-2,#357
         beq mtp0f
         error
mtp0f:
         mov sloc00,@#34
         mov #stbot,r6
;
;
;
tst240:
         clr r3
         mov #stbot,r6
         mov @#34,sloc00
         mov @#4,sloc01
         mov #mtpah,@#4
         mov #mtpaa,@#34
         jmp mtpaa
mtpal:
         halt
         error
         jmp mtpaa
mtpah:
         error
mtpaa:
         inc r3
         mov #stbot,r6
         cmp r3,#400
         beq mtpae
         mov #104400,@#mtpal
         add r3,@#mtpal
         br mtpal
mtpae:
         mov sloc00,@#34
         mov sloc01,@#4
         mov #stbot,r6
;
;
;
tst241:
         mov #stbot,r6
         mov @#20,sloc00
         mov #miotb,@#20
         iot
miota:
         error
miotb:
         cmp #stbot-4,r6
         beq miotd
         error
miotd:
         cmp (r6),#miota
         beq miotf
         error
miotf:
         mov sloc00,@#20
         mov #stbot,r6
;
;
;
tst242:
         mov #stbot,r6
         mov @#20,sloc00
         mov #mitob,@#20
         clr @#177776
         ccc
         iot
mitoa:
         error
mitob:
         cmp stbot-2,#0
         beq mitoc
         error
mitoc:
         mov #stbot,r6
         mov #mitoe,@#20
         mov #357,@#177776
         scc
         iot
mitod:
         error
mitoe:
         cmp stbot-2,#357
         beq mitof
         error
mitof:
         mov sloc00,@#20
         mov #stbot,r6
;
;
;
tst243:
         mov #stbot,r6
         mov @#30,sloc00
         mov #metb,@#30
         emt 0
meta:
         error
metb:
         cmp #stbot-4,r6
         beq metd
         error
metd:
         cmp (r6),#meta
         beq metf
         error
metf:
         mov sloc00,@#30
         mov #stbot,r6
;
;
;
tst244:
         mov #stbot,r6
         mov @#30,sloc00
         mov #metob,@#30
         clr @#177776
         ccc
         emt 0
metoa:
         error
metob:
         cmp stbot-2,#0
         beq metoc
         error
metoc:
         mov #stbot,r6
         mov #metoe,@#30
         mov #357,@#177776
         scc
         emt 0
metod:
         error
metoe:
         cmp stbot-2,#357
         beq metof
         error
metof:
         mov sloc00,@#30
         mov #stbot,r6
;
;
;
tst245:
         mov #stbot,r6
         mov @#14,sloc00
         mov #mbtb,@#14
         bpt
mbta:
         error
mbtb:
         cmp #stbot-4,r6
         beq mbtd
         error
mbtd:
         cmp (r6),#mbta
         beq mbtf
         error
mbtf:
         mov sloc00,@#14
         mov #stbot,r6
;
;
;
tst246:
         mov #stbot,r6
         mov @#14,sloc00
         mov #mbtob,@#14
         clr @#177776
         ccc
         bpt
mbtoa:
         error
mbtob:
         cmp stbot-2,#0
         beq mbtoc
         error
mbtoc:
         mov #stbot,r6
         mov #mbtoe,@#14
         mov #357,@#177776
         scc
         bpt
mbtod:
         error
mbtoe:
         cmp stbot-2,#357
         beq mbtof
         error
mbtof:
         mov sloc00,@#14
         mov #stbot,r6
;
;
;
tst247:
         mov #stbot,r6
         mov @#10,sloc00
         mov #milb,@#10
         clr r1
         jmp r1
mila:
         error
milb:
         cmp #stbot-4,r6
         beq mild
         error
mild:
         cmp (r6),#mila
         beq milf
         error
milf:
         mov sloc00,@#10
         mov #stbot,r6
;
;
;
tst250:
         mov #stbot,r6
         mov @#10,sloc00
         mov #milob,@#10
         clr @#177776
         ccc
         clr r1
         jmp r1
miloa:
         error
milob:
         cmp stbot-2,#4
         beq miloc
         error
miloc:
         mov #stbot,r6
         mov #miloe,@#10
         mov #357,@#177776
         scc
         jmp r1
milod:
         error
miloe:
         cmp stbot-2,#357
         beq milof
         error
milof:
         mov sloc00,@#10
         mov #stbot,r6
;
;
;
tst251:
         mov #stbot,r6
         mov @#10,sloc00
         mov #miallb,@#10
         clr r3
         jsr r3,r3
mialla:
         error
miallb:
         cmp #stbot-4,r6
         beq mialld
         error
mialld:
         cmp (r6),#mialla
         beq miallf
         error
miallf:
         mov sloc00,@#10
         mov #stbot,r6
;
;
;
tst252:
         mov #stbot,r6
         mov @#10,sloc00
         mov #mjsib,@#10
         clr @#177776
         ccc
         clr r3
         jsr r3,r3
mjsia:
         error
mjsib:
         cmp stbot-2,#4
         beq mjsic
         error
mjsic:
         mov #stbot,r6
         mov #mjsie,@#10
         mov #357,@#177776
         scc
         jsr r3,r3
mjsid:
         error
mjsie:
         cmp stbot-2,#357
         beq mjsif
         error
mjsif:
         mov sloc00,@#10
         mov #stbot,r6
;
;
;
tst253:
         clr @#cpereg
         mov @#4,sloc00
         mov #2$,@#4
         mov #30000,@#177776
         tst @#177700                         ; this one should not exist
1$:
         error
2$:
         cmp #20,@#cpereg
         beq 3$
         error
3$:
         cmp (r6)+,#1$
         beq 4$
         error
4$:
         cmp (r6)+,#30000
         beq 5$
         error
5$:
         clr @#cpereg
         mov sloc00,@#4
;
;
;
tst254:
         clr @#cpereg
         mov @#4,sloc00
         mov #2$,@#4
         mov @#6,sloc01
         clr @#6
         mov #30000,-(r6)
         mov #1$+1,-(r6)
         rti
1$:
         error
2$:
         cmp #100,@#cpereg
         beq 3$
         error
3$:
         cmp #1$+1,(r6)+
         beq 4$
         error
4$:
         cmp #30000,(r6)+
         beq 5$
         error
5$:
         clr @#cpereg
         mov #7$,@#4
         mov #30340,@#6
         clr @#177776
         jmp @#177776
6$:
         error
7$:
         mov @#177776,r1
         cmp #100,@#cpereg
         beq 8$
         error
8$:
         cmp #177776,(r6)+
         beq 9$
         error
9$:
         cmp #0,(r6)+
         beq 10$
         error
10$:
         cmp #340,r1
         beq 11$
         error
11$:
         clr @#cpereg
         mov sloc00,@#4
         mov sloc01,@#6
;
;
;
tst255:                        ; FIXME??? differences from original to allow for no apt
         mov @#4,sloc00
         mov #2$,@#4
10$:
         mov #777,r6
         clr @#cpereg
         clr @#177776
         tst @#177700
1$:
;         mov #stbot,r6
         error
2$:
         cmp #0,r6
         beq 3$
;         mov #stbot,r6
         error
3$:
         cmp #1$,(r6)+
         beq 4$
;         mov #stbot,r6
         error
4$:
         cmp #0,(r6)
         beq 5$
;         mov #stbot,r6
         error
5$:
         cmp #124,@#cpereg
         beq 6$
         error
6$:
         clr @#cpereg
         mov #stbot,r6
         mov sloc00,@#4
         clr @#0
         clr @#2
;
;
;
tst256:
         mov @#4,sloc00
         mov #pirqnx,@#4
         clr @#cpereg
         tst @#pirq
         mov sloc00,@#4
         br pirtex
pirqnx:
         error
pirtex:
;
;
;
tst257:
         mov @#240,sloc00
         mov @#242,sloc01
         mov unxpir,@#240
         mov #pr7,@#242
         mov #1000,r3
         mov #pirtbl,r4
1$:
         spl 7
         clr @#pirq
         cmp @#pirq,(r4)+
         beq 2$
         error
2$:
         mov r3,@#pirq
         cmp @#pirq,(r4)+
         beq 3$
         error
3$:
         asl r3
         bcc 2$
         br expir1

pirtbl:
         .word 0
         .word 1042
         .word 2104
         .word 4146
         .word 10210
         .word 20252
         .word 40314
         .word 100356
expir1:
;
;
;
tst260:
         spl 7
         clr @#pirq
         mov #177000,r3
         mov #pitbl1,r4
1$:
         mov r3,@#pirq
         cmp @#pirq,(r4)
         beq 2$
         error
2$:
         ror r3
         bic #777,r3
         tst (r4)+
         bne 1$
         br pir2ex

pitbl1:
         .word 177356
         .word 77314
         .word 37252
         .word 17210
         .word 7146
         .word 3104
         .word 1042
         .word 0

unxpir:
         error
pir2ex:
;
;
;
tst261:
         mov #1000,r3
         mov #pirrtn,@#240
         mov #340,@#242
         clr r4
pi1:
         tst (r4)+
         bis r3,@#pirq
         spl 0
         error
pi3:
         add #4,r6
         asl r3
         bcc pi1
         br pir3ex
pirrtn:
         mov @#pirq,r5
         clr @#pirq
         bic #177761,r5
         cmp r4,r5
         beq pi2
         error
pi2:
         jmp pi3
pir3ex:
;
;
;
tst262:
         clr @#pirq
         clr @#177776
         spl 7
         mov #1000,r3
         mov #2$,@#240
         mov #340,@#242
1$:
         mov r3,@#pirq
         asl r3
         bcc 1$
         clr @#pirq
         br 3$
2$:
         clr @#pirq
         error
3$:
;
;
;
tst263:
         clr @#pirq
         mov #10$,@#240
         mov #340,@#242
         mov #pitbl2,r5
         mov #6,@#dcount
1$:
         clr r4
         mov #1000,r3
         mov (r5)+,@#177776
3$:
         tst (r4)+
         mov r3,@#pirq
         mov @#177776,r1
         mov @#pirq,r2
         bic #177437,r1
         bic #177437,r2
         cmp r1,r2
         bge 4$
         error
4$:
         asl r3
         bcc 3$
         dec @#dcount
         bne 1$
         jmp pir5ex
10$:
         mov @#pirq,-(r6)
         clr @#pirq
         mov 4(r6),r1
         mov (r6),r2
         bic #177437,r2
         bic #177437,r1
         cmp r1,r2
         bmi 20$
         error
20$:
         mov (r6)+,r2
         bic #177761,r2
         cmp r4,r2
         beq 21$
         error
21$:
         mov #4$,(r6)
         rti

pitbl2:
         .word 300
         .word 240
         .word 200
         .word 140
         .word 100
         .word 40
pir5ex:
;
;
;
tst264:
         clr @#pirq
         spl 7
         mov #10$,@#240
         mov #340,@#242
         mov #177000,r3
         mov r3,@#pirq
         mov #16,r4
         spl 0

         tst r4
         beq pir6ex
         error
10$:
         tst -(r4)
         ror r3
         bic #777,r3
         mov r3,@#pirq
         rti
pir6ex:
         mov sloc00,@#240
         mov sloc01,@#242
;
; end copy czkdjb0
;
tstm1:
         clr @#cpereg
         clr @#177572
         clr @#flag
         mov @#4,-(sp)
         mov #addtrp,@#4
         clr r5
         mov @#177572,r1
         mov @#177574,r1
         mov @#177576,r1
         mov @#172516,r1
         mov (sp)+,@#4
         cmp r5,#0
         beq 1$
         error
1$:
;
;
;
tstm3:
         clr @#177572
         clr @#flag
         mov #172200,r3
1$:
         mov #177777,(r3)+
         cmp r3,#172400
         bne 1$
         mov #177600,r3
2$:
         mov #177777,(r3)+
         cmp r3,#177700
         bne 2$
         mov #172200,r3
3$:
         cmp (r3)+,#77417         ; orig 177416
         beq 4$
         error
4$:
         cmp r3,#172240
         bne 3$
5$:
         cmp (r3)+,#7777          ; orig 177777
         beq 6$
         error
6$:
         cmp r3,#172300
         bne 5$
7$:
         cmp (r3)+,#77417         ; orig 177416
         beq 8$
         error
8$:
         cmp r3,#172340
         bne 7$
9$:
         cmp (r3)+,#7777          ; orig 177777
         beq 10$
         error
10$:
         cmp r3,#172400
         bne 9$
         mov #177600,r3
11$:
         cmp (r3)+,#77417         ; orig 177416
         beq 12$
         error
12$:
         cmp r3,#177640
         bne 11$
13$:
         cmp (r3)+,#7777          ; orig 177777
         beq 14$
         error
14$:
         cmp r3,#177700
         bne 13$
         mov #172200,r3
15$:
         mov #0,(r3)+
         cmp r3,#172400
         bne 15$
         mov #177600,r3
16$:
         mov #0,(r3)+
         cmp r3,#177700
         bne 16$
         mov #172200,r3
17$:
         cmp (r3)+,#0
         beq 18$
         error
18$:
         cmp r3,#172400
         bne 17$
         mov #177600,r3
19$:
         cmp (r3)+,#0
         beq 20$
         error
20$:
         cmp r3,#177700
;
;
;
tstm4:
         clr @#177572
         clr flag
         mov #172200,r0
1$:
         mov #52404,(r0)+
         mov #125012,(r0)+
         cmp r0,#172240
         bne 1$
2$:
         mov #125252,(r0)+
         mov #52525,(r0)+
         cmp r0,#172300
         bne 2$
3$:
         mov #52404,(r0)+
         mov #125012,(r0)+
         cmp r0,#172340
         bne 3$
4$:
         mov #125252,(r0)+
         mov #52525,(r0)+
         cmp r0,#172400
         bne 4$
         mov #177600,r0
5$:
         mov #52404,(r0)+
         mov #125012,(r0)+
         cmp r0,#177640
         bne 5$
6$:
         mov #125252,(r0)+
         mov #52525,(r0)+
         cmp r0,#177700
         bne 6$

         mov #172200,r3
7$:
         mov (r3)+,r0
         bic #200,r0                  ; reset a bit
         cmp r0,#52404                ; original #52404 - acf triggers setting of a bit
         beq 8$
         error
8$:
         cmp (r3)+,#25012              ; original #125012
         beq 9$
         error
9$:
         cmp r3,#172240
         bne 7$
10$:
         cmp (r3)+,#5252               ; original #125252
         beq 11$
         error
11$:
         cmp (r3)+,#2525               ; original #52525
         beq 12$
         error
12$:
         cmp r3,#172300
         bne 10$
13$:
         mov (r3)+,r0
         bic #200,r0                  ; reset a bit
         cmp r0,#52404                ; original #52404 - acf triggers setting of a bit
         beq 14$
         error
14$:
         cmp (r3)+,#25012              ; original #125012
         beq 15$
         error
15$:
         cmp r3,#172340
         bne 13$
16$:
         cmp (r3)+,#5252               ; original #125252
         beq 17$
         error
17$:
         cmp (r3)+,#2525               ; original #52525
         beq 18$
         error
18$:
         cmp r3,#172400
         bne 16$
         mov #177600,r3
19$:
         mov (r3)+,r0
         bic #200,r0                  ; reset a bit
         cmp r0,#52404                ; original #52404 - acf triggers setting of a bit
         beq 20$
         error
20$:
         cmp (r3)+,#25012              ; original #125012
         beq 21$
         error
21$:
         cmp r3,#177640
         bne 19$
22$:
         cmp (r3)+,#5252               ; original #125252
         beq 23$
         error
23$:
         cmp (r3)+,#2525               ; original #52525
         beq 24$
         error
24$:
         cmp r3,#177700
         bne 22$
;
tstm4a:
         mov #172200,r0
25$:
         mov #125012,(r0)+
         mov #52404,(r0)+
         cmp r0,#172240
         bne 25$
26$:
         mov #52525,(r0)+
         mov #125252,(r0)+
         cmp r0,#172300
         bne 26$
27$:
         mov #125012,(r0)+
         mov #52404,(r0)+
         cmp r0,#172340
         bne 27$
28$:
         mov #52525,(r0)+
         mov #125252,(r0)+
         cmp r0,#172400
         bne 28$
         mov #177600,r0
29$:
         mov #125012,(r0)+
         mov #52404,(r0)+
         cmp r0,#177640
         bne 29$
30$:
         mov #52525,(r0)+
         mov #125252,(r0)+
         cmp r0,#177700
         bne 30$

         mov #172200,r3
31$:
         cmp (r3)+,#25012              ; original #125012
         beq 32$
         error
32$:
         mov (r3)+,r0
         bic #200,r0                  ; reset a bit
         cmp r0,#52404                ; original #52404 - acf triggers setting of a bit
         beq 33$
         error
33$:
         cmp r3,#172240
         bne 31$
34$:
         cmp (r3)+,#2525               ; original #52525
         beq 35$
         error
35$:
         cmp (r3)+,#5252               ; original #125252
         beq 36$
         error
36$:
         cmp r3,#172300
         bne 34$
37$:
         cmp (r3)+,#25012              ; original #125012
         beq 38$
         error
38$:
         mov (r3)+,r0
         bic #200,r0                  ; reset a bit
         cmp r0,#52404                ; original #52404 - acf triggers setting of a bit
         beq 39$
         error
39$:
         cmp r3,#172340
         bne 37$
40$:
         cmp (r3)+,#2525               ; original #52525
         beq 41$
         error
41$:
         cmp (r3)+,#5252               ; original #125252
         beq 42$
         error
42$:
         cmp r3,#172400
         bne 40$
         mov #177600,r3
43$:
         cmp (r3)+,#25012              ; original #125012
         beq 44$
         error
44$:
         mov (r3)+,r0
         bic #200,r0                  ; reset a bit
         cmp r0,#52404                ; original #52404 - acf triggers setting of a bit
         beq 45$
         error
45$:
         cmp r3,#177640
         bne 43$
46$:
         cmp (r3)+,#2525               ; original #52525
         beq 47$
         error
47$:
         cmp (r3)+,#5252               ; original #125252
         beq 48$
         error
48$:
         cmp r3,#177700
         bne 46$
;
;
;
tstm5:
         mov #160000,@#177572
         clr flag
         mov @#sr0,r0
         bic #176,r0
         cmp r0,#160000
         beq 1$
         error
1$:
         clr @#177572
         mov @#sr0,r0
         bic #176,r0
         cmp r0,#0
         beq 2$
         error
2$:
         mov #120000,@#177572
         mov @#sr0,r0
         bic #176,r0
         cmp r0,#120000
         beq 3$
         error
3$:
         mov #40000,@#177572
         mov @#sr0,r0
         bic #176,r0
         cmp r0,#40000
         beq 4$
         error
4$:
;
;
;
tstm6:
         clr @#177572
         clr flag
         mov #77,@#172516
         cmp @#172516,#17                ; original #77
         beq 1$
         error
1$:
         clr @#172516
         cmp @#172516,#0
         beq 2$
         error
2$:
         mov #52,@#172516
         cmp @#172516,#12                ; original #52
         beq 3$
         error
3$:
         mov #25,@#172516
         cmp @#172516,#5                 ; original #25
         beq 4$
         error
4$:
;
;
;
tstm7:
         clr @#177572
         clr @#flag
         mov #140000,@#177776
         mov #stbot,sp
         mov r6,@#savuse
         mov #40000,@#177776
         mov #stbot,sp
         mov r6,@#savsup
         mov #30000,@#177776
         jsr pc,mmu
         mov #27,@#172516
         mov @#244,-(sp)
         mov #177777,-(sp)
         mov #135072,@#244
         mov #77400,@#udpdr0
         mov #244,r3
         inc @#177572
         mfpi (r3)+
         cmp #30010,@#177776
         beq 1$
         error
1$:
         clr @#177572
         mov #140000,@#177776
         cmp r6,@#savuse
         beq 100$
         error
100$:
         mov #40000,@#177776
         cmp r6,@#savsup
         beq 200$
         error
200$:
         cmp @#244,#135072
         beq 2$
         error
2$:
         cmp r3,#246
         beq 3$
         error
3$:
         clr @#177776
         cmp (sp)+,#135072
         beq 4$
         error
4$:
         cmp (sp),#177777
         beq 5$
         error
5$:
         mov #30017,@#177776
         mov #173621,@#244
         mov #244,r1
         inc @#177572
         mfpi (r1)
         cmp #30011,@#177776
         beq 300$
         error
300$:
         clr @#177572
         cmp @#244,#173621
         beq 301$
         error
301$:
         cmp r1,#244
         beq 302$
         error
302$:
         clr @#177776
         cmp (sp)+,#173621
         beq 303$
         error
303$:
         cmp (sp),#177777
         beq 304$
         error
304$:
         clr r3
         inc @#177572
         mfpi r3
         cmp #4,@#177776
         beq 6$
         error
6$:
         clr @#177572
         cmp r3,#0
         beq 7$
         error
7$:
         cmp (sp)+,#0
         beq 8$
         error
8$:
         cmp (sp)+,#177777
         beq 9$
         error
9$:
         mov (sp)+,@#244
;
;
;
tstm10:
         clr @#177572
         clr @#flag
         mov #140000,@#177776
         mov r6,@#savuse
         mov #40000,@#177776
         mov r6,@#savsup
         mov #30000,@#177776
         jsr pc,mmu
         mov #27,@#172516
         mov @#244,-(sp)
         mov #177777,-(sp)
         mov #157002,@#244
         mov #77400,@#uipdr0
         mov #244,r3
         inc @#177572
         mfpd (r3)+
         cmp #30010,@#177776
         beq 1$
         error
1$:
         clr @#177572
         mov #140000,@#177776
         cmp r6,@#savuse
         beq 100$
         error
100$:
         mov #40000,@#177776
         cmp r6,@#savsup
         beq 200$
         error
200$:
         cmp @#244,#157002
         beq 2$
         error
2$:
         cmp r3,#246
         beq 3$
         error
3$:
         clr @#177776
         cmp (sp)+,#157002
         beq 4$
         error
4$:
         cmp (sp),#177777
         beq 5$
         error
5$:
         mov #30017,@#177776
         mov #103456,@#244
         mov #244,r1
         inc @#177572
         mfpd (r1)
         cmp #30011,@#177776
         beq 300$
         error
300$:
         clr @#177572
         cmp @#244,#103456
         beq 301$
         error
301$:
         cmp r1,#244
         beq 302$
         error
302$:
         clr @#177776
         cmp (sp)+,#103456
         beq 303$
         error
303$:
         cmp (sp),#177777
         beq 304$
         error
304$:
         mov #30017,@#177776
         mov #113672,@#244
         mov #246,r1
         inc @#177572
         mfpd -(r1)
         cmp #30011,@#177776
         beq 400$
         error
400$:
         clr @#177572
         cmp @#244,#113672
         beq 401$
         error
401$:
         cmp r1,#244
         beq 402$
         error
402$:
         clr @#177776
         cmp (sp)+,#113672
         beq 403$
         error
403$:
         cmp (sp),#177777
         beq 404$
         error
404$:
         clr r3
         inc @#177572
         mfpd r3
         cmp #4,@#177776
         beq 6$
         error
6$:
         clr @#177572
         cmp r3,#0
         beq 7$
         error
7$:
         cmp (sp)+,#0
         beq 8$
         error
8$:
         cmp (sp)+,#177777
         beq 9$
         error
9$:
         mov (sp)+,@#244
;
;
;
tstm11:
         clr @#177572
         clr @#flag
         mov #140000,@#177776
         mov r6,@#savuse
         mov #40000,@#177776
         mov r6,@#savsup
         mov #30000,@#177776
         jsr pc,mmu
         mov #27,@#172516
         mov @#244,-(sp)
         mov #177777,-(sp)
         mov #120413,-(sp)
         mov #177777,@#244
         mov #77400,@#udpdr0
         mov #244,r3
         inc @#177572
         mtpi (r3)+
         cmp #30010,@#177776
         beq 1$
         error
1$:
         clr @#177776
         mov #140000,@#177776
         cmp r6,@#savuse
         beq 100$
         error
100$:
         mov #40000,@#177776
         cmp r6,@#savsup
         beq 200$
         error
200$:
         cmp @#244,#120413
         beq 2$
         error
2$:
         cmp r3,#246
         beq 3$
         error
3$:
         clr @#177776
         cmp (sp),#177777
         beq 4$
         error
4$:
         mov #30017,@#177776
         mov #145121,-(sp)
         mov #244,r1
         inc @#177572
         mtpi (r1)
         cmp #30011,@#177776
         beq 300$
         error
300$:
         clr @#177572
         cmp @#244,#145121
         beq 301$
         error
301$:
         cmp r1,#244
         beq 302$
         error
302$:
         clr @#177776
         cmp (sp),#177777
         beq 304$
         error
304$:
         mov #30017,@#177776
         mov #122347,-(sp)
         mov #246,r1
         inc @#177572
         mtpi -(r1)
         cmp #30011,@#177776
         beq 400$
         error
400$:
         clr @#177572
         cmp @#244,#122347
         beq 401$
         error
401$:
         cmp r1,#244
         beq 402$
         error
402$:
         clr @#177776
         cmp (sp),#177777
         beq 404$
         error
404$:
         clr -(sp)
         inc @#177572
         mtpi r3
         cmp #4,@#177776
         beq 5$
         error
5$:
         clr @#177572
         cmp r3,#0
         beq 6$
         error
6$:
         cmp (sp)+,#177777
         beq 7$
         error
7$:
         mov (sp)+,@#244
;
;
;
tstm12:
         clr @#177572
         clr @#flag
         mov #140000,@#177776
         mov r6,@#savuse
         mov #40000,@#177776
         mov r6,@#savsup
         mov #30000,@#177776
         jsr pc,mmu
         mov #27,@#172516
         mov @#244,-(sp)
         mov #177777,-(sp)
         mov #100004,-(sp)
         mov #177777,@#244
         mov #77400,@#uipdr0
         mov #244,r3
         inc @#177572
         mtpd (r3)+
         cmp #30010,@#177776
         beq 1$
         error
1$:
         clr @#177572
         mov #140000,@#177776
         cmp r6,@#savuse
         beq 100$
         error
100$:
         mov #40000,@#177776
         cmp r6,@#savsup
         beq 200$
         error
200$:
         cmp @#244,#100004
         beq 2$
         error
2$:
         cmp r3,#246
         beq 3$
         error
3$:
         clr @#177776
         cmp (sp),#177777
         beq 4$
         error
4$:
         mov #30017,@#177776
         mov #100737,-(sp)
         mov #244,r1
         inc @#177572
         mtpd (r1)
         cmp #30011,@#177776
         beq 300$
         error
300$:
         clr @#177572
         cmp @#244,#100737
         beq 301$
         error
301$:
         cmp r1,#244
         beq 302$
         error
302$:
         clr @#177776
         cmp (sp),#177777
         beq 304$
         error
304$:
         mov #30017,@#177776
         mov #156711,-(sp)
         mov #246,r1
         inc @#177572
         mtpd -(r1)
         cmp #30011,@#177776
         beq 400$
         error
400$:
         clr @#177572
         cmp @#244,#156711
         beq 401$
         error
401$:
         cmp r1,#244
         beq 402$
         error
402$:
         clr @#177776
         cmp (sp),#177777
         beq 404$
         error
404$:
         clr -(sp)
         inc @#177572
         mtpd r3
         cmp #4,@#177776
         beq 5$
         error
5$:
         clr @#177572
         cmp r3,#0
         beq 6$
         error
6$:
         cmp (sp)+,#177777
         beq 7$
         error
7$:
         mov (sp)+,@#244
;
;
;
tstm13:
         clr @#177572
         mov #mmutrp,@#250
         clr @#flag
         mov @#214,-(sp)
         mov @#216,-(sp)
         clr savmr0
         clr savmr1
         clr savmr2
         jsr pc,mmu
         mov #30000,@#177776
         mov #200,r2
         mov #77400,@#177600
         jsr pc,ts7
;         mov #77404,@#177600          -- this is not the same for kt11c, acf 4 causes mmu traps
;         jsr pc,ts7
         mov #220,r1
         jsr pc,mmu
         clr r3
         mov #1,@#flag
         mov #1,@#177572
         mov #100000,@#177776
         mov (r2)+,-(r1)
         jsr pc,tsm7
         clr savmr0
         clr savmr1
         clr savmr2
         mov #0,r3                      ; #22; abort triggers before autoincrement
         mov #1,@#flag
         mov #1,@#177572
         mov #20000,@#177776
         mfpi (r2)+
         jsr pc,tsm7
         mov #30000,@#177776
         mov #77400,@#177600
         clr @#177572
         mfpi (r2)+
         mov (sp)+,r3
         mov (sp)+,@#216
         mov (sp)+,@#214
         jmp ts7fin
ts7:
         mov #1,flag
         mov #1,@#177572
         mov r7,r1
         mfpi (r2)+
         cmp #0,flag
         beq ok7
         error
ok7:
         clrb savmr0
         cmp #100000,savmr0
         beq oka7
         error
oka7:
         cmp savmr1,#0                      ; #22; abort triggers before autoincrement
         beq okay7
         error
okay7:
         cmp savmr2,r1
         beq okay7a
         error
okay7a:
         clr savmr0
         clr savmr1
         clr savmr2
         rts pc
tsm7:
         cmp #0,flag
         beq tsma
         error
tsma:
         bic #40377,@#savmr0
         cmp #100000,savmr0
         beq tsmb
         error
tsmb:
         cmp r3,savmr1
         beq tsmc
         error
tsmc:
         rts pc
ts7fin:
;
;
;
tstm14:
         clr @#177572
         mov #mmutrp,@#250
         clr @#flag
         mov @#244,-(sp)
         mov @#246,-(sp)
         clr savmr0
         clr savmr1
         clr savmr2
         jsr pc,mmu
         mov #30000,@#177776
         mov #244,r2
         mov #77402,@#177600
         mov #246,-(sp)                   ; can't really read what it says in the doc. 244 or 246. Don't understand the code either, and both seem to pass the tests. WTF???
         mov #1,flag
         mov #1,@#177572
         mov r7,r1
         mtpi (r2)+
         cmp #0,flag
         beq 1$
         error
1$:
         clrb savmr0
         cmp #20000,savmr0
         beq 2$
         error
2$:
         cmp #13022,savmr1            ; #11026 - this implementation reverses the updates during an mtpi
         beq 3$
         error
3$:
         cmp r1,savmr2
         beq 4$
         error
4$:
         cmp @#244,2(sp)
         beq 5$
         error
5$:
         mov #30000,@#177776
         mov #2,-(sp)
         mtpi (r2)+
         mov (sp)+,@#246
         mov (sp)+,@#244
;
;
;
tstm15:
         clr @#177572
         mov #mmutrp,@#250
         clr flag
         clr savmr0
         clr savmr1
         clr savmr2
         mov #30000,@#177776
         jsr pc,mmu
         mov #plf0,r3
         mov #bn0,r1
         mov #abort0,r2
         mov #26,@#172516
         jsr pc,tsm9
         mov #plf1,r3
         mov #bn1,r1
         mov #abort1,r2
         jsr pc,tsm9
         clr @#177572
         mov #plf1+10,r3
         mov #bn1+10,r1
         mov (r3),@#177600
         mfpi (r1)+
         mov (sp)+,r5
         jmp ts9fin
;
tsm9:
         mov (r3)+,@#177600
         mov r1,r0
         mov #1,flag
         mov #1,@#177572
         mov r7,r4
         mfpi @(r0)+
         cmp (r2),#0
         bne 2$
         mov (sp)+,r5
         cmp #1,flag
         beq 1$
         error
1$:
         br 6$
2$:
         cmp #0,flag
         beq 3$
         error
3$:
         clrb savmr0
         cmp #40000,savmr0
         beq 4$
         error
4$:
         cmp #0,savmr1                     ; original = 20
         beq 5$
         error
5$:
         cmp r4,savmr2
         beq 6$
         error
6$:
         clr flag
         clr savmr0
         clr savmr1
         clr savmr2
         inc r1
         inc r1
         inc r2
         inc r2
         cmp (r3),#777
         bne tsm9
         rts pc
;
plf0:
         .word 70006
         .word 70006
         .word 70006
         .word 13406
         .word 20006
         .word 04006
         .word 40006
         .word 70006
         .word 24006
         .word 04006
         .word 14006
         .word 12006
         .word 02006
         .word 01406
         .word 04006
         .word 02006
         .word 00406
         .word 07406
         .word 01006
         .word 03406
         .word 777

bn0:
         .word 013000
         .word 016000
         .word 017000
         .word 002700
         .word 014000
         .word 002000
         .word 004000
         .word 007000
         .word 002000
         .word 000700
         .word 004000
         .word 001000
         .word 000300
         .word 000400
         .word 001400
         .word 000600
         .word 000200
         .word 001700
         .word 000300
         .word 000700

abort0:
         .word 0
         .word 0
         .word 1
         .word 0
         .word 1
         .word 1
         .word 0
         .word 0
         .word 0
         .word 0
         .word 1
         .word 0
         .word 0
         .word 1
         .word 1
         .word 1
         .word 1
         .word 0
         .word 1
         .word 0

plf1:
         .word 00416
         .word 20016
         .word 24016
         .word 34016
         .word 74016
         .word 40016
         .word 20016
         .word 00016
         .word 30016
         .word 10016
         .word 14016
         .word 04016
         .word 02016
         .word 00416
         .word 00016
         .word 03416
         .word 01016
         .word 01416
         .word 00416
         .word 777

bn1:
         .word 000100
         .word 010000
         .word 006000
         .word 016000
         .word 016000
         .word 004000
         .word 000000
         .word 000000
         .word 004000
         .word 004000
         .word 004000
         .word 000000
         .word 000300
         .word 000000
         .word 000400
         .word 001000
         .word 000100
         .word 000400
         .word 000200

abort1:
         .word 0
         .word 0
         .word 0
         .word 0
         .word 1
         .word 1
         .word 1
         .word 0
         .word 1
         .word 0
         .word 0
         .word 1
         .word 1
         .word 1
         .word 0
         .word 0
         .word 1
         .word 0
         .word 0

ts9fin:
;
;
;
tstm16:
         clr @#177572
         mov #mmutrp,@#250
         clr flag
         clr savmr0
         clr savmr1
         clr savmr2
         jsr pc,mmu
         clr @#177776
         mov #20200,r2
         mov #77400,@#172302
         mov #1,flag
         mov #1,@#177572
         mov r7,r1
         mfpi (r2)+
         mov #100003,r4
         jsr pc,ts10
         mov #30000,@#177776
         jsr pc,mmu
         mov #77400,@#177636
         mov #1600,@#177676
         mov #160000,r2
         mov #1,flag
         mov #1,@#177572
         mov r7,r1
         mfpd (r2)+
         mov #100177,r4
         jsr pc,ts10
         mov #10000,@#177776
         jsr pc,mmu
         mov #77400,@#172212
         mov #120000,r2
         mov #1,flag
         mov #1,@#177572
         mov r7,r1
         mfpi (r2)+
         mov #100053,r4
         jsr pc,ts10
         mov #20000,@#177776
         jsr pc,mmu
         mov #40000,r2
         mov #1,flag
         mov #1,@#177572
         mov r7,r1
         mfpd (r2)+
         mov #100105,r4
         jsr pc,ts10
         jmp t10fin
;
ts10:
         cmp #0,flag
         beq 1$
         error
1$:
         cmp r4,savmr0
         beq 2$
         error
2$:
         cmp #0,savmr1              ; original #22
         beq 3$
         error
3$:
         cmp r1,savmr2
         beq 4$
         error
4$:
         clr savmr0
         clr savmr1
         clr savmr2
         rts pc
;
t10fin:
;
;
;
tstm17:
         clr @#177572
         mov #mmutrp,@#250
         clr flag
         mov #30000,@#177776
         mov #26,r1
         mov #177606,r3            ; original 610
         mov #21,r4
         jsr pc,ts11
         mov #0,@#177776
         mov #23,r1
         mov #172306,r3            ; original 310
         mov #24,r4
         jsr pc,ts11
         mov #10000,@#177776
         mov #25,r1
         mov #172206,r3            ; original 210
         mov #22,r4
         jsr pc,ts11
         jmp t11fin
;
ts11:
         jsr pc,mmu
         mov r1,@#172516
         mov #77400,(r3)
         mov #77774,r2             ; original 100000
         mov #1,flag
         mov #1,@#177572
         mfpd (r2)+
         cmp #0,flag
         beq 1$
         error
1$:
         mov r4,@#172516
         mov #77774,r2             ; original 100000
         mov #1,flag
         mov #1,@#177572
         mfpd (r2)+
         tst (sp)+
         cmp #1,flag
         beq 2$
         error
2$:
         clr flag
         rts pc
;
t11fin:
;
;
;
tstm21:
         clr @#177572
         mov #mmutrp,@#250
         clr flag
         clr @#177776
         jsr pc,mmu
         mov #0,@#172516
         mov #parad1,r3
         mov #parva1,r1
1$:
         mov (r1)+,@(r3)+
         cmp (r1),#333
         bne 1$
         mov #phy1,r3
         mov #vir1,r1
         mov #mode1,r2
2$:
         mov (r2)+,@#177776
         mov @(r3)+,r5
         mov #1,@#177572
         mfpi @(r1)+
         mov (sp)+,r4
         clr @#177572
         cmp r5,r4
         beq 3$
         error
3$:
         cmp (r3),#111
         bne 2$
         inc r3
         inc r3
         inc r1
         inc r1
         inc r2
         inc r2
         mov (r2)+,@#177776
         mov @(r3)+,r5
         mov #7,@#172516
         mov #1,@#177572
         mfpd @(r1)+
         mov (sp)+,r4
         clr @#177572
         clr @#172516
         cmp r5,r4
         beq 4$
         error
4$:
         jmp t13fin

parad1:
         .word 172240
         .word 177642
         .word 172252
         .word 177640
         .word 172242
         .word 172254
         .word 177652
         .word 177644
         .word 172246
         .word 177654
         .word 172250
         .word 177660
         .word 333

parva1:
         .word 0
         .word 10
         .word 177777
         .word 177601
         .word 10
         .word 52
         .word 70
         .word 10
         .word 10
         .word 60
         .word 0
         .word 10
         .word 333

vir1:
         .word 0
         .word 25000
         .word 135224
         .word 17700
         .word 33000
         .word 145252
         .word 121000
         .word 43000
         .word 75000
         .word 142000
         .word 117700
         .word 111
         .word 7000

phy1:
         .word 0
         .word 6000
         .word 15124
         .word 0
         .word 14000
         .word 12452
         .word 10000
         .word 4000
         .word 16000
         .word 10000
         .word 17700
         .word 111
         .word 10000

mode1:
         .word 10000
         .word 30000
         .word 10000
         .word 30000
         .word 10000
         .word 10000
         .word 30000
         .word 30000
         .word 10000
         .word 30000
         .word 10000
         .word 30000
         .word 30000

t13fin:
;
; end copy czkdkb0
;

;
; --------------------------------------------------------------------------------------------------
;
         mov #stk, sp
t14:
         inc r2
         clr r1
         mov #hello, r2
l1:
         tstb @#177564
         bpl l1
         movb (r2)+,r3
         bne l2
         jmp @#st
l2:
         movb r3, @#177566
         jmp @#l1
;
; data for czkdjb0
;
sloc00:  .word 0
sloc01:  .word 0
dcount:  .word 0

expdat:  .word 0

seq:     .word 0
sps:     .word 0
spsj:    .word 0
;
; subroutines for czkdkb0
;
mmu:
         mov r0,-(sp)
         mov r1,-(sp)
         mov r2,-(sp)
         mov #177600,r0
         jsr pc,pdr
         jsr pc,par
         jsr pc,par
         mov #172200,r0
         jsr pc,pdr
         jsr pc,par
         jsr pc,par
         jsr pc,pdr
         jsr pc,par
         jsr pc,par
         mov #27,@#172516
         mov (sp)+,r2
         mov (sp)+,r1
         mov (sp)+,r0
         rts pc
;
;
;
pdr:
         clr r2
pdr1:
         mov #77406,(r0)+
         add #1,r2
         cmp #16.,r2
         bne pdr1
         rts pc
;
;
;
par:
         clr r1
par1:
         mov r1,(r0)+
         add #200,r1
         cmp #1600,r1
         bne par1
         mov #7600,(r0)+               ; original 177600
         rts pc
;
;
;
addtrp:
         inc r5
         rti
;
;
;
mmutrp:
         cmp flag,#1
         beq 1$
         error
1$:
         mov r0,-(sp)
         mov @#177776,r0
         ash #-14,r0
         cmp r0,#2
         bne ok
         br notok
ok:
         mov @#177776,r0
         ash #2,r0
         ash #-14,r0
         cmp r0,#2
         bne ok1
notok:
         clr 4(sp)
ok1:
         mov @#177572,savmr0
         mov @#177574,savmr1
         mov @#177576,savmr2
         clr @#177572
         clr flag
         mov (sp)+,r0
         rti
;
; czkdkb0 data
;
savmr0:  .word 0
savmr1:  .word 0
savmr2:  .word 0
savuse:  .word 0
savsup:  .word 0
flag:    .word 0
;
;
;
count:   .word 0

         .even

hello:   .ascii /Hello, world: cpu t25/<15><12>
         .ascii /  regfile/<15><12>
         .ascii /  full mmu (without traps)/<15><12>
         .ascii /  psw on bus/<15><12>
         .ascii /  swab instr/<15><12>
         .ascii /  source in cvs/<15><12>
         .ascii /  generic blockram/<15><12>
         .ascii /  single 50mhz clock/<15><12>
         .ascii /  csdr/<15><12>
         .ascii /  pir/<15><12>
         .ascii / /<15><12>
         .ascii /  mfpi/<15><12>
         .ascii /  mfpd/<15><12>
         .ascii /  mtpi/<15><12>
         .ascii /  mtpd/<15><12>
         .ascii /  mfps/<15><12>
         .ascii /  mtps/<15><12>
         .ascii /  mfpt/<15><12>
         .ascii /  reset insn resets mmr0,mmr3,pir/<15><12>
         .ascii / /<15><12>
         .ascii /  mul/<15><12>
         .ascii /  div/<15><12>
         .ascii /  ash/<15><12>
         .ascii /  ashc/<15><12>
         .ascii /  xor/<15><12>
         .ascii /  tstset/<15><12>
         .ascii /  wrtlck/<15><12>
         .ascii / /<15><12>
         .ascii /  recoded slu w. input,output,interrupts/<15><12>
         .ascii /  kw11l w//interrupts/<15><12>
         .ascii /  wait insn waits until interrupt/<15><12>
         .ascii /  cpu error register/<15><12>
         .ascii /  stack limit register/<15><12>
         .ascii /  yellow stack traps/<15><12>
         .ascii /  red stack traps/<15><12>
         .ascii /  32 Kbytes core/<15><12>
         .ascii / /<15><12>
         .ascii /  t25 runs czkdjb0 tests 1-264 and modified czkdkb0 tests 1-17,21/<15><12>
         .ascii /  t204 is disabled in this source/
         .asciz / /<15><12>

         .even

tothier: .ascii /ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ/
