         .title test26 - early mmu tests copied from zkdk and adapted to work. Probably no longer useful.
         jmp st
;         .word 0   ;                    0
;         .word 0   ;                    2
         .word 0   ;                    4
         .word 0   ;                    6
         .word 0   ;                   10
         .word 0   ;                   12
         .word 0   ;                   14
         .word 0   ;                   16
         .word 0   ;                   20
         .word 0   ;                   22
         .word 0   ;                   24
         .word 0   ;                   26
         .word 0   ;                   30
         .word 0   ;                   32
         .word 0   ;                   34
         .word 0   ;                   36
         .word 0   ;                   40
         .word 0   ;                   42
         .word 0   ;                   44
         .word 0   ;                   46
         .word 0   ;                   50
         .word 0   ;                   52
         .word 0   ;                   54
         .word 0   ;                   56
         .word 0   ;                   60
         .word 0   ;                   62
         .word 0   ;                   64
         .word 0   ;                   66
         .word 0   ;                   70
         .word 0   ;                   72
         .word 0   ;                   74
         .word 0   ;                   76
         .word 0   ;                  100
         .word 0   ;                  102
         .word 0   ;                  104
         .word 0   ;                  106
         .word 0   ;                  110
         .word 0   ;                  112
         .word 0   ;                  114
         .word 0   ;                  116
         .word 0   ;                  120
         .word 0   ;                  122
         .word 0   ;                  124
         .word 0   ;                  126
         .word 0   ;                  130
         .word 0   ;                  132
         .word 0   ;                  134
         .word 0   ;                  136
         .word 0   ;                  140
         .word 0   ;                  142
         .word 0   ;                  144
         .word 0   ;                  146
         .word 0   ;                  150
         .word 0   ;                  152
         .word 0   ;                  154
         .word 0   ;                  156
         .word 0   ;                  160
         .word 0   ;                  162
         .word 0   ;                  164
         .word 0   ;                  166
         .word 0   ;                  170
         .word 0   ;                  172
         .word 0   ;                  174
         .word 0   ;                  176
         .word 0   ;                  200
         .word 0   ;                  202
         .word 0   ;                  204
         .word 0   ;                  206
         .word 0   ;                  210
         .word 0   ;                  212
         .word 0   ;                  214
         .word 0   ;                  216
         .word 0   ;                  220
         .word 0   ;                  222
         .word 0   ;                  224
         .word 0   ;                  226
         .word 0   ;                  230
         .word 0   ;                  232
         .word 0   ;                  234
         .word 0   ;                  236
         .word 0   ;                  240
         .word 0   ;                  242
         .word 0   ;                  244
         .word 0   ;                  246
         .word 0   ;                  250
         .word 0   ;                  252
         .word 0   ;                  254
         .word 0   ;                  256
         .word 0   ;                  260
         .word 0   ;                  262
         .word 0   ;                  264
         .word 0   ;                  266
         .word 0   ;                  270
         .word 0   ;                  272
         .word 0   ;                  274
         .word 0   ;                  276
         .word 0   ;                  300
         .word 0   ;                  302
         .word 0   ;                  304
         .word 0   ;                  306
         .word 0   ;                  310
         .word 0   ;                  312
         .word 0   ;                  314
         .word 0   ;                  316
         .word 0   ;                  320
         .word 0   ;                  322
         .word 0   ;                  324
         .word 0   ;                  326
         .word 0   ;                  330
         .word 0   ;                  332
         .word 0   ;                  334
         .word 0   ;                  336
         .word 0   ;                  340
         .word 0   ;                  342
         .word 0   ;                  344
         .word 0   ;                  346
         .word 0   ;                  350
         .word 0   ;                  352
         .word 0   ;                  354
         .word 0   ;                  356
         .word 0   ;                  360
         .word 0   ;                  362
         .word 0   ;                  364
         .word 0   ;                  366
         .word 0   ;                  370
         .word 0   ;                  372
         .word 0   ;                  374
         .word 0   ;                  376
         .word 0   ;                  400
         .word 0   ;                  402
         .word 0   ;                  404
         .word 0   ;                  406
         .word 0   ;                  410
         .word 0   ;                  412
         .word 0   ;                  414
         .word 0   ;                  416
         .word 0   ;                  420
         .word 0   ;                  422
         .word 0   ;                  424
         .word 0   ;                  426
         .word 0   ;                  430
         .word 0   ;                  432
         .word 0   ;                  434
         .word 0   ;                  436
         .word 0   ;                  440
         .word 0   ;                  442
         .word 0   ;                  444
         .word 0   ;                  446
         .word 0   ;                  450
         .word 0   ;                  452
         .word 0   ;                  454
         .word 0   ;                  456
         .word 0   ;                  460
         .word 0   ;                  462
         .word 0   ;                  464
         .word 0   ;                  466
         .word 0   ;                  470
         .word 0   ;                  472
         .word 0   ;                  474
         .word 0   ;                  476
stbot:
stk:
         .word 0   ;                  500
         .word 0   ;                  502
         .word 0   ;                  504
         .word 0   ;                  506
         .word 0   ;                  510
         .word 0   ;                  512
         .word 0   ;                  514
         .word 0   ;                  516
         .word 0   ;                  520
         .word 0   ;                  522
         .word 0   ;                  524
         .word 0   ;                  526
         .word 0   ;                  530
         .word 0   ;                  532
         .word 0   ;                  534
         .word 0   ;                  536
         .word 0   ;                  540
         .word 0   ;                  542
         .word 0   ;                  544
         .word 0   ;                  546
         .word 0   ;                  550
         .word 0   ;                  552
         .word 0   ;                  554
         .word 0   ;                  556
         .word 0   ;                  560
         .word 0   ;                  562
         .word 0   ;                  564
         .word 0   ;                  566
         .word 0   ;                  570
         .word 0   ;                  572
         .word 0   ;                  574
         .word 0   ;                  576
         .word 0   ;                  600
         .word 0   ;                  602
         .word 0   ;                  604
         .word 0   ;                  606
         .word 0   ;                  610
         .word 0   ;                  612
         .word 0   ;                  614
         .word 0   ;                  616
         .word 0   ;                  620
         .word 0   ;                  622
         .word 0   ;                  624
         .word 0   ;                  626
         .word 0   ;                  630
         .word 0   ;                  632
         .word 0   ;                  634
         .word 0   ;                  636
         .word 0   ;                  640
         .word 0   ;                  642
         .word 0   ;                  644
         .word 0   ;                  646
         .word 0   ;                  650
         .word 0   ;                  652
         .word 0   ;                  654
         .word 0   ;                  656
         .word 0   ;                  660
         .word 0   ;                  662
         .word 0   ;                  664
         .word 0   ;                  666
         .word 0   ;                  670
         .word 0   ;                  672
         .word 0   ;                  674
         .word 0   ;                  676
         .word 0   ;                  700
         .word 0   ;                  702
         .word 0   ;                  704
         .word 0   ;                  706
         .word 0   ;                  710
         .word 0   ;                  712
         .word 0   ;                  714
         .word 0   ;                  716
         .word 0   ;                  720
         .word 0   ;                  722
         .word 0   ;                  724
         .word 0   ;                  726
         .word 0   ;                  730
         .word 0   ;                  732
         .word 0   ;                  734
         .word 0   ;                  736
         .word 0   ;                  740
         .word 0   ;                  742
         .word 0   ;                  744
         .word 0   ;                  746
         .word 0   ;                  750
         .word 0   ;                  752
         .word 0   ;                  754
         .word 0   ;                  756
         .word 0   ;                  760
         .word 0   ;                  762
         .word 0   ;                  764
         .word 0   ;                  766
         .word 0   ;                  770
         .word 0   ;                  772
         .word 0   ;                  774
         .word 0   ;                  776
;
; misc definitions
;
ht       = 11
lf       = 12
cr       = 15
crlf     = 200
ps       = 177776
stklmt   = 177774
pirq     = 177772
dswr     = 177570
ddisp    = 177570

;
; general purpose register definitions
;
r0       = %0
r1       = %1
r2       = %2
r3       = %3
r4       = %4
r5       = %5
r6       = %6
r7       = %7
sp       = %6
pc       = %7
;
; priority level definitions
;
pr0      = 0
pr1      = 40
pr2      = 100
pr3      = 140
pr4      = 200
pr5      = 240
pr6      = 300
pr7      = 340
;
; kt11 register addresses
;
sr0      = 177572
sr1      = 177574
sr2      = 177576
sr3      = 172516
;
uipdr0   = 177600
uipdr1   = 177602
uipdr2   = 177604
uipdr3   = 177606
uipdr4   = 177610
uipdr5   = 177612
uipdr6   = 177614
uipdr7   = 177616
;
udpdr0   = 177620
udpdr1   = 177622
udpdr2   = 177624
udpdr3   = 177626
udpdr4   = 177630
udpdr5   = 177632
udpdr6   = 177634
udpdr7   = 177636
;
uipar0   = 177640
uipar1   = 177642
uipar2   = 177644
uipar3   = 177646
uipar4   = 177650
uipar5   = 177652
uipar6   = 177654
uipar7   = 177656
;
udpar0   = 177660
udpar1   = 177662
udpar2   = 177664
udpar3   = 177666
udpar4   = 177670
udpar5   = 177672
udpar6   = 177674
udpar7   = 177676
;
kipdr0   = 172300
kipdr1   = 172302
kipdr2   = 172304
kipdr3   = 172306
kipdr4   = 172310
kipdr5   = 172312
kipdr6   = 172314
kipdr7   = 172316
;
kipar0   = 172340
kipar1   = 172342
kipar2   = 172344
kipar3   = 172346
kipar4   = 172350
kipar5   = 172352
kipar6   = 172354
kipar7   = 172356
;
sipdr0   = 172200
sipdr1   = 172202
sipdr2   = 172204
sipdr3   = 172206
sipdr4   = 172210
sipdr5   = 172212
sipdr6   = 172214
sipdr7   = 172216
;
sipar0   = 172240
sipar1   = 172242
sipar2   = 172244
sipar3   = 172246
sipar4   = 172250
sipar5   = 172252
sipar6   = 172254
sipar7   = 172256





..n      = 0
         .macro error
..n      = ..n + 1
         mov #..n,@#ddisp
         halt
         .endm error
;
;
;

;         .=1000
st:
         mov #0, @#0             ; erase the jump at loc 0, so we know if we ended there
         inc @#count
         mov @#count,@#177570    ; keep count of how many loops we've done, and copy this into the display register
         mov #stk, sp
;
; tst1 - mtpi insn writes to previous instruction space
;
tst1:
         clr @#sr0               ; disable mmu
         mov #30000,@#177776     ; setup current mode=kernel, previous mode=user
         clr r1                  ; r1=0
         mov #125252,@#400       ; setup test data
         mov #0,@#kipar0         ;
         mov #77406,@#kipdr0     ; pdr 77406 - read/write, full block
         mov #4,@#uipar0         ; offset of 0x100 or o400
         mov #77406,@#uipdr0     ; pdr 77406 - read/write, full block
         mov #0,@#sr3
         mov #1,@#sr0            ; enable mmu
         mov #52525,-(r6)        ; push test data onto stack
         mtpi (r1)               ; --> test insn
         cmp #52525,@#400        ; check result
         beq 1$
         error
1$:
;
; tst2 - mtpd insn writes to previous instruction space
;
tst2:
         clr @#sr0               ; disable mmu
         mov #30000,@#177776     ; setup current mode=kernel, previous mode=user
         mov #4,r1               ; r1=4
         mov #125252,@#404       ; setup test data
         mov #0,@#kipar0         ;
         mov #77406,@#kipdr0     ; pdr 77406 - read/write, full block
         mov #3,@#uipar0         ; offset of o300
         mov #77406,@#uipdr0     ; pdr 77406 - read/write, full block
         mov #4,@#udpar0         ; offset of 0x100 or o400
         mov #77406,@#udpdr0     ; pdr 77406 - read/write, full block
         mov #0,@#sr3
         mov #1,@#sr0            ; enable mmu
         mov #52520,-(r6)        ; push test data onto stack
         mtpd (r1)               ; --> test insn -- should fail, because sr3=0, so data access is disabled
         cmp #125252,@#404       ; check unmodified, original data
         beq 1$
         error
1$:
         cmp #52520,@#304        ; check data arrived in insn space
         beq 2$
         error
2$:
         mov #1,@#sr3
         mov #52521,-(r6)        ; push test data onto stack
         mtpd (r1)               ; --> test insn
         cmp #52521,@#404        ; check result
         beq 3$
         error
3$:
;
; tst3 - mfpi insn reads from previous instruction space
;
tst3:
         clr @#sr0               ; disable mmu
         mov #30000,@#177776     ; setup current mode=kernel, previous mode=user
         clr r1                  ; r1=0
         mov #125252,@#400       ; setup test data
         mov #0,@#kipar0         ;
         mov #77406,@#kipdr0     ; pdr 77406 - read/write, full block
         mov #4,@#uipar0         ; offset of 0x100 or o400
         mov #77406,@#uipdr0     ; pdr 77406 - read/write, full block
         mov #0,@#sr3
         mov #1,@#sr0            ; enable mmu
         mfpi (r1)               ; --> test insn
         mov (r6)+,r1
         cmp #125252,r1          ; check result
         beq 1$
         error
1$:
;
; tst4 - mfpi insn reads from previous data space
;
tst4:
         clr @#sr0               ; disable mmu
         mov #30000,@#177776     ; setup current mode=kernel, previous mode=user
         clr r1                  ; r1=0
         mov #52525,@#400       ; setup test data
         mov #0,@#kipar0         ;
         mov #77406,@#kipdr0     ; pdr 77406 - read/write, full block
         mov #0,@#uipar0         ; offset of 0
         mov #77406,@#uipdr0     ; pdr 77406 - read/write, full block
         mov #4,@#udpar0         ; offset of 0x100 or o400
         mov #77406,@#udpdr0     ; pdr 77406 - read/write, full block
         mov #1,@#sr3
         mov #1,@#sr0            ; enable mmu
         mfpd (r1)               ; --> test insn
         mov (r6)+,r1
         cmp #52525,r1          ; check result
         beq 1$
         error
1$:
;
; end of tests from czkdjb0
;
;
; data for czkdjb0
;
sloc00:  .word 0
sloc01:  .word 0

expdat:  .word 0

seq:     .word 0
sps:     .word 0
spsj:    .word 0

count:   .word 0

         .even


tothier: .ascii /ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ/
