// For your readability, replace all '' in this file with white space
arm-none-eabi-gcc.exe-mcpu=cortex-m3-mthumb-I.-IGenerated_Source\PSoC5-Wa,-alh=.\CortexM3\ARM_GCC_541\Debug/main.lst-g-DDEBUG-DCY_CORE_ID=0-Wall-ffunction-sections-ffat-lto-objects-Og-cmain.c-o.\CortexM3\ARM_GCC_541\Debug\main.o
arm-none-eabi-gcc.exe-mcpu=cortex-m3-mthumb-I.-IGenerated_Source\PSoC5-Wa,-alh=.\CortexM3\ARM_GCC_541\Debug/FrontPanel.lst-g-DDEBUG-DCY_CORE_ID=0-Wall-ffunction-sections-ffat-lto-objects-Og-cFrontPanel.c-o.\CortexM3\ARM_GCC_541\Debug\FrontPanel.o
arm-none-eabi-gcc.exe-mcpu=cortex-m3-mthumb-I.-IGenerated_Source\PSoC5-Wa,-alh=.\CortexM3\ARM_GCC_541\Debug/Z80_SIO_emul.lst-g-DDEBUG-DCY_CORE_ID=0-Wall-ffunction-sections-ffat-lto-objects-Og-cZ80_SIO_emul.c-o.\CortexM3\ARM_GCC_541\Debug\Z80_SIO_emul.o
arm-none-eabi-gcc.exe-mcpu=cortex-m3-mthumb-I.-IGenerated_Source\PSoC5-Wa,-alh=.\CortexM3\ARM_GCC_541\Debug/Z80_IO_Handle.lst-g-DDEBUG-DCY_CORE_ID=0-Wall-ffunction-sections-ffat-lto-objects-Og-cZ80_IO_Handle.c-o.\CortexM3\ARM_GCC_541\Debug\Z80_IO_Handle.o
arm-none-eabi-gcc.exe-mcpu=cortex-m3-mthumb-I.-IGenerated_Source\PSoC5-Wa,-alh=.\CortexM3\ARM_GCC_541\Debug/Z80_PIO_emul.lst-g-DDEBUG-DCY_CORE_ID=0-Wall-ffunction-sections-ffat-lto-objects-Og-cZ80_PIO_emul.c-o.\CortexM3\ARM_GCC_541\Debug\Z80_PIO_emul.o
arm-none-eabi-gcc.exe-mcpu=cortex-m3-mthumb-I.-IGenerated_Source\PSoC5-Wa,-alh=.\CortexM3\ARM_GCC_541\Debug/Z80_6850_Emul.lst-g-DDEBUG-DCY_CORE_ID=0-Wall-ffunction-sections-ffat-lto-objects-Og-cZ80_6850_Emul.c-o.\CortexM3\ARM_GCC_541\Debug\Z80_6850_Emul.o
arm-none-eabi-gcc.exe-mcpu=cortex-m3-mthumb-I.-IGenerated_Source\PSoC5-Wa,-alh=.\CortexM3\ARM_GCC_541\Debug/Z80_SDCard_Emul.lst-g-DDEBUG-DCY_CORE_ID=0-Wall-ffunction-sections-ffat-lto-objects-Og-cZ80_SDCard_Emul.c-o.\CortexM3\ARM_GCC_541\Debug\Z80_SDCard_Emul.o
arm-none-eabi-gcc.exe-mcpu=cortex-m3-mthumb-I.-IGenerated_Source\PSoC5-Wa,-alh=.\CortexM3\ARM_GCC_541\Debug/Z80_6850_2_Emul.lst-g-DDEBUG-DCY_CORE_ID=0-Wall-ffunction-sections-ffat-lto-objects-Og-cZ80_6850_2_Emul.c-o.\CortexM3\ARM_GCC_541\Debug\Z80_6850_2_Emul.o
arm-none-eabi-gcc.exe-mcpu=cortex-m3-mthumb-I.-IGenerated_Source\PSoC5-Wa,-alh=.\CortexM3\ARM_GCC_541\Debug/Z80_Mem_Mappers.lst-g-DDEBUG-DCY_CORE_ID=0-Wall-ffunction-sections-ffat-lto-objects-Og-cZ80_Mem_Mappers.c-o.\CortexM3\ARM_GCC_541\Debug\Z80_Mem_Mappers.o
@mkdepend@C:\Users\dgilliland\Documents\GitHub\Retro-Computers\Z80\PSOC\PSOC_Design_Files\Z80-PSoC-3-Chips_002\Z80_3Pin.cydsn\CortexM3\ARM_GCC_541\Debug\SOURCE_C__ARM_GCC_GENERIC.txt
