/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var l=this||self,w=function(a,b){a=a.split(".");var c=l;a[0]in c||"undefined"==typeof c.execScript||c.execScript("var "+a[0]);for(var e;a.length&&(e=a.shift());)a.length||void 0===b?c=c[e]&&c[e]!==Object.prototype[e]?c[e]:c[e]={}:c[e]=b},x=function(a,b){function c(){}c.prototype=b.prototype;a.prototype=new c;a.prototype.constructor=a};var y=function(a){if(Error.captureStackTrace)Error.captureStackTrace(this,y);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))};x(y,Error);y.prototype.name="CustomError";var z=function(a,b){a=a.split("%s");for(var c="",e=a.length-1,d=0;d<e;d++)c+=a[d]+(d<b.length?b[d]:"%s");y.call(this,c+a[e])};x(z,y);z.prototype.name="AssertionError";var B=function(a,b,c){if(!a){var e="Assertion failed";if(b){e+=": "+b;var d=Array.prototype.slice.call(arguments,2)}throw new z(""+e,d||[]);}return a};var C=Array.prototype.forEach?function(a,b){B(null!=a.length);Array.prototype.forEach.call(a,b,void 0)}:function(a,b){for(var c=a.length,e="string"===typeof a?a.split(""):a,d=0;d<c;d++)d in e&&b.call(void 0,e[d],d,a)};var D;a:{var F=l.navigator;if(F){var G=F.userAgent;if(G){D=G;break a}}D=""}var H=function(a){return-1!=D.indexOf(a)};var I=function(){this.s=""};I.prototype.toString=function(){return"SafeStyle{"+this.s+"}"};I.prototype.h=function(a){this.s=a};(new I).h("");var J=function(){this.o=""};J.prototype.toString=function(){return"SafeStyleSheet{"+this.o+"}"};J.prototype.h=function(a){this.o=a};(new J).h("");var aa=-1!=D.toLowerCase().indexOf("webkit")&&!H("Edge")&&H("Mobile");try{(new self.OffscreenCanvas(0,0)).getContext("2d")}catch(a){};var ba=H("Safari")&&!((H("Chrome")||H("CriOS"))&&!H("Edge")||H("Coast")||H("Opera")||H("Edge")||H("Edg/")||H("OPR")||H("Firefox")||H("FxiOS")||H("Silk")||H("Android"))&&!(H("iPhone")&&!H("iPod")&&!H("iPad")||H("iPad")||H("iPod"));var M=function(a){var b=window;if(aa&&ba&&b){b.focus();var c=0,e=null;e=b.setInterval(function(){a.closed||5==c?(b.clearInterval(e),K(a)):(a.close(),c++)},150)}else a.close(),K(a)},K=function(a){if(!a.closed&&a.document&&a.document.body)if(a=a.document.body,B(null!=a,"goog.dom.setTextContent expects a non-null value for node"),"textContent"in a)a.textContent="Please close this window.";else if(3==a.nodeType)a.data="Please close this window.";else if(a.firstChild&&3==a.firstChild.nodeType){for(;a.lastChild!=
a.firstChild;)a.removeChild(B(a.lastChild));a.firstChild.data="Please close this window."}else{for(var b;b=a.firstChild;)a.removeChild(b);B(a,"Node cannot be null or undefined.");a.appendChild((9==a.nodeType?a:a.ownerDocument||a.document).createTextNode("Please close this window."))}};var ca=function(a){if(!a)return"";a=a.split("#")[0].split("?")[0];a=a.toLowerCase();0==a.indexOf("//")&&(a=window.location.protocol+a);/^[\w\-]*:\/\//.test(a)||(a=window.location.href);var b=a.substring(a.indexOf("://")+3),c=b.indexOf("/");-1!=c&&(b=b.substring(0,c));a=a.substring(0,a.indexOf("://"));if("http"!==a&&"https"!==a&&"chrome-extension"!==a&&"file"!==a&&"android-app"!==a&&"chrome-search"!==a&&"chrome-untrusted"!==a&&"chrome"!==a&&"app"!==a)throw Error("Invalid URI scheme in origin: "+a);
c="";var e=b.indexOf(":");if(-1!=e){var d=b.substring(e+1);b=b.substring(0,e);if("http"===a&&"80"!==d||"https"===a&&"443"!==d)c=":"+d}return a+"://"+b+c};var da=function(){function a(){d[0]=1732584193;d[1]=4023233417;d[2]=2562383102;d[3]=271733878;d[4]=3285377520;u=n=0}function b(g){for(var h=p,f=0;64>f;f+=4)h[f/4]=g[f]<<24|g[f+1]<<16|g[f+2]<<8|g[f+3];for(f=16;80>f;f++)g=h[f-3]^h[f-8]^h[f-14]^h[f-16],h[f]=(g<<1|g>>>31)&4294967295;g=d[0];var m=d[1],r=d[2],t=d[3],L=d[4];for(f=0;80>f;f++){if(40>f)if(20>f){var v=t^m&(r^t);var E=1518500249}else v=m^r^t,E=1859775393;else 60>f?(v=m&r|t&(m|r),E=2400959708):(v=m^r^t,E=3395469782);v=((g<<5|g>>>27)&4294967295)+
v+L+E+h[f]&4294967295;L=t;t=r;r=(m<<30|m>>>2)&4294967295;m=g;g=v}d[0]=d[0]+g&4294967295;d[1]=d[1]+m&4294967295;d[2]=d[2]+r&4294967295;d[3]=d[3]+t&4294967295;d[4]=d[4]+L&4294967295}function c(g,h){if("string"===typeof g){g=unescape(encodeURIComponent(g));for(var f=[],m=0,r=g.length;m<r;++m)f.push(g.charCodeAt(m));g=f}h||(h=g.length);f=0;if(0==n)for(;f+64<h;)b(g.slice(f,f+64)),f+=64,u+=64;for(;f<h;)if(k[n++]=g[f++],u++,64==n)for(n=0,b(k);f+64<h;)b(g.slice(f,f+64)),f+=64,u+=64}function e(){var g=[],
h=8*u;56>n?c(q,56-n):c(q,64-(n-56));for(var f=63;56<=f;f--)k[f]=h&255,h>>>=8;b(k);for(f=h=0;5>f;f++)for(var m=24;0<=m;m-=8)g[h++]=d[f]>>m&255;return g}for(var d=[],k=[],p=[],q=[128],A=1;64>A;++A)q[A]=0;var n,u;a();return{reset:a,update:c,digest:e,digestString:function(){for(var g=e(),h="",f=0;f<g.length;f++)h+="0123456789ABCDEF".charAt(Math.floor(g[f]/16))+"0123456789ABCDEF".charAt(g[f]%16);return h}}};var ea=function(a,b,c){var e=[];if(1==(Array.isArray(null)?2:1))return e=[b,a],C(c,function(q){e.push(q)}),N(e.join(" "));var d=[],k=[];C(null,function(q){k.push(q.key);d.push(q.value)});var p=Math.floor((new Date).getTime()/1E3);e=0==d.length?[p,b,a]:[d.join(":"),p,b,a];C(c,function(q){e.push(q)});a=N(e.join(" "));p=[p,a];0==k.length||p.push(k.join(""));return p.join("_")},N=function(a){var b=da();b.update(a);return b.digestString().toLowerCase()};var O=function(a){var b=a||[];a=[];for(var c=0,e=b.length;c<e;++c){var d=String(b[c]||"");d&&a.push(d)}if(2>a.length)return null;b=a[0];c=gadgets.rpc.getOrigin(a[1]);if(c!==a[1])return null;a=a.slice(2);return(a=(c&&b?["session_state",ea(ca(c),b,a||[])].join(" "):null)||"")&&a.substr(14)||null},P=function(a,b,c){this.j=String(a||"");this.f=String(b||"");this.b=String(c||"");this.a={};this.l=this.m=this.g=this.i="";this.c=null};
P.prototype.evaluate=function(){var a={},b="";try{b=String(document.cookie||"")}catch(p){}b=b.split("; ").join(";").split(";");for(var c=0,e=b.length;c<e;++c){var d=b[c],k=d.indexOf("=");-1!=k?a[d.substr(0,k)]=d.substr(k+1):a[d]=null}this.a=a;if(this.a.SAPISID||this.a.APISID||this.a["__Secure-3PAPISID"]||this.a.SID)if(this.f=this.f.split(".")[0].split("@")[0],this.g=Q(this,this.j))if(a=gadgets.rpc.getOrigin(String(window.location.href)),this.i=Q(this,a)){b=String(this.a.LSOLH||"").split(":");c=b.length;
if(1==c||4==c)this.m=b[0];if(3==c||4==c)a=String(b[c-3]||""),b=String(b[c-1]||""),c=this.i,a?(e=[a],c&&e.push(c),c=N(e.join(" ")).substr(0,4)):c=null,c===b&&(this.l=a);this.b&&(a=this.b.indexOf("."),-1!=a&&(a=this.b.substr(0,a)||"",this.b=a+"."+O([this.g,this.j,this.f,this.m,this.l,a]).substr(0,4)));a=O([this.g,this.j,this.f,this.b]);this.b&&(a=a+"."+this.b);this.c=a}else this.c="";else this.c=""};
var Q=function(a,b){(b=String(a.a[0==b.indexOf("https://")?"SAPISID":"APISID"]||""))||(b=String(a.a["__Secure-3PAPISID"]||""));return b};P.prototype.getVersionInfo=function(a){var b=parseInt(a,10);if(String(b)!=a||!(0<=b))return null;a=this.l;if(!a)return null;a=a.split("|");return a.length<=b?null:a[b]||null};
var R=function(a,b,c){a=new P(a,b,c);a.evaluate();return a},S=function(a,b,c){c=c||fa(this);var e=null;if(a){a=String(a);var d=a.indexOf(".");-1!=d&&(e=a.substr(d+1))}b=R(c,b,e).c;if(null==a||""==a)a=b==a;else if(null==b||b.length!=a.length)a=!1;else{e=c=0;for(d=a.length;e<d;++e)c|=a.charCodeAt(e)^b.charCodeAt(e);a=0==c}return a},T=function(a,b,c){c=c||fa(this);c=R(c);if(String(a)!=c.c)throw Error("Unauthorized request");return c.getVersionInfo(String(b))},fa=function(a){a=String(a.origin||"");if(!a)throw Error("RPC has no origin.");
return a};w("checkSessionState",S);w("getVersionInfo",T);var U,V,W,X,Y,Z,ha=window,ia=(window.location.href||ha.location.href).match(/.*(\?|#|&)usegapi=([^&#]+)/)||[];
"1"===decodeURIComponent(ia[ia.length-1]||"")?(W=function(a,b,c,e,d,k){U.send(b,d,e,k||gapi.iframes.CROSS_ORIGIN_IFRAMES_FILTER)},X=function(a,b){U.register(a,b,gapi.iframes.CROSS_ORIGIN_IFRAMES_FILTER)},Y=function(a){var b=/^(?:https?:\/\/)?[0-9.\-A-Za-z]+(?::\d+)?/.exec(a);b=gapi.iframes.makeWhiteListIframesFilter([b?b[0]:null]);W("..","oauth2callback",gadgets.rpc.getAuthToken(".."),void 0,a,b)},V=function(){ja()},Z=function(){W("..","oauth2relayReady",gadgets.rpc.getAuthToken(".."));X("check_session_state",
ka);X("get_versioninfo",la)}):(W=function(a,b,c,e,d){gadgets.rpc.call(a,b+":"+c,e,d)},X=function(a,b){gadgets.rpc.register(a,b)},Y=function(a){gadgets.rpc.getTargetOrigin("..")==gadgets.rpc.getOrigin(a)&&W("..","oauth2callback",gadgets.rpc.getAuthToken(".."),void 0,a)},V=function(){Z()},Z=function(){W("..","oauth2relayReady",gadgets.rpc.getAuthToken(".."));X("check_session_state",S);X("get_versioninfo",T)});
var ja=function(){var a=Z;window.gapi.load("gapi.iframes",function(){U=gapi.iframes.getContext().getParentIframe();a()})},ma=function(a){window.setTimeout(function(){Y(a)},1)},ka=function(a){if(a){var b=a.session_state;var c=a.client_id}return S(b,c,U.getOrigin())},la=function(a){return T(a.xapisidHash,a.sessionIndex,U.getOrigin())},na=!1,oa=!1,pa=function(){oa=!0;na&&V()};w("oauth2callback",ma);
w("oauth2verify",function(a,b){var c=window.open("about:blank",a),e;if(c&&!c.closed&&(e=c.oauth2callbackUrl))return window.timeoutMap=window.timeoutMap||{},window.realSetTimeout=window.realSetTimeout||window.setTimeout,window.setTimeout=function(d,k){try{var p=d,q=!1;d=function(){if(!q){q=!0;try{window.timeoutMap[String(n)]=void 0,delete window.timeoutMap[String(n)]}catch(u){}return p.call(this)}};var A=c.setTimeout(d,k);var n=window.realSetTimeout(d,k);window.timeoutMap[String(n)]=A;return n}catch(u){}return window.realSetTimeout(d,
k)},window.realClearTimeout=window.realClearTimeout||window.clearTimeout,window.clearTimeout=function(d){try{var k=window.timeoutMap[String(d)];k&&c.clearTimeout(k)}catch(p){}try{window.timeoutMap[String(d)]=void 0,delete window.timeoutMap[String(d)]}catch(p){}window.realClearTimeout(d)},ma(String(e)),"keep_open"!=b&&M(c),!0;c&&!c.closed&&M(c);return!1});w("init",function(){na=!0;oa&&V()});window.addEventListener?window.addEventListener("load",pa,!1):window.attachEvent("onload",pa);
